{AAC: {1042800: [[AAC, CA3c, [soma, basal, apical], AMPA, weight, 4.027705192565918],
      [AAC, ConMC, [soma, basal, apical], AMPA, weight, 3.63057017326355], [AAC, GC,
        [soma, basal, apical], AMPA, weight, 5.572389602661133], [AAC, HC, [apical,
          basal, soma], GABA_A, weight, 7.772492408752441], [AAC, HCC, [apical, basal,
          soma], GABA_A, weight, 4.6702351570129395], [AAC, IS, [apical, basal, soma],
        GABA_A, weight, 6.290884494781494], [AAC, LPP, [soma, basal, apical], AMPA,
        weight, 2.1849896907806396], [AAC, MC, [soma, basal, apical], AMPA, weight,
        4.715407848358154], [AAC, MOPP, [apical, basal, soma], GABA_A, weight, 4.851626396179199],
      [AAC, MPP, [soma, basal, apical], AMPA, weight, 6.75106954574585], [AAC, NGFC,
        apical, GABA_A, weight, 6.413921356201172], [AAC, NGFC, apical, GABA_B, weight,
        3.137484312057495]], 1042913: [[AAC, CA3c, [soma, basal, apical], AMPA, weight,
        4.045795917510986], [AAC, ConMC, [soma, basal, apical], AMPA, weight, 4.016985893249512],
      [AAC, GC, [soma, basal, apical], AMPA, weight, 6.668478488922119], [AAC, HC,
        [apical, basal, soma], GABA_A, weight, 2.1187283992767334], [AAC, HCC, [apical,
          basal, soma], GABA_A, weight, 5.458293437957764], [AAC, IS, [apical, basal,
          soma], GABA_A, weight, 4.010105133056641], [AAC, LPP, [soma, basal, apical],
        AMPA, weight, 6.9169769287109375], [AAC, MC, [soma, basal, apical], AMPA,
        weight, 6.26797342300415], [AAC, MOPP, [apical, basal, soma], GABA_A, weight,
        5.364426612854004], [AAC, MPP, [soma, basal, apical], AMPA, weight, 5.274762153625488],
      [AAC, NGFC, apical, GABA_A, weight, 4.953482627868652], [AAC, NGFC, apical,
        GABA_B, weight, 4.797976493835449]], 1043025: [[AAC, CA3c, [soma, basal, apical],
        AMPA, weight, 6.033484935760498], [AAC, ConMC, [soma, basal, apical], AMPA,
        weight, 5.578705787658691], [AAC, GC, [soma, basal, apical], AMPA, weight,
        5.616320610046387], [AAC, HC, [apical, basal, soma], GABA_A, weight, 4.299551010131836],
      [AAC, HCC, [apical, basal, soma], GABA_A, weight, 3.7512474060058594], [AAC,
        IS, [apical, basal, soma], GABA_A, weight, 6.336981773376465], [AAC, LPP,
        [soma, basal, apical], AMPA, weight, 6.9620513916015625], [AAC, MC, [soma,
          basal, apical], AMPA, weight, 6.229747772216797], [AAC, MOPP, [apical, basal,
          soma], GABA_A, weight, 7.145535469055176], [AAC, MPP, [soma, basal, apical],
        AMPA, weight, 6.67498254776001], [AAC, NGFC, apical, GABA_A, weight, 4.7488508224487305],
      [AAC, NGFC, apical, GABA_B, weight, 3.4947657585144043]], 1043138: [[AAC, CA3c,
        [soma, basal, apical], AMPA, weight, 6.561470985412598], [AAC, ConMC, [soma,
          basal, apical], AMPA, weight, 6.219306945800781], [AAC, GC, [soma, basal,
          apical], AMPA, weight, 3.9631621837615967], [AAC, HC, [apical, basal, soma],
        GABA_A, weight, 2.258424758911133], [AAC, HCC, [apical, basal, soma], GABA_A,
        weight, 5.846057891845703], [AAC, IS, [apical, basal, soma], GABA_A, weight,
        5.034092426300049], [AAC, LPP, [soma, basal, apical], AMPA, weight, 5.112180233001709],
      [AAC, MC, [soma, basal, apical], AMPA, weight, 4.667977333068848], [AAC, MOPP,
        [apical, basal, soma], GABA_A, weight, 2.4400391578674316], [AAC, MPP, [soma,
          basal, apical], AMPA, weight, 5.396890163421631], [AAC, NGFC, apical, GABA_A,
        weight, 3.5806305408477783], [AAC, NGFC, apical, GABA_B, weight, 2.221743106842041]],
    1043249: [[AAC, CA3c, [soma, basal, apical], AMPA, weight, 5.183590888977051],
      [AAC, ConMC, [soma, basal, apical], AMPA, weight, 4.191165924072266], [AAC,
        GC, [soma, basal, apical], AMPA, weight, 4.382809638977051], [AAC, HC, [apical,
          basal, soma], GABA_A, weight, 7.391737937927246], [AAC, HCC, [apical, basal,
          soma], GABA_A, weight, 3.6349098682403564], [AAC, IS, [apical, basal, soma],
        GABA_A, weight, 6.828073978424072], [AAC, LPP, [soma, basal, apical], AMPA,
        weight, 5.4630126953125], [AAC, MC, [soma, basal, apical], AMPA, weight, 4.248554706573486],
      [AAC, MOPP, [apical, basal, soma], GABA_A, weight, 7.172123908996582], [AAC,
        MPP, [soma, basal, apical], AMPA, weight, 8.660943984985352], [AAC, NGFC,
        apical, GABA_A, weight, 5.779860496520996], [AAC, NGFC, apical, GABA_B, weight,
        3.13289213180542]]}}
