{BC: {1039000: [[BC, BC, [apical, basal, soma], GABA_A, weight, 5.252769470214844],
      [BC, CA3c, [soma, basal, apical], AMPA, weight, 5.595545291900635], [BC, ConMC,
        [soma, basal, apical], AMPA, weight, 7.295633792877197], [BC, GC, [soma, basal,
          apical], AMPA, weight, 6.292196750640869], [BC, HC, [apical, basal, soma],
        GABA_A, weight, 0.0902332216501236], [BC, HCC, [apical, basal, soma], GABA_A,
        weight, 3.772529125213623], [BC, IS, [apical, basal, soma], GABA_A, weight,
        7.996270179748535], [BC, LPP, [soma, basal, apical], AMPA, weight, 4.571841239929199],
      [BC, MC, [soma, basal, apical], AMPA, weight, 3.2795379161834717], [BC, MOPP,
        [apical, basal, soma], GABA_A, weight, 3.8079161643981934], [BC, MPP, [soma,
          basal, apical], AMPA, weight, 2.5135769844055176], [BC, NGFC, apical, GABA_A,
        weight, 7.702312469482422], [BC, NGFC, apical, GABA_B, weight, 2.3946001529693604]],
    1039950: [[BC, BC, [apical, basal, soma], GABA_A, weight, 2.547353982925415],
      [BC, CA3c, [soma, basal, apical], AMPA, weight, 4.69939661026001], [BC, ConMC,
        [soma, basal, apical], AMPA, weight, 5.624050140380859], [BC, GC, [soma, basal,
          apical], AMPA, weight, 2.744365930557251], [BC, HC, [apical, basal, soma],
        GABA_A, weight, 0.19925574958324432], [BC, HCC, [apical, basal, soma], GABA_A,
        weight, 4.07317590713501], [BC, IS, [apical, basal, soma], GABA_A, weight,
        4.028637886047363], [BC, LPP, [soma, basal, apical], AMPA, weight, 5.572686195373535],
      [BC, MC, [soma, basal, apical], AMPA, weight, 5.326851844787598], [BC, MOPP,
        [apical, basal, soma], GABA_A, weight, 3.4305615425109863], [BC, MPP, [soma,
          basal, apical], AMPA, weight, 7.983126640319824], [BC, NGFC, apical, GABA_A,
        weight, 3.736579179763794], [BC, NGFC, apical, GABA_B, weight, 3.440234661102295]],
    1040900: [[BC, BC, [apical, basal, soma], GABA_A, weight, 4.9988508224487305],
      [BC, CA3c, [soma, basal, apical], AMPA, weight, 2.231027126312256], [BC, ConMC,
        [soma, basal, apical], AMPA, weight, 2.9660277366638184], [BC, GC, [soma,
          basal, apical], AMPA, weight, 4.681736946105957], [BC, HC, [apical, basal,
          soma], GABA_A, weight, 0.17310220003128052], [BC, HCC, [apical, basal, soma],
        GABA_A, weight, 0.8768512606620789], [BC, IS, [apical, basal, soma], GABA_A,
        weight, 5.796695709228516], [BC, LPP, [soma, basal, apical], AMPA, weight,
        4.708514213562012], [BC, MC, [soma, basal, apical], AMPA, weight, 3.7269115447998047],
      [BC, MOPP, [apical, basal, soma], GABA_A, weight, 3.544053316116333], [BC, MPP,
        [soma, basal, apical], AMPA, weight, 4.147136211395264], [BC, NGFC, apical,
        GABA_A, weight, 4.264327049255371], [BC, NGFC, apical, GABA_B, weight, 4.795489311218262]],
    1041850: [[BC, BC, [apical, basal, soma], GABA_A, weight, 1.8026096820831299],
      [BC, CA3c, [soma, basal, apical], AMPA, weight, 7.106821537017822], [BC, ConMC,
        [soma, basal, apical], AMPA, weight, 4.555238246917725], [BC, GC, [soma, basal,
          apical], AMPA, weight, 3.8772177696228027], [BC, HC, [apical, basal, soma],
        GABA_A, weight, 0.10235096514225006], [BC, HCC, [apical, basal, soma], GABA_A,
        weight, 3.42854642868042], [BC, IS, [apical, basal, soma], GABA_A, weight,
        8.639383316040039], [BC, LPP, [soma, basal, apical], AMPA, weight, 4.585087299346924],
      [BC, MC, [soma, basal, apical], AMPA, weight, 3.416624069213867], [BC, MOPP,
        [apical, basal, soma], GABA_A, weight, 4.885584354400635], [BC, MPP, [soma,
          basal, apical], AMPA, weight, 5.652233123779297], [BC, NGFC, apical, GABA_A,
        weight, 5.005306720733643], [BC, NGFC, apical, GABA_B, weight, 3.7509605884552]],
    1042799: [[BC, BC, [apical, basal, soma], GABA_A, weight, 3.986872911453247],
      [BC, CA3c, [soma, basal, apical], AMPA, weight, 6.285758018493652], [BC, ConMC,
        [soma, basal, apical], AMPA, weight, 3.4281609058380127], [BC, GC, [soma,
          basal, apical], AMPA, weight, 4.393231391906738], [BC, HC, [apical, basal,
          soma], GABA_A, weight, 0.26071515679359436], [BC, HCC, [apical, basal, soma],
        GABA_A, weight, 3.2534496784210205], [BC, IS, [apical, basal, soma], GABA_A,
        weight, 3.149905204772949], [BC, LPP, [soma, basal, apical], AMPA, weight,
        5.856886863708496], [BC, MC, [soma, basal, apical], AMPA, weight, 3.4542317390441895],
      [BC, MOPP, [apical, basal, soma], GABA_A, weight, 5.048715591430664], [BC, MPP,
        [soma, basal, apical], AMPA, weight, 7.6188530921936035], [BC, NGFC, apical,
        GABA_A, weight, 4.438721656799316], [BC, NGFC, apical, GABA_B, weight, 1.7213761806488037]]}}
