{HCC: {1043250: [[HCC, CA3c, [soma, basal, apical], AMPA, weight, 4.477283954620361],
      [HCC, GC, [soma, basal, apical], AMPA, weight, 4.367081642150879], [HCC, HCC,
        [apical, basal, soma], GABA_A, weight, 5.2369890213012695], [HCC, IS, [apical,
          basal, soma], GABA_A, weight, 4.8687591552734375], [HCC, LPP, [soma, basal,
          apical], AMPA, weight, 5.25836706161499], [HCC, MC, [soma, basal, apical],
        AMPA, weight, 5.950047492980957], [HCC, MOPP, [apical, basal, soma], GABA_A,
        weight, 6.337284564971924], [HCC, MPP, [soma, basal, apical], AMPA, weight,
        1.5583133697509766], [HCC, NGFC, apical, GABA_A, weight, 5.017030239105225],
      [HCC, NGFC, apical, GABA_B, weight, 8.044448852539062]], 1043600: [[HCC, CA3c,
        [soma, basal, apical], AMPA, weight, 4.477283954620361], [HCC, GC, [soma,
          basal, apical], AMPA, weight, 4.367081642150879], [HCC, HCC, [apical, basal,
          soma], GABA_A, weight, 5.2369890213012695], [HCC, IS, [apical, basal, soma],
        GABA_A, weight, 4.8687591552734375], [HCC, LPP, [soma, basal, apical], AMPA,
        weight, 5.25836706161499], [HCC, MC, [soma, basal, apical], AMPA, weight,
        5.950047492980957], [HCC, MOPP, [apical, basal, soma], GABA_A, weight, 6.337284564971924],
      [HCC, MPP, [soma, basal, apical], AMPA, weight, 1.5583133697509766], [HCC, NGFC,
        apical, GABA_A, weight, 5.017030239105225], [HCC, NGFC, apical, GABA_B, weight,
        8.044448852539062]], 1043950: [[HCC, CA3c, [soma, basal, apical], AMPA, weight,
        4.477283954620361], [HCC, GC, [soma, basal, apical], AMPA, weight, 4.367081642150879],
      [HCC, HCC, [apical, basal, soma], GABA_A, weight, 5.2369890213012695], [HCC,
        IS, [apical, basal, soma], GABA_A, weight, 4.8687591552734375], [HCC, LPP,
        [soma, basal, apical], AMPA, weight, 5.25836706161499], [HCC, MC, [soma, basal,
          apical], AMPA, weight, 5.950047492980957], [HCC, MOPP, [apical, basal, soma],
        GABA_A, weight, 6.337284564971924], [HCC, MPP, [soma, basal, apical], AMPA,
        weight, 1.5583133697509766], [HCC, NGFC, apical, GABA_A, weight, 5.017030239105225],
      [HCC, NGFC, apical, GABA_B, weight, 8.044448852539062]], 1044300: [[HCC, CA3c,
        [soma, basal, apical], AMPA, weight, 4.477283954620361], [HCC, GC, [soma,
          basal, apical], AMPA, weight, 4.367081642150879], [HCC, HCC, [apical, basal,
          soma], GABA_A, weight, 5.2369890213012695], [HCC, IS, [apical, basal, soma],
        GABA_A, weight, 4.8687591552734375], [HCC, LPP, [soma, basal, apical], AMPA,
        weight, 5.25836706161499], [HCC, MC, [soma, basal, apical], AMPA, weight,
        5.950047492980957], [HCC, MOPP, [apical, basal, soma], GABA_A, weight, 6.337284564971924],
      [HCC, MPP, [soma, basal, apical], AMPA, weight, 1.5583133697509766], [HCC, NGFC,
        apical, GABA_A, weight, 5.017030239105225], [HCC, NGFC, apical, GABA_B, weight,
        8.044448852539062]], 1044649: [[HCC, CA3c, [soma, basal, apical], AMPA, weight,
        4.477283954620361], [HCC, GC, [soma, basal, apical], AMPA, weight, 4.367081642150879],
      [HCC, HCC, [apical, basal, soma], GABA_A, weight, 5.2369890213012695], [HCC,
        IS, [apical, basal, soma], GABA_A, weight, 4.8687591552734375], [HCC, LPP,
        [soma, basal, apical], AMPA, weight, 5.25836706161499], [HCC, MC, [soma, basal,
          apical], AMPA, weight, 5.950047492980957], [HCC, MOPP, [apical, basal, soma],
        GABA_A, weight, 6.337284564971924], [HCC, MPP, [soma, basal, apical], AMPA,
        weight, 1.5583133697509766], [HCC, NGFC, apical, GABA_A, weight, 5.017030239105225],
      [HCC, NGFC, apical, GABA_B, weight, 8.044448852539062]]}}
