{IS: {1049650: [[IS, GC, [soma, basal, apical], AMPA, weight, 4.519564628601074],
      [IS, IS, [apical, basal, soma], GABA_A, weight, 5.380042552947998]], 1050400: [
      [IS, GC, [soma, basal, apical], AMPA, weight, 4.107705116271973], [IS, IS, [
          apical, basal, soma], GABA_A, weight, 2.310532331466675]], 1051150: [[IS,
        GC, [soma, basal, apical], AMPA, weight, 4.936081409454346], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 2.8918135166168213]], 1051900: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 6.082849979400635], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 3.3563108444213867]], 1052649: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 8.614535331726074], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 6.823266983032227]]}}
