{MOPP: {1052650: [[MOPP, HC, [apical, basal, soma], GABA_A, weight, 3.718125104904175],
      [MOPP, HCC, [apical, basal, soma], GABA_A, weight, 6.1620917320251465], [MOPP,
        LPP, [soma, basal, apical], AMPA, weight, 2.86087703704834], [MOPP, MC, [
          soma, basal, apical], AMPA, weight, 3.961167097091675], [MOPP, MOPP, [apical,
          basal, soma], GABA_A, weight, 3.8540711402893066], [MOPP, MPP, [soma, basal,
          apical], AMPA, weight, 5.519805431365967], [MOPP, NGFC, apical, GABA_A,
        weight, 3.1222317218780518], [MOPP, NGFC, apical, GABA_B, weight, 3.5336451530456543]],
    1053650: [[MOPP, HC, [apical, basal, soma], GABA_A, weight, 3.737441301345825],
      [MOPP, HCC, [apical, basal, soma], GABA_A, weight, 6.18481969833374], [MOPP,
        LPP, [soma, basal, apical], AMPA, weight, 2.864537239074707], [MOPP, MC, [
          soma, basal, apical], AMPA, weight, 3.942800521850586], [MOPP, MOPP, [apical,
          basal, soma], GABA_A, weight, 3.9126439094543457], [MOPP, MPP, [soma, basal,
          apical], AMPA, weight, 5.461088180541992], [MOPP, NGFC, apical, GABA_A,
        weight, 3.11093807220459], [MOPP, NGFC, apical, GABA_B, weight, 3.538125514984131]],
    1054650: [[MOPP, HC, [apical, basal, soma], GABA_A, weight, 4.602402687072754],
      [MOPP, HCC, [apical, basal, soma], GABA_A, weight, 6.206311225891113], [MOPP,
        LPP, [soma, basal, apical], AMPA, weight, 3.6238160133361816], [MOPP, MC,
        [soma, basal, apical], AMPA, weight, 4.936755657196045], [MOPP, MOPP, [apical,
          basal, soma], GABA_A, weight, 4.8520708084106445], [MOPP, MPP, [soma, basal,
          apical], AMPA, weight, 6.065963268280029], [MOPP, NGFC, apical, GABA_A,
        weight, 2.979074478149414], [MOPP, NGFC, apical, GABA_B, weight, 5.181460857391357]],
    1055650: [[MOPP, HC, [apical, basal, soma], GABA_A, weight, 4.602402687072754],
      [MOPP, HCC, [apical, basal, soma], GABA_A, weight, 6.206311225891113], [MOPP,
        LPP, [soma, basal, apical], AMPA, weight, 3.6238160133361816], [MOPP, MC,
        [soma, basal, apical], AMPA, weight, 4.936755657196045], [MOPP, MOPP, [apical,
          basal, soma], GABA_A, weight, 4.8520708084106445], [MOPP, MPP, [soma, basal,
          apical], AMPA, weight, 6.065963268280029], [MOPP, NGFC, apical, GABA_A,
        weight, 2.979074478149414], [MOPP, NGFC, apical, GABA_B, weight, 5.181460857391357]],
    1056649: [[MOPP, HC, [apical, basal, soma], GABA_A, weight, 3.7180991172790527],
      [MOPP, HCC, [apical, basal, soma], GABA_A, weight, 6.1619696617126465], [MOPP,
        LPP, [soma, basal, apical], AMPA, weight, 2.861093044281006], [MOPP, MC, [
          soma, basal, apical], AMPA, weight, 3.961282730102539], [MOPP, MOPP, [apical,
          basal, soma], GABA_A, weight, 3.8540732860565186], [MOPP, MPP, [soma, basal,
          apical], AMPA, weight, 5.519852161407471], [MOPP, NGFC, apical, GABA_A,
        weight, 3.1221930980682373], [MOPP, NGFC, apical, GABA_B, weight, 3.533689022064209]]}}
