{NGFC: {1044650: [[NGFC, HC, [apical, basal, soma], GABA_A, weight, 1.700950264930725],
      [NGFC, IS, [apical, basal, soma], GABA_A, weight, 5.230748176574707], [NGFC,
        LPP, [soma, basal, apical], AMPA, weight, 4.246274471282959], [NGFC, MOPP,
        [apical, basal, soma], GABA_A, weight, 2.395015001296997], [NGFC, MPP, [soma,
          basal, apical], AMPA, weight, 5.1007256507873535], [NGFC, NGFC, apical,
        GABA_A, weight, 3.214181423187256], [NGFC, NGFC, apical, GABA_B, weight, 1.5950367450714111]],
    1045900: [[NGFC, HC, [apical, basal, soma], GABA_A, weight, 1.6279414892196655],
      [NGFC, IS, [apical, basal, soma], GABA_A, weight, 1.7416908740997314], [NGFC,
        LPP, [soma, basal, apical], AMPA, weight, 6.089334011077881], [NGFC, MOPP,
        [apical, basal, soma], GABA_A, weight, 5.418954372406006], [NGFC, MPP, [soma,
          basal, apical], AMPA, weight, 4.931822776794434], [NGFC, NGFC, apical, GABA_A,
        weight, 2.6752374172210693], [NGFC, NGFC, apical, GABA_B, weight, 1.580226182937622]],
    1047150: [[NGFC, HC, [apical, basal, soma], GABA_A, weight, 1.7079401016235352],
      [NGFC, IS, [apical, basal, soma], GABA_A, weight, 7.631063938140869], [NGFC,
        LPP, [soma, basal, apical], AMPA, weight, 7.8372368812561035], [NGFC, MOPP,
        [apical, basal, soma], GABA_A, weight, 1.8614578247070312], [NGFC, MPP, [
          soma, basal, apical], AMPA, weight, 4.569197654724121], [NGFC, NGFC, apical,
        GABA_A, weight, 1.4140547513961792], [NGFC, NGFC, apical, GABA_B, weight,
        1.5904242992401123]], 1048400: [[NGFC, HC, [apical, basal, soma], GABA_A,
        weight, 3.4769160747528076], [NGFC, IS, [apical, basal, soma], GABA_A, weight,
        2.0239176750183105], [NGFC, LPP, [soma, basal, apical], AMPA, weight, 3.847139835357666],
      [NGFC, MOPP, [apical, basal, soma], GABA_A, weight, 4.163544654846191], [NGFC,
        MPP, [soma, basal, apical], AMPA, weight, 5.758337497711182], [NGFC, NGFC,
        apical, GABA_A, weight, 2.811591148376465], [NGFC, NGFC, apical, GABA_B, weight,
        2.0663139820098877]], 1049640: [[NGFC, HC, [apical, basal, soma], GABA_A,
        weight, 4.512772083282471], [NGFC, IS, [apical, basal, soma], GABA_A, weight,
        5.005661487579346], [NGFC, LPP, [soma, basal, apical], AMPA, weight, 4.325577735900879],
      [NGFC, MOPP, [apical, basal, soma], GABA_A, weight, 4.7349419593811035], [NGFC,
        MPP, [soma, basal, apical], AMPA, weight, 6.292125225067139], [NGFC, NGFC,
        apical, GABA_A, weight, 1.4134280681610107], [NGFC, NGFC, apical, GABA_B,
        weight, 3.853302001953125]]}}
