MC:
  1015624:
  - - MC
    - - HC
      - HCC
      - BC
    - apical
    - GABA_A
    - weight
    - 0.008049208666357688
  - - MC
    - AAC
    - ais
    - GABA_A
    - weight
    - 0.5114586445777161
  - - MC
    - BC
    - soma
    - GABA_A
    - weight
    - 0.34692051484191316
HCC:
  1043250:
  - - HCC
    - - MPP
      - LPP
    - apical
    - AMPA
    - weight
    - 1.0
  - - HCC
    - CA3c
    - - apical
      - basal
      - soma
    - AMPA
    - weight
    - 0.6566451470425374
  - - HCC
    - GC
    - - apical
      - basal
      - soma
    - AMPA
    - weight
    - 0.1001589952503415
  - - HCC
    - HCC
    - - apical
      - basal
    - GABA_A
    - weight
    - 0.010184933575811338
  - - HCC
    - IS
    - - apical
      - basal
      - soma
    - GABA_A
    - weight
    - 0.010087139798327274
  - - HCC
    - MC
    - - apical
      - basal
      - soma
    - AMPA
    - weight
    - 0.1
  - - HCC
    - MOPP
    - apical
    - GABA_A
    - weight
    - 0.5219992386275958
  - - HCC
    - NGFC
    - apical
    - GABA_A
    - weight
    - 0.44237633809465765
  - - HCC
    - NGFC
    - apical
    - GABA_B
    - weight
    - 0.005
NGFC:
  1044650:
  - - NGFC
    - HC
    - - apical
      - basal
      - soma
    - GABA_A
    - weight
    - 0.7942624235109325
  - - NGFC
    - MOPP
    - - apical
      - basal
      - soma
    - GABA_A
    - weight
    - 0.26829371642994915
  - - NGFC
    - NGFC
    - - apical
      - basal
      - soma
    - GABA_A
    - weight
    - 0.7054143677353365
  - - NGFC
    - NGFC
    - - apical
      - basal
      - soma
    - GABA_B
    - weight
    - 0.03594232440393129
IS:
  1049650:
  - - IS
    - GC
    - - apical
      - basal
      - soma
    - AMPA
    - weight
    - 1.9987717351292489
  - - IS
    - IS
    - - apical
      - basal
      - soma
    - GABA_A
    - weight
    - 0.034505548542686386
HC:
  1030000:
  - - HC
    - HC
    - apical
    - GABA_A
    - weight
    - 0.02467867705453928
  - - HC
    - IS
    - - apical
      - soma
    - GABA_A
    - weight
    - 0.07361009092147369
AAC:
  1042800:
  - - AAC
    - HC
    - apical
    - GABA_A
    - weight
    - 0.017154583774377043
  - - AAC
    - HCC
    - apical
    - GABA_A
    - weight
    - 0.03824009463686688
  - - AAC
    - IS
    - - apical
      - basal
    - GABA_A
    - weight
    - 0.10193042688561235
  - - AAC
    - MOPP
    - apical
    - GABA_A
    - weight
    - 0.04413096743705005
  - - AAC
    - NGFC
    - apical
    - GABA_A
    - weight
    - 0.9819332503174829
  - - AAC
    - NGFC
    - apical
    - GABA_B
    - weight
    - 0.020148053814486786
BC:
  1039000:
  - - BC
    - BC
    - - basal
      - soma
    - GABA_A
    - weight
    - 0.10512872302932394
  - - BC
    - HC
    - apical
    - GABA_A
    - weight
    - 0.9767981816616946
  - - BC
    - HCC
    - apical
    - GABA_A
    - weight
    - 0.5651116122142961
  - - BC
    - IS
    - - apical
      - basal
    - GABA_A
    - weight
    - 0.6691634599247661
  - - BC
    - MOPP
    - apical
    - GABA_A
    - weight
    - 0.11372389670573924
  - - BC
    - NGFC
    - apical
    - GABA_A
    - weight
    - 0.49944550843943536
  - - BC
    - NGFC
    - apical
    - GABA_B
    - weight
    - 0.11982843445053448
MOPP:
  1052650:
  - - MOPP
    - - MPP
      - LPP
    - apical
    - AMPA
    - weight
    - 0.26225296615059124
  - - MOPP
    - HC
    - - apical
      - basal
    - GABA_A
    - weight
    - 0.0424649570089991
  - - MOPP
    - HCC
    - - apical
      - basal
    - GABA_A
    - weight
    - 0.011366732283755834
  - - MOPP
    - MC
    - - basal
      - soma
    - AMPA
    - weight
    - 0.8409264441261144
  - - MOPP
    - MOPP
    - - apical
    - GABA_A
    - weight
    - 0.07609160797103993
  - - MOPP
    - NGFC
    - - apical
    - GABA_A
    - weight
    - 0.0945321262817779
  - - MOPP
    - NGFC
    - - apical
    - GABA_B
    - weight
    - 0.07647775509424784
