axon: {}
apical:
  synapses:
    NMDA:
      Kd:
        filters:
          syn_types:
          - excitatory
        value: 5.11520052441336
      gamma:
        filters:
          syn_types:
          - excitatory
        value: 0.07049474192334064
      vshift:
        filters:
          syn_types:
          - excitatory
        value: -3.2850118424061643
