ais:
  DGC_KM:
    gbar: {value: 0.009402899}
  cable:
    Ra: {origin: soma}
    cm: {origin: soma}
  ions:
    ek: {origin: soma}
  kap:
    gkabar: {value: 0.01037209}
  kdr:
    gkdrbar: {value: 0.06995454}
  nax:
    gbar: {value: 0.441262}
    sh: {origin: hillock}
    sha: {value: -4.897933}
  pas:
    e: {origin: soma}
    g: {origin: soma}
apical:
  cable:
    Ra: {origin: soma}
    cm: {origin: soma}
  ions:
    ek: {origin: soma}
  kad:
    gkabar:
    - {max_loc: 300.0, min_loc: 75.0, origin: soma, outside: 0.0, slope: 0.00034913669999999997,
      value: 0.0491930425}
    - {min_loc: 300.0, origin: soma, value: 0.1277488}
  kap:
    gkabar: {max_loc: 75.0, origin: soma, outside: 0.0, slope: 0.00034913669999999997}
  kdr:
    gkdrbar: {value: 0.008337353}
  nas:
    gbar:
    - {value: 0.02947238}
    - custom: {distance_th: 100.0, func: custom_filter_modify_slope_if_terminal}
      min: 0.00731045
      origin: parent
      slope: 0.0
    sh: {origin: soma}
    sha: {value: 0.0}
  pas:
    e: {origin: soma}
    g: {origin: soma, slope: 1.501397e-05, tau: 243.8052}
  synapses:
    AMPA:
      g_unit:
      - filters:
          syn_types: [excitatory]
        origin: soma
        slope: 1.801176e-06
        tau: 274.5544
        value: 0.0002830316
      - custom: {func: custom_filter_if_terminal}
        filters:
          syn_types: [excitatory]
        origin: parent
        origin_filters:
          syn_types: [excitatory]
      - filters:
          layers: [OML]
          syn_types: [excitatory]
        origin: apical
        origin_filters:
          layers: [MML]
          syn_types: [excitatory]
    NMDA:
      Kd:
        filters:
          syn_types: [excitatory]
        value: 3.573623
      g_unit:
        filters:
          syn_types: [excitatory]
        value: 0.006180688
      gamma:
        filters:
          syn_types: [excitatory]
        value: 0.07433832
      vshift:
        filters:
          syn_types: [excitatory]
        value: 7.438003
axon:
  DGC_KM:
    gbar: {origin: ais}
  cable:
    Ra: {origin: soma}
    cm: {origin: soma}
  ions:
    ek: {origin: soma}
  kap:
    gkabar: {origin: ais}
  kdr:
    gkdrbar: {origin: ais}
  nax:
    gbar: {value: 0.07628776}
    sh: {origin: hillock}
  pas:
    e: {origin: soma}
    g: {origin: soma}
hillock:
  DGC_KM:
    gbar: {value: 0.009402899}
  cable:
    Ra: {origin: soma}
    cm: {origin: soma}
  ions:
    ek: {origin: soma}
  kap:
    gkabar: {origin: soma}
  kdr:
    gkdrbar: {origin: soma}
  nax:
    gbar: {value: 0.03448583}
    sh: {value: 7.874204}
  pas:
    e: {origin: soma}
    g: {origin: soma}
soma:
  Ca:
    gcamult: {value: 0.4881511}
  Cacum:
    tau: {value: 61.55919}
  CadepK:
    gcakmult: {value: 6.505431}
  cable:
    Ra: {value: 150.0}
    cm: {value: 1.0}
  ions:
    ek: {value: -80.0}
  kap:
    gkabar: {value: 0.02300779}
  kdr:
    gkdrbar: {value: 0.04935162}
  nas:
    gbar: {value: 0.03448583}
    sh: {value: 7.874204}
  pas:
    e: {value: -72.39023}
    g: {value: 1.836953e-08}
