ais:
  DGC_KM:
    gbar:
      value: 0.006347139949009889
  cable:
    Ra:
      origin: soma
    cm:
      origin: soma
  ions:
    ek:
      origin: soma
  kap:
    gkabar:
      value: 0.004740797612810147
  kdr:
    gkdrbar:
      value: 0.07011679727657331
  nax:
    gbar:
      value: 0.3835593177859759
    sh:
      origin: hillock
    sha:
      value: -4.613881046908619
  pas:
    e:
      origin: soma
    g:
      origin: soma
apical:
  cable:
    Ra:
      origin: soma
    cm:
      origin: soma
  ions:
    ek:
      origin: soma
  kad:
    gkabar:
    - max_loc: 300.0
      min_loc: 75.0
      origin: soma
      outside: 0.0
      slope: 0.0003190407541902768
      value: 0.02908889401540784
    - min_loc: 300.0
      origin: soma
      value: 0.1008730637082201
  kap:
    gkabar:
      max_loc: 75.0
      origin: soma
      outside: 0.0
      slope: 0.0003190407541902768
  kdr:
    gkdrbar:
      value: 0.008972555754094972
  nas:
    gbar:
    - value: 0.023579467897683584
    - custom:
        distance_th: 100.0
        func: custom_filter_modify_slope_if_terminal
      min: 0.0028284270946139414
      origin: parent
      slope: 0.0
    sh:
      origin: soma
    sha:
      value: 0.0
  pas:
    e:
      origin: soma
    g:
      origin: soma
      slope: 2.2254039036942885e-05
      tau: 252.70146170082702
  synapses:
    AMPA:
      g_unit:
      - filters:
          syn_types:
          - excitatory
        origin: soma
        slope: 7.234999246130328e-07
        tau: 339.61312359874313
        value: 0.00020501099296229476
      - custom:
          func: custom_filter_if_terminal
        filters:
          syn_types:
          - excitatory
        origin: parent
        origin_filters:
          syn_types:
          - excitatory
      - filters:
          layers:
          - OML
          syn_types:
          - excitatory
        origin: apical
        origin_filters:
          layers:
          - MML
          syn_types:
          - excitatory
    NMDA:
      Kd:
        filters:
          syn_types:
          - excitatory
        value: 8.862931856382929
      f_inc:
        filters:
          syn_types:
          - excitatory
        value: 0.22696226294560612
      f_max:
        filters:
          syn_types:
          - excitatory
        value: 1.1149732792138145
      g_unit:
        filters:
          syn_types:
          - excitatory
        value: 0.0002512530523428524
      gamma:
        filters:
          syn_types:
          - excitatory
        value: 0.11188219761999567
      sat:
        filters:
          syn_types:
          - excitatory
        value: 0.7575098638439086
      vshift:
        filters:
          syn_types:
          - excitatory
        value: -37.10356913462222
axon:
  DGC_KM:
    gbar:
      origin: ais
  cable:
    Ra:
      origin: soma
    cm:
      origin: soma
  ions:
    ek:
      origin: soma
  kap:
    gkabar:
      origin: ais
  kdr:
    gkdrbar:
      origin: ais
  nax:
    gbar:
      value: 0.06565798588715413
    sh:
      origin: hillock
  pas:
    e:
      origin: soma
    g:
      origin: soma
hillock:
  DGC_KM:
    gbar:
      value: 0.006347139949009889
  cable:
    Ra:
      origin: soma
    cm:
      origin: soma
  ions:
    ek:
      origin: soma
  kap:
    gkabar:
      origin: soma
  kdr:
    gkdrbar:
      origin: soma
  nax:
    gbar:
      value: 0.04232462423724439
    sh:
      value: 7.905070112778596
  pas:
    e:
      origin: soma
    g:
      origin: soma
soma:
  Ca:
    gcamult:
      value: 0.2204785606330315
  Cacum:
    tau:
      value: 90.75560210330342
  CadepK:
    gcakmult:
      value: 9.414873200132982
  cable:
    Ra:
      value: 150.0
    cm:
      value: 1.0
  ions:
    ek:
      value: -80.0
  kap:
    gkabar:
      value: 0.005160837451137079
  kdr:
    gkdrbar:
      value: 0.06562062412873736
  nas:
    gbar:
      value: 0.04232462423724439
    sh:
      value: 7.905070112778596
  pas:
    e:
      value: -74.63715870306746
    g:
      value: 2.632149775788123e-08
