## Common definitions used in model configuration of dentate gyrus network
SWC Types:
  soma:   1
  axon:   2
  ais:    2
  basal:  3
  apical: 4
  trunk:  5 
  tuft:   6
Synapse Types:
  excitatory: 0
  inhibitory: 1
  neuromodulatory: 2
