params:
  g_pas0: 2.0e-6
  celsius:  25.0
  nao0: 145
  ko0: 4
  Ra_dend: 200
  Ra_axon: 110
  cm0: 1
  v_init: -80.0
  
  apical_gbar_Na: 0.05
  apical_initial_gmax_KA: 0.001
  apical_gmax_KA_scale: -0.02
  apical_gmax_KA_shift: 70
  apical_gbar_fKDR: 0.0002
  apical_gkbar_Kir: 0.001

  prox_gbar_Na: 0.05
  prox_gbar_fKDR: 0.002
  
  prox_gtcabar_Ca: 0.0012
  prox_gncabar_Ca: 0.0016
  prox_glcabar_Ca: 0.0060

  prox_gbar_BK: 0.009
  prox_gbar_Kv723: 0.001
  
  hillock_gbar_Na: 0.1 #0.009
  hillock_gmax_KA: 0.001
  hillock_gbar_fKDR: 0.004

  ais_gbar_Na: 0.4
  ais_gmax_KA: 0.002
  ais_gbar_fKDR: 0.002
  
  axon_gbar_scale: 0.25
  
  prox_tau_Ca: 15.0
    

spike detector:
  section: axon
  loc: 0.5
  threshold: -40
  delay: 0.05
  onset delay: 0.0
  distance: 50.0

  
apical:
  synapses:
    AMPA:
      g_unit:
#      - filters:
#          syn_types: [excitatory]
#        origin: soma
#        value: 0.00035
      - filters:
          syn_types: [excitatory]
        origin: soma
        slope: 1.0e-3
        tau: 300.0
        value: 0.0003
    NMDA:
      g_unit:
        filters:
          syn_types: [excitatory]
        value: 0.024
        #slope: 1.0e-2
        #tau: 300.0
        origin: soma
      gVI:
        filters:
          syn_types: [excitatory]
        value: 0.0001
      tau1_0:
        filters:
          syn_types:
          - excitatory
        value: 3.531
      tau2_0:
        filters:
          syn_types:
          - excitatory
        value: 62.5
      sh2:
        filters:
          syn_types:
          - excitatory
        value: 57.5
      sc2:
        filters:
          syn_types:
          - excitatory
        value: -0.12
      tau_D1:
        - filters:
            layers: [MML, OML]
            syn_types:
            - excitatory
          value: 185.0
        - filters:
            layers: [IML]
            syn_types:
            - excitatory
          value: 176.0
      tau_F:
        - filters:
            layers: [MML, OML]
            syn_types:
            - excitatory
          value: 109.0
        - filters:
            layers: [IML]
            syn_types:
              - excitatory
          value: 86.0
      delta_F:
        filters:
          syn_types:
          - excitatory
        value: 0.2
      tau_G1:
        filters:
          syn_types:
          - excitatory
        value: 4.03
      tau_G2:
        filters:
          syn_types:
          - excitatory
        value: 300.0
      Ginc:
        filters:
          syn_types:
          - excitatory
        value: 0.125
      Gmax:
        filters:
          syn_types:
          - excitatory
        value: 700.0
      tau_Gact:
        filters:
          syn_types:
          - excitatory
        value: 500.0
