PinskyRinzel:
  Ltotal: 39.25288391113281
  pp: 0.6877154111862183
  gc: 91.47968292236328
  soma_gmax_Na: 0.5072875022888184
  soma_gmax_K: 0.41890859603881836
  soma_g_pas: 0.0008144230814650655
  dend_gmax_Ca: 0.01694423146545887
  dend_gmax_KCa: 0.03828846290707588
  dend_g_pas: 0.0018682691734284163
  dend_beta_Caconc: 0.03628211468458176
  dend_d_Caconc: 11.543885231018066
  cm_ratio: 18.239519119262695
  dend_gmax_KAHP: 96.09903717041016
  global_diam: 10.0
  global_cm: 3.0
  e_pas: -62.0
  ic_constant: 0.0040512807
  V_threshold: -40.0
  V_rest: -66.0
apical:
  synapses:
    NMDA:
      g_unit:
        filters:
          syn_types: [excitatory]
        value: 0.05
      gVI:
        - filters:
            syn_types: [excitatory]
          value: 0.0005
      tau1_0:
        filters:
          syn_types:
          - excitatory
        value: 3.531
      tau2_0:
        filters:
          syn_types:
          - excitatory
        value: 100.0
      tau_D1:
        - filters:
            layers: [MML, OML]
            syn_types:
            - excitatory
          value: 185.0
        - filters:
            layers: [IML]
            syn_types:
            - excitatory
          value: 176.0
      tau_F:
        - filters:
            layers: [MML, OML]
            syn_types:
            - excitatory
          value: 109.0
        - filters:
            layers: [IML]
            syn_types:
              - excitatory
          value: 86.0
      delta_F:
        filters:
          syn_types:
          - excitatory
        value: 0.1
      tau_G1:
        filters:
          syn_types:
          - excitatory
        value: 2.03
      tau_G2:
        filters:
          syn_types:
          - excitatory
        value: 100.0
      Ginc:
        filters:
          syn_types:
          - excitatory
        value: 500.0
