param_config_name: 
feature_names:
- GC target rate dist residual
- MC target rate dist residual
- AAC firing rate
- AAC fraction active
- BC firing rate
- BC fraction active
- HC firing rate
- HC fraction active
- HCC firing rate
- HCC fraction active
- IS firing rate
- IS fraction active
- MOPP firing rate
- MOPP fraction active
- NGFC firing rate
- NGFC fraction active
objective_names:
- GC target rate dist residual
- MC target rate dist residual
- BC firing rate
- BC fraction active
- HC firing rate
- HC fraction active
- HCC firing rate
- HCC fraction active
- IS firing rate
- IS fraction active
- MOPP firing rate
- MOPP fraction active
- NGFC firing rate
- NGFC fraction active
kwargs:
  config_file: Network_Clamp_Slice_neg2000_neg1500um_IN_Izh.yaml
  tstop: 150.
  v_init: -77.
  vrecord_fraction: 0.05
  dt: 0.025
  cleanup: False
  verbose: True
  cache_queries: True
  output_results: False
  target_populations: ['GC', 'MC', 'AAC', 'BC', 'HC', 'HCC', 'IS', 'MOPP', 'NGFC']

