param_config_name: "Weight inh microcircuit"
objective_names:
- GC target rate dist residual
- MC target rate dist residual
- AAC firing rate
- BC firing rate
- HC firing rate
- HCC firing rate
- IS firing rate
- MOPP firing rate
- NGFC firing rate
target_populations: ['GC', 'MC', 'AAC', 'BC', 'HC', 'HCC', 'IS', 'MOPP', 'NGFC']
kwargs:
  config_file: Network_Clamp_Slice_neg2000_neg1500um_IN_Izh.yaml
  tstop: 9500.
  checkpoint_interval: 0.
  v_init: -77.
  vrecord_fraction: 0.05
  dt: 0.025
  cleanup: False
  verbose: True
  cache_queries: True
  output_results: False
  use_coreneuron: True

