param_config_name: "Weight inh microcircuit"
objective_names:
- GC target rate dist residual
- GC firing rate
- GC fraction active
- MC target rate dist residual
- MC firing rate
- MC fraction active
- BC firing rate
- BC fraction active
- HC firing rate
- HC fraction active
- HCC firing rate
- HCC fraction active
- IS firing rate
- IS fraction active
- MOPP firing rate
- MOPP fraction active
- NGFC firing rate
- NGFC fraction active
target_populations: ['GC', 'MC', 'AAC', 'BC', 'HC', 'HCC', 'IS', 'MOPP', 'NGFC']
kwargs:
  config_file: Network_Clamp_Slice_neg50_pos50um_IN_Izh.yaml
  tstop: 9500.
  checkpoint_interval: 0.
  v_init: -77.
  vrecord_fraction: 0.05
  dt: 0.025
  cleanup: False
  verbose: True
  cache_queries: True
  output_results: False
  use_coreneuron: True

