optimization_title: DG_optimize_network_clamp
param_gen: PopulationAnnealing
feature_names:
- GC in field max firing rate
- GC out of field mean firing rate
- GC in field mean state value
- GC out of field mean state value
objective_names:
- GC in field max firing rate
- GC out of field mean firing rate
- GC in field mean state value
- GC out of field mean state value
update_context:
- - optimize_network_clamp
  - update_network_clamp
get_features_stages:
- source: optimize_network_clamp
  compute_features: compute_features
get_objectives:
  optimize_network_clamp: get_objectives
kwargs:
  config_file: Network_Clamp_GC_Exc_Sat_SLN_extent.yaml
  input_features_namespaces: 
   - "Place Selectivity"
   - "Grid Selectivity"
   - "Constant Selectivity"
  tstop: 9500.
  v_init: -77.
  dt: 0.025
  cleanup: False
  verbose: True
  cache_queries: True
  output_results: False
  population: GC
  target_state_variable: v
