optimization_title: DG_test_network_subworlds
param_gen: PopulationAnnealing
bounds:
  BC_GC.GABA_A.g_unit: !!python/tuple
  - 0.00001
  - 0.01
param_names:
- BC_GC.GABA_A.g_unit
feature_names:
- firing_rate
objective_names:
- firing_rate
update_context:
- - DG_test_network_subworlds
  - update_network
get_features_stages:
- source: DG_test_network_subworlds
  compute_features: compute_features_firing_rate
get_objectives:
  DG_test_network_subworlds: get_objectives
kwargs:
  config: Full_Scale_GC_Exc_Sat_LNN.yaml
## config: Small_Scale_Control_test_load_LN_weights_Sat.yaml
  tstop: 10.
  v_init: -77.
  vrecord_fraction: 0.1
  dt: 0.025
  cleanup: False
  verbose: True
  cache_queries: True
  output_results: False
target_range:
  firing_rate: 1.
target_val:
  firing_rate: 1.
x0:
  BC_GC.GABA_A.g_unit: 0.00065
