## Model configuration of dentate gyrus network
Model Name: dentatenet_Full_Scale_Basis
Dataset Name: Full_Scale_Control
Definitions: !include Definitions.yaml
Global Parameters: !include Global.yaml
Geometry: !include Geometry.yaml
Random Seeds: !include Random.yaml
Connection Generator: !include Full_Scale_Connections.yaml
Recording: !include Recording.yaml
Stimulus: !include Input_Configuration.yaml
Analysis: !include Analysis_Configuration.yaml
## Cell types for dentate gyrus model
Cell Types:
  GC:
    template: DGC
    template file: DGC_Template_minimal.hoc
    mechanism file: 20220114_DG_GC_excitability_synint_combined_gid_118936_mech.yaml
    synapses:
      correct_for_spines: True
      density: !include GC_synapse_density.yaml
  MC:
    template: Cell
    template file: neuroh5_cell_template.hoc
    synapses:
      weights: !include MC_SLN_weights.yaml
      density: !include MC_synapse_density.yaml
  HC:
    template: Cell
    template file: neuroh5_cell_template.hoc
    mechanism file: DG_HICAP_PR_config.yaml
    synapses:
      density: !include HC_synapse_density.yaml
  BC:
    template: Cell
    template file: neuroh5_cell_template.hoc
    mechanism file: DG_BC_PR_config.yaml
    synapses:
      density: !include BC_synapse_density.yaml
  AAC:
    template: Cell
    template file: neuroh5_cell_template.hoc
    mechanism file: DG_AAC_PR_config.yaml
    synapses:
      density: !include AAC_synapse_density.yaml
  HCC:
    template: Cell
    template file: neuroh5_cell_template.hoc
    synapses:
      density: !include HCC_synapse_density.yaml
  NGFC:
    template: Cell
    template file: neuroh5_cell_template.hoc
    synapses:
      density: !include NGFC_synapse_density.yaml
  MOPP:
    template: Cell
    template file: neuroh5_cell_template.hoc
    synapses:
      density: !include NGFC_synapse_density.yaml
  IS:
    template: Cell
    template file: neuroh5_cell_template.hoc
    synapses:
      density: !include IS_synapse_density.yaml
  MPP:
    template: VecStim
  LPP:
    template: VecStim
  CA3c:
    template: VecStim
  ConMC:
    template: VecStim
    spike train:
      namespace: Input Spikes
      attribute: Spike Train

