Synapse Mechanisms:
  AMPA: Exp2Syn  # SatExp2Syn
  NMDA: FacilNMDA
  GABA_A: Exp2Syn  # SatExp2Syn
  GABA_B: Exp2Syn  # SatExp2Syn
Synapse Parameter Rules:
  SatExp2Syn:
    mech_file: sat_exp2syn.mod
    mech_params:
      - sat
      - dur_onset
      - tau_offset
      - e
    netcon_params:
      weight: 0
      g_unit: 1
  FacilExp2Syn:
    mech_file: facil_exp2syn.mod
    mech_params:
      - sat
      - dur_onset
      - tau_offset
      - e
      - f_inc
      - f_max
      - f_tau
    netcon_params:
      weight: 0
      g_unit: 1
  FacilNMDA:
    mech_file: facil_NMDA.mod
    mech_params:
      - sat
      - dur_onset
      - tau_offset
      - e
      - f_inc
      - f_max
      - f_tau
      - mg
      - Kd
      - gamma
    netcon_params:
      weight: 0
      g_unit: 1
  Exp2Syn:
    mech_file: exp2syn.mod
    mech_params:
      - tau1
      - tau2
      - e
    netcon_params:
      weight: 0
# full width in um [S-T, M-L]
Axon Width:
  GC:   [900., 900.]
  MPP:  [1500., 3000.]
  LPP:  [1500., 3000.]
  MC:   [4000., 4000.]
  NGFC: [2000., 2000.]
  AAC:  [1700., 1100.]
  BC:   [1700., 1000.]
  HCC:  [2600., 2600.]
  HC:   [3000., 3000.]
  IS:   [3000., 3000.]
  MOPP: [2000., 2000.]
Axon Offset:
    MC:   [1000., 1000.]
    GC:   [0., 0.]
    MPP:  [0., 0.]
    LPP:  [0., 0.]
    NGFC: [0., 0.]
    AAC:  [0., 0.]
    BC:   [0., 0.]
    HCC:  [0., 0.]
    HC:   [0., 0.]
    IS:   [0., 0.]
    MOPP: [0., 0.]
Synapses:
  GC:
    MPP:
      type: excitatory
      sections: [apical]
      layers: [MML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau1: 0.5
          tau2: 5.5
          e: 0
          weight: 0.0016
    LPP:
      type: excitatory
      sections: [apical]
      layers: [OML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau1: 0.5
          tau2: 5.5
          e: 0
          weight: 0.0018
    MC:   
      type: excitatory
      sections: [apical]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau1: 0.5
          tau2: 5.5
          e: 0
          weight: 0.00019
    AAC:
      type: inhibitory
      sections: [ais]
      layers: [GCL]
      proportions: [1.0]
      mechanisms:
        GABA_A:
          tau1: 0.3
          tau2: 2.9
          e: -75
          weight: 0.001
    BC:   
      type: inhibitory
      sections: [soma, apical]
      layers: [GCL, IML]
      proportions: [1.0, 0.69]
      mechanisms:
        GABA_A:
          tau1: 0.25
          tau2: 5.5
          e: -75
          weight: 0.00065
    HCC:  
      type: inhibitory
      sections: [apical]
      layers: [IML]
      proportions: [0.31]
      mechanisms:
        GABA_A:
          tau1: 0.4
          tau2: 1.1
          e: -75
          weight: 0.003
    HC:   
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.5, 0.5]
      mechanisms:
        GABA_A:
          tau1: 0.5
          tau2: 6.0
          e: -75
          weight: 0.006
    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.28, 0.28]
      mechanisms:
        GABA_A:
          tau1:  0.1
          tau2: 10.0
          e:   -75
          weight: 0.00015
        GABA_B:
          tau1:  50.0
          tau2: 200.0
          e:   -90
          weight: 0.0001
    MOPP: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.22, 0.22]
      mechanisms:
        GABA_A:
          tau1:  0.1
          tau2: 10.0
          e:   -75
          weight: 0.00015
  MC:
    GC:   
      type: excitatory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.23]
      mechanisms:
        AMPA:
          tau1: 0.5
          tau2: 6.2
          e: 0
          weight: 0.0015
    MC:   
      type: excitatory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.77]
      mechanisms:
        AMPA:
          tau1: 0.45
          tau2: 2.2
          e: 0
          weight: 0.0005
    HC:   
      type: inhibitory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.33]
      mechanisms:
        GABA_A:
          tau1: 0.5
          tau2: 6.0
          e: -75
          weight: 0.001
    BC:   
      type: inhibitory
      sections: [soma, apical]
      layers: [Hilus, Hilus]
      proportions: [1.0, 0.17]
      mechanisms:
        GABA_A:
          tau1: 0.3
          tau2: 3.3
          e: -75
          weight: 0.0015
    AAC:  
      type: inhibitory
      sections: [ais]
      layers: [GCL]
      proportions: [1.0]
      mechanisms:
        GABA_A:
          tau1: 0.3
          tau2: 3.3
          e: -75
          weight: 0.003
    HCC:  
      type: inhibitory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.5]
      mechanisms:
        GABA_A:
          tau1: 0.6
          tau2: 4.7
          e: -75
          weight: 0.0006
  HC:
    GC:   
      type: excitatory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.72]
      mechanisms:
        AMPA:
          tau1: 0.3
          tau2: 6.2
          e: 0
          weight: 0.0047
    MC:   
      type: excitatory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.28]
      mechanisms:
        AMPA:
          tau1: 0.9
          tau2: 3.6
          e: 0
          weight: 0.0022
    HC:  
      type: inhibitory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.99]
      mechanisms:
        GABA_A:
          tau1: 0.37
          tau2: 10.48
          e: -75
          weight: 0.000623
    IS:  
      type: inhibitory
      sections: [apical, soma]
      layers: [Hilus, Hilus]
      proportions: [0.01, 1.0]
      mechanisms:
        GABA_A:
          tau1: 0.37
          tau2: 10.48
          e: -75
          weight: 0.0005
  BC:
    GC:   
      type: excitatory
      sections: [basal, basal]
      layers: [Hilus, GCL]
      proportions: [1.0, 1.0]
      mechanisms:
        AMPA:
          tau1: 0.3
          tau2: 6.2
          e: 0
          weight: 0.0047
    MPP:
      type: excitatory
      sections: [apical]
      layers: [MML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau1:  0.5
          tau2: 3.0
          e:     0
          weight: 0.0005
    LPP:
      type: excitatory
      sections: [apical]
      layers: [OML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau1:  0.5
          tau2: 3.0
          e:     0
          weight: 0.0005
    MC:   
      type: excitatory
      sections: [apical]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau1: 0.9
          tau2: 3.6
          e: 0
          weight: 0.0003
    BC:   
      type: inhibitory
      sections: [basal, soma]
      layers: [Hilus, Hilus]
      proportions: [0.67, 1.0]
      mechanisms:
        GABA_A:
          tau1: 0.22
          tau2: 3.35
          e: -75
          weight: 0.00427
    HCC:  
      type: inhibitory
      sections: [apical]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        GABA_A:
          tau1: 0.6
          tau2: 4.78
          e: -75
          weight: 0.000664
    HC:   
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.96, 0.96]
      mechanisms:
        GABA_A:
          tau1: 0.46
          tau2: 4.43
          e: -75
          weight: 0.00214
    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.02, 0.02]
      mechanisms:
        GABA_A:
          tau1:   4.2
          tau2: 14.0
          e:    -75
          weight: 0.000183
        GABA_B:
          tau1:  50.0
          tau2: 200.0
          e:   -90
          weight: 0.000181
    MOPP: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.02, 0.02]
      mechanisms:
        GABA_A:
          tau1:   4.2
          tau2: 14.0
          e:    -75
          weight: 0.0002
    IS:
      type: inhibitory
      sections: [basal]
      layers: [Hilus]
      proportions: [0.33]
      mechanisms:
        GABA_A:
          tau1: 0.46
          tau2: 4.43
          e: -75
          weight: 0.00214
  AAC:
    GC:   
      type: excitatory
      sections: [basal, basal]
      layers: [Hilus, GCL]
      proportions: [1.0, 1.0]
      mechanisms:
        AMPA:
          tau1: 0.3
          tau2: 6.2
          e: 0
          weight: 0.0047
    MC:   
      type: excitatory
      sections: [apical]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau1: 0.9
          tau2: 3.6
          e: 0
          weight: 0.0003
    HCC:  
      type: inhibitory
      sections: [apical]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        GABA_A:
          tau1: 0.6
          tau2: 4.78
          e: -75
          weight: 0.000664
  HCC:
    MPP:
      type: excitatory
      sections: [apical]
      layers: [MML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau1: 0.5
          tau2: 5.0
          e: 0
          weight: 0.0005
    LPP:
      type: excitatory
      sections: [apical]
      layers: [OML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau1: 0.5
          tau2: 5.0
          e: 0
          weight: 0.0005
    GC:   
      type: excitatory
      sections: [basal]
      layers: [Hilus]
      proportions: [0.68]
      mechanisms:
        AMPA:
          tau1: 0.3
          tau2: 6.2
          e: 0
        weight: 0.0047
    MC:   
      type: excitatory
      sections: [basal, apical]
      layers: [Hilus, IML]
      proportions: [0.32, 1.0]
      mechanisms:
        AMPA:
          tau1: 0.9
          tau2: 3.6
          e: 0
          weight: 0.0023
    HCC:  
      type: inhibitory
      sections: [basal, apical]
      layers: [Hilus, IML]
      proportions: [0.3, 1.0]
      mechanisms:
        GABA_A:
          tau1: 0.72
          tau2: 4.7
          e: -75
          weight: 0.000325
    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.56, 0.56]
      mechanisms:
        GABA_A:
          tau1:  4.2
          tau2: 16.2
          e: -75
          weight: 0.000168
        GABA_B:
          tau1:  50.0  # https://physoc.onlinelibrary.wiley.com/doi/abs/10.1113/jphysiol.1993.sp019600
          tau2: 200.0  # http://www.jneurosci.org/content/33/18/7961
          e: -90
          weight: 0.000215
    MOPP: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.44, 0.44]
      mechanisms:
        GABA_A:
          tau1:  4.2
          tau2: 16.2
          e: -75
          weight: 0.000168
    IS: 
      type: inhibitory
      sections: [basal, soma]
      layers: [Hilus, Hilus]
      proportions: [0.7, 1.0]
      mechanisms:
        GABA_A:
          tau1: 0.46
          tau2: 4.43
          e: -75
          weight: 0.0005
  NGFC:
    MPP:
      type: excitatory
      sections: [basal]
      layers: [MML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau1: 0.5
          tau2: 5.0
          e: 0
          weight: 0.00025
    LPP:
      type: excitatory
      sections: [apical]
      layers: [OML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau1: 0.5
          tau2: 5.0
          e: 0
          weight: 0.00033
    HC:  
      type: inhibitory
      sections: [basal, apical]
      layers: [MML, OML]
      proportions: [0.86, 0.86]
      mechanisms:
        GABA_A:
          tau1: 0.72
          tau2: 4.7
          e: -75
          weight: 0.000473
    NGFC: 
      type: inhibitory
      sections: [basal, apical]
      layers: [MML, OML]
      proportions: [0.08, 0.08]
      mechanisms:
        GABA_A:
          tau1:  4.2
          tau2: 14.0
          e: -75
          weight: 0.000113
        GABA_B:
          tau1:  50.0
          tau2: 200.0
          e: -90
          weight: 0.000169
    MOPP: 
      type: inhibitory
      sections: [basal, apical]
      layers: [MML, OML]
      proportions: [0.06, 0.06]
      mechanisms:
        GABA_A:
          tau1:  4.2
          tau2: 14.0
          e: -75
          weight: 0.000113
  MOPP:
    MPP:
      type: excitatory
      sections: [basal]
      layers: [MML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau1: 0.5
          tau2: 5.0
          e: 0
          weight: 0.0010
    LPP:
      type: excitatory
      sections: [apical]
      layers: [OML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau1: 0.5
          tau2: 5.0
          e: 0
          weight: 0.0010
    MC:   
      type: excitatory
      sections: [basal]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau1: 0.9
          tau2: 3.6
          e: 0
          weight: 0.0005
    HC:  
      type: inhibitory
      sections: [basal, apical]
      layers: [MML, OML]
      proportions: [1.0, 0.86]
      mechanisms:
        GABA_A:
          tau1: 0.72
          tau2: 4.7
          e: -75
          weight: 0.000473
    HCC:  
      type: inhibitory
      sections: [basal]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        GABA_A:
          tau1: 0.72
          tau2: 4.7
          e: -75
          weight: 0.000325
    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.56, 0.08]
      mechanisms:
        GABA_A:
          tau1:  4.2
          tau2: 14.0
          e: -75
          weight: 0.000113
        GABA_B:
          tau1:  50.0
          tau2: 200.0
          e: -90
          weight: 0.000169
    MOPP: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.44, 0.06]
      mechanisms:
        GABA_A:
          tau1:  4.5
          tau2: 13.8
          e: -75
          weight: 0.000113
  IS:
    GC:   
      type: excitatory
      sections: [apical]
      layers: [Hilus]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau1: 0.3
          tau2: 6.2
          e: 0
          weight: 0.0005
    IS:   
      type: inhibitory
      sections: [apical, soma]
      layers: [Hilus, Hilus]
      proportions: [1.0, 1.0]
      mechanisms:
        GABA_A:
          tau1: 0.37
          tau2: 10.48
          e: -75
          weight: 0.0010
Connection Velocity:
  AAC: 250.0
  BC: 250.0
  HC: 250.0
  HCC: 250.0
  MC: 250.0
  NGFC: 250.0
  MOPP: 250.0
  MPP: 250.0
  LPP: 250.0
  IS: 250.0
  GC: 250.0
Gap Junctions:
  Locations:
    BC:
      AAC: [apical, basal]
      BC: [apical, basal]
    AAC:
      AAC: [apical, basal]
    HCC:
      HCC: [apical, basal]
    HC: 
      HC: [apical, basal]
    IS: 
      HC: [apical, basal]
      IS: [apical, basal]
    NGFC:
      NGFC: [apical]
    MOPP:
      MOPP: [apical, basal]
  Connection Probabilities:
    AAC, BC, HC, IS, HCC, NGFC, MOPP:
      - [0.286, 0.0,   0.0,  0.0,  0.0,   0.0,   0.0]
      - [0.286, 0.286, 0.0,  0.0,  0.0,   0.0,   0.0]
      - [0.0,   0.0,   0.19, 0.0,  0.0,   0.0,   0.0]
      - [0.0,   0.0,   0.19, 0.19, 0.0,   0.0,   0.0]
      - [0.0,   0.0,   0.0,  0.0,  0.085, 0.0,   0.0]
      - [0.786, 0.786, 0.0,  0.0,  0.786, 0.786, 0.0]
      - [0.786, 0.786, 0.0,  0.0,  0.786, 0.786, 0.786]
  ## Distance-dependent connection weights,
  ## based on Fig. 1C from Otsuka 2013
  Connection Weights: { 0: 1.0, 25: 0.429, 75: 0.405, 125: 0.345, 175: 0.08 }
  Connection Parameters: [0.4201,-0.0019,150.7465,0.0255]
  Coupling Coefficients:
    AAC:
      AAC: 0.017
    BC:
      BC: 0.017
    HC:
      HC: 0.13
    HCC:
      HCC: 0.04
    NGFC:
      NGFC: 0.0385
    MOPP:
      MOPP: 0.0385
  ## Distance-dependent coupling coefficient weights,
  ## Based on Fig. 6B from Amitai 2002
  Coupling Weights: { 0: 1.0, 25: 0.5, 75: 0.375, 125: 0.1875, 175: 0.1875 }
  Coupling Parameters: [0.0002,-0.0658,7.3211]
