Synapse Mechanisms:
  AMPA: Exp2Syn  # SatExp2Syn
  NMDA: FacilNMDA
  GABA_A: Exp2Syn  # SatExp2Syn
  GABA_B: Exp2Syn  # SatExp2Syn
Synapse Parameter Rules:
  SatExp2Syn:
    mech_file: sat_exp2syn.mod
    mech_params:
      - sat
      - dur_onset
      - tau_offset
      - e
    netcon_params:
      weight: 0
      g_unit: 1
  FacilExp2Syn:
    mech_file: facil_exp2syn.mod
    mech_params:
      - sat
      - dur_onset
      - tau_offset
      - e
      - f_inc
      - f_max
      - f_tau
    netcon_params:
      weight: 0
      g_unit: 1
  FacilNMDA:
    mech_file: facil_NMDA.mod
    mech_params:
      - sat
      - dur_onset
      - tau_offset
      - e
      - f_inc
      - f_max
      - f_tau
      - mg
      - Kd
      - gamma
    netcon_params:
      weight: 0
      g_unit: 1
  Exp2Syn:
    mech_file: exp2syn.mod
    mech_params:
      - tau1
      - tau2
      - e
    netcon_params:
      weight: 0
# full width in um [S-T, M-L]
Axon Width:
    GC:   [900., 900.]
    MPP:  [1500., 3000.]
    LPP:  [1500., 3000.]
    MC:   [4000., 4000.]
    NGFC: [2000., 2000.]
    AAC:  [1700., 1100.]
    BC:   [1700., 1000.]
    HCC:  [2600., 2600.]
    HC:   [3000., 3000.]
    IS:   [3000., 3000.]
    MOPP: [2000., 2000.]
Axon Offset:
    MC:   [1000., 1000.]
    GC:   [0., 0.]
    MPP:  [0., 0.]
    LPP:  [0., 0.]
    NGFC: [0., 0.]
    AAC:  [0., 0.]
    BC:   [0., 0.]
    HCC:  [0., 0.]
    HC:   [0., 0.]
    IS:   [0., 0.]
    MOPP: [0., 0.]
Axon Standard Deviation:
    GC:   0.4
    MC:   0.515
    NGFC: 0.45
    AAC:  0.45
    BC:   0.45
    HCC:  0.45
    HC:   0.45
    IS:   0.45
    MOPP: 0.45
    MPP:  1.0
    LPP:  1.0
Synapse Types:
    GC:
      MPP:  [excitatory]
      LPP:  [excitatory]
      MC:   [excitatory]
      NGFC: [inhibitory]
      AAC:  [inhibitory]
      BC:   [inhibitory]
      HCC:  [inhibitory]
      HC:   [inhibitory]
      MOPP: [inhibitory]
    MC:
      GC:   [excitatory]
      MC:   [excitatory]
      HC:   [inhibitory]
      BC:   [inhibitory]
      AAC:  [inhibitory]
      HCC:  [inhibitory]
    HC:
      GC:  [excitatory]
      MC:  [excitatory]
      HC:  [inhibitory]
      BC:  [inhibitory]
      IS:  [inhibitory]
    BC:
      GC:   [excitatory]
      MC:   [excitatory]
      HC:   [inhibitory]
      BC:   [inhibitory]
      HCC:  [inhibitory]
      NGFC: [inhibitory]
      MOPP: [inhibitory]
      IS:   [inhibitory]
      MPP:  [excitatory]
      LPP:  [excitatory]
    AAC:
      GC:   [excitatory]
      MC:   [excitatory]
      HC:   [inhibitory]
      NGFC: [inhibitory]
      MOPP: [inhibitory]
    HCC:
      GC:   [excitatory]
      MC:   [excitatory]
      BC:   [inhibitory]
      HCC:  [inhibitory]
      NGFC: [inhibitory]
      MOPP: [inhibitory]
      IS:   [inhibitory]
    NGFC:
      HC:   [inhibitory]
      NGFC: [inhibitory]
      MPP:  [excitatory]
      LPP:  [excitatory]
    MOPP:
      MC:   [excitatory]
      MOPP: [inhibitory]
      HC:   [inhibitory]
      HCC:  [inhibitory]
      MPP:  [excitatory]
    IS:
      GC:   [excitatory]
      IS:   [inhibitory]
Synapse Locations:
    GC:
      MPP:  [apical]
      LPP:  [apical]
      MC:   [apical]
      NGFC: [apical]
      AAC:  [ais]
      BC:   [soma, apical]
      MOPP: [apical]
      HCC:  [apical]
      HC:   [apical]
    MC:
      GC:   [apical]
      MC:   [apical]
      HC:   [apical]
      BC:   [soma, apical]
      AAC:  [soma]
      HCC:  [apical]
    HC:
      GC:   [apical, basal]
      MC:   [apical, basal]
      HC:   [apical, basal]
      BC:   [apical, basal]
      IS:   [apical, basal]
    BC:
      GC:   [apical, basal]
      MC:   [basal]
      HC:   [apical]
      BC:   [apical, basal]
      HCC:  [basal]
      NGFC: [apical, basal]
      MOPP: [apical, basal]
      IS:   [basal]
      MPP:  [apical]
      LPP:  [apical]
    AAC:
      GC: [apical, basal]
      MC: [basal]
      HC: [apical]
      NGFC: [apical, basal]
      MOPP: [apical, basal]
      IS:   [basal]
    HCC:
      GC: [apical, basal]
      MC: [basal]
      BC: [basal]
      HCC: [basal]
      NGFC: [apical, basal]
      MOPP: [apical, basal]
      IS:   [basal]
    NGFC:
      HC: [apical]
      NGFC: [apical]
      MOPP: [apical]
      MPP:  [basal]
      LPP:  [apical]
    MOPP:
      MC:   [basal, apical]
      MPP:  [apical]
      HC:   [basal]
      HCC:  [basal]
      MOPP: [apical]
      NGFC: [apical]
    IS:
      GC:   [apical, basal]
      IS:   [apical]
Synapse Layers:
    GC:
      MPP:  [MML]
      LPP:  [OML]
      MC:   [IML]
      AAC:  [GCL]
      BC:   [GCL, IML]
      NGFC: [MML, OML]
      MOPP: [MML, OML]
      HC:   [MML, OML]
      HCC:  [IML]
    MC:
      GC:  [Hilus]
      MC:  [Hilus]
      HC:  [IML]
      BC:  [Hilus]
      AAC: [Hilus]
      HCC: [IML]
    HC:
      GC:  [Hilus]
      MC:  [GCL]
      HC:  [Hilus]
      BC:  [GCL]
      IS:  [Hilus]
    BC:
      GC:   [Hilus, GCL]
      MC:   [Hilus]
      HC:   [MML]
      BC:   [GCL, IML]
      HCC:  [Hilus]
      NGFC: [MML, OML]
      MOPP: [MML, OML]
      IS:   [Hilus]
      MPP:  [MML]
      LPP:  [OML]
    AAC:
      GC:   [Hilus, GCL]
      MC:   [GCL]
      HC:   [IML, MML]
      NGFC: [MML, OML]
      MOPP: [MML, OML]
    HCC:
      GC:   [Hilus, GCL]
      MC:   [GCL]
      BC:   [GCL]
      HCC:  [GCL]
      NGFC: [OML]
      MOPP: [MML]
      IS:   [Hilus]
    NGFC:
      HC:   [MML, OML]
      NGFC: [OML]
      MPP:  [MML]
      LPP:  [OML]
    MOPP:
      MC:   [IML]
      MOPP: [MML]
      HC:   [IML]
      HCC:  [IML]
      MPP:  [MML]
    IS:
      GC:   [Hilus]
      IS:   [Hilus]
Synapse Proportions:
  GC:
    MPP:  [1.]
    LPP:  [1.]
    MC:   [1.]
    AAC:  [1.]
    BC:   [1., 0.1]
    NGFC: [0.15, 0.4]
    MOPP: [0.3, 0.3]
    HC:   [0.55, 0.3]
    HCC:  [0.9]
  MC:
    GC:  [0.45]
    MC:  [0.55]
    HC:  [0.5]
    BC:  [0.77]
    AAC: [0.23]
    HCC: [0.5]
  HC:
    MC:  [1.0]
    BC:  [1.0]
    GC:  [1.0]
    HC:  [0.75]
    IS:  [0.25]
  BC:
    GC:   [0.5, 0.5]
    MC:   [0.5]
    MPP:  [1.0]
    LPP:  [1.0]
    BC:   [0.1, 1.0]
    HCC:  [0.5]
    HC:   [0.34]
    NGFC: [0.33, 0.5]
    MOPP: [0.33, 0.5]
    IS:   [0.5]
  AAC:
    GC:   [0.5, 0.5]
    MC:   [0.5]
    HC:   [1.0, 0.9]
    NGFC: [0.05, 0.5]
    MOPP: [0.05, 0.5]
  HCC:
    GC:   [1.0, 0.5]
    MC:   [0.5]
    BC:   [0.2]
    HCC:  [0.8]
    NGFC: [1.0]
    MOPP: [1.0]
    IS:   [1.0]
  NGFC:
    HC:   [1.0, 0.66]
    NGFC: [0.34]
    MPP:  [1.0]
    LPP:  [1.0]
  MOPP:
    MC:   [1.0]
    MOPP: [1.0]
    HC:   [0.5]
    HCC:  [0.5]
    MPP:  [1.0]
  IS:
    GC:   [1.0]
    IS:   [1.0]
Synapse Kinetics:
  GC:
      GC:
        AMPA:
          tau1: 0.5
          tau2: 5.5
          e: 0
      MC:
        AMPA:
          tau1: 0.5
          tau2: 5.5
          e: 0
      MPP:
        AMPA:
          tau1: 0.5
          tau2: 5.5
          e: 0
      LPP:
        AMPA:
          tau1: 0.5
          tau2: 5.5
          e: 0
      HC:
        GABA_A:
          tau1: 0.5
          tau2: 6.0
          e: -75
      BC:
        GABA_A:
          tau1: 0.25
          tau2: 5.5
          e: -75
      AAC:
        GABA_A:
          tau1: 0.3
          tau2: 2.9
          e: -75
      HCC:
        GABA_A:
          tau1: 0.4
          tau2: 1.1
          e: -75
      NGFC:
        GABA_A:
          tau1:  0.1
          tau2: 10.0
          e:   -75
        GABA_B:
          tau1:  86.8
          tau2: 428.1
          e:   -90
      MOPP:
        GABA_A:
          tau1:  0.1
          tau2: 10.0
          e:   -75
  MC:
      GC:
        AMPA:
          tau1: 0.5
          tau2: 6.2
          e: 0
      MC:
        AMPA:
          tau1: 0.45
          tau2: 2.2
          e: 0
      HC:
        GABA_A:
          tau1: 0.5
          tau2: 6.0
          e: -75
      BC:
        GABA_A:
          tau1: 0.3
          tau2: 3.3
          e: -75
      AAC:
        GABA_A:
          tau1: 0.3
          tau2: 3.3
          e: -75
      HCC:
        GABA_A:
          tau1: 0.6
          tau2: 4.7
          e: -75
  HC:
      GC:
        AMPA:
          tau1: 0.3
          tau2: 6.2
          e: 0
      MC:
        AMPA:
          tau1: 0.9
          tau2: 3.6
          e: 0
      HC:
        GABA_A:
          tau1: 0.37
          tau2: 10.48
          e: -75
      BC:
        GABA_A:
          tau1: 0.265
          tau2: 2.88
          e: -75
      IS:
        GABA_A:
          tau1: 0.37
          tau2: 10.48
          e: -75
  BC:
      GC:
        AMPA:
          tau1: 0.3
          tau2: 6.2
          e: 0
      MC:
        AMPA:
          tau1: 0.9
          tau2: 3.6
          e: 0
      MPP:
        AMPA:
          tau1:  0.5
          tau2: 3.0
          e:     0
      LPP:
        AMPA:
          tau1:  0.5
          tau2: 3.0
          e:     0
      HC:
        GABA_A:
          tau1: 0.46
          tau2: 4.43
          e: -75
      BC:
        GABA_A:
          tau1: 0.22
          tau2: 3.35
          e: -75
      HCC:
        GABA_A:
          tau1: 0.6
          tau2: 4.78
          e: -75
      NGFC:
        GABA_A:
          tau1:   4.2
          tau2: 14.0
          e:    -75
        GABA_B:
          tau1:  86.8
          tau2: 428.1
          e:   -90
      MOPP:
        GABA_A:
          tau1:   4.2
          tau2: 14.0
          e:    -75
      IS:
        GABA_A:
          tau1: 0.46
          tau2: 4.43
          e: -75
  AAC:
      GC:
        AMPA:
          tau1: 0.3
          tau2: 6.2
          e: 0
      MC:
        AMPA:
          tau1: 0.9
          tau2: 3.6
          e: 0
      HC:
        GABA_A:
          tau1: 0.46
          tau2: 4.43
          e: -75
      NGFC:
        GABA_A:
          tau1:  4.2
          tau2: 14.0
          e: -75
        GABA_B:
          tau1:  86.8
          tau2: 428.1
          e: -90
      MOPP:
        GABA_A:
          tau1:  4.2
          tau2: 14.0
          e: -75
      IS:
        GABA_A:
          tau1: 0.46
          tau2: 4.43
          e: -75
  HCC:
      GC:
        AMPA:
          tau1: 0.3
          tau2: 6.2
          e: 0
      MC:
        AMPA:
          tau1: 0.9
          tau2: 3.6
          e: 0
      BC:
        GABA_A:
          tau1: 0.28
          tau2: 3.45
          e: -75
      HCC:
        GABA_A:
          tau1: 0.72
          tau2: 4.7
          e: -75
      IS:
        GABA_A:
          tau1: 0.46
          tau2: 4.43
          e: -75
      MOPP:
        GABA_A:
          tau1:  4.2
          tau2: 16.2
          e: -75
      NGFC:
        GABA_A:
          tau1:  4.2
          tau2: 16.2
          e: -75
        GABA_B:
          tau1: 86.8  # 50.0  https://physoc.onlinelibrary.wiley.com/doi/abs/10.1113/jphysiol.1993.sp019600
          tau2: 428.1  # 200.0  http://www.jneurosci.org/content/33/18/7961
          e: -90
  NGFC:
      MPP:
        AMPA:
          tau1: 3.0
          tau2: 30.0
          e: 0
      LPP:
        AMPA:
          tau1: 3.0
          tau2: 30.0
          e: 0
      HC:
        GABA_A:
          tau1: 0.72
          tau2: 4.7
          e: -75
      IS:
        GABA_A:
          tau1: 0.46
          tau2: 4.43
          e: -75
      NGFC:
        GABA_A:
          tau1:  4.2
          tau2: 14.0
          e: -75
        GABA_B:
          tau1:  86.8
          tau2: 428.1
          e: -90
  MOPP:
      MPP:
        AMPA:
          tau1: 0.5
          tau2: 3.0
          e: 0
      MC:
        AMPA:
          tau1: 0.9
          tau2: 3.6
          e: 0
      BC:
        GABA_A:
          tau1: 0.72
          tau2: 10.0
          e: -75
      HC:
        GABA_A:
          tau1: 0.72
          tau2: 4.7
          e: -75
      HCC:
        GABA_A:
          tau1: 0.72
          tau2: 4.7
          e: -75
      IS:
        GABA_A:
          tau1: 0.46
          tau2: 4.43
          e: -75
      NGFC:
        GABA_A:
          tau1:  4.5
          tau2: 13.8
          e: -75
        GABA_B:
          tau1:  86.8
          tau2: 428.1
          e: -90
      MOPP:
        GABA_A:
          tau1:  4.5
          tau2: 13.8
          e: -75
  IS:
      GC:
        AMPA:
          tau1: 0.3
          tau2: 6.2
          e: 0
      IS:
        GABA_A:
          tau1: 0.37
          tau2: 10.48
          e: -75
Connection Properties:
  GC:
    AAC:
      GABA_A: 
        weight: 1.0
        velocity: 250.0
    BC:
      GABA_A: 
        weight: 0.65
        velocity: 250.0
    HC:
      GABA_A:
        weight: 6.0
        velocity: 250.0
    HCC:
      GABA_A:
        weight: 3.0
        velocity: 250.0
    MC:
      AMPA:
        weight: 0.19
        velocity: 250.0
    NGFC:
      GABA_A:
        weight: 0.15
        velocity: 250.0
      GABA_B:
        weight: 0.1
        velocity: 250.0
    MOPP:
      GABA_A:
        weight: 0.15
        velocity: 250.0
    MPP:
      AMPA:
        weight: 1.6
        velocity: 250.0
    LPP:
      AMPA:
        weight: 1.8
        velocity: 250.0
  MC:
    AAC:
      GABA_A:
        weight: 3.0
        velocity: 250.0
    BC:
      GABA_A:
        weight: 1.5
        velocity: 250.0
    GC:
      AMPA:
        weight: 1.5
        velocity: 250.0
    HC:
      GABA_A:
        weight: 1.0
        velocity: 250.0
    HCC:
      GABA_A:
        weight: 0.6
        velocity: 250.0
    MC:
      AMPA:
        weight: 0.5
        velocity: 250.0
  HC:
    GC:
      AMPA:
        weight: 4.7
        velocity: 250.0
    HC:
      GABA_A:
        weight: 0.623
        velocity: 250.0
    MC:
      AMPA:
        weight: 2.2
        velocity: 250.0
    BC:
      GABA_A:
        weight: 5.2
        velocity: 250.0
    IS:
      GABA_A:
        weight: 0.5
        velocity: 250.0
  BC:
    GC:
      AMPA:
        weight: 4.7
        velocity: 250.0
    MC:
      AMPA:
        weight: 0.3
        velocity: 250.0
    HC:
      GABA_A:
        weight: 2.14
        velocity: 250.0
    IS:
      GABA_A:
        weight: 2.14
        velocity: 250.0
    BC:
      GABA_A:
        weight: 4.27
        velocity: 250.0
    HCC:
      GABA_A:
        weight: 0.664
        velocity: 250.0
    NGFC:
      GABA_A:
        weight: 0.183
        velocity: 250.0
      GABA_B:
        weight: 0.181
        velocity: 250.0
    MOPP:
      GABA_A:
        weight: 0.2
        velocity: 250.0
    LPP:
      AMPA:
        weight: 0.5
        velocity: 250.0
    MPP:
      AMPA:
        weight: 0.5
        velocity: 250.0
  AAC:
    GC:
      AMPA:
        weight: 4.7
        velocity: 250.0
    MC:
      AMPA:
        weight: 0.3
        velocity: 250.0
    HC:
      GABA_A:
        weight: 2.14
        velocity: 250.0
    IS:
      GABA_A:
        weight: 1.0
        velocity: 250.0
    NGFC:
      GABA_A:
        weight: 0.183
        velocity: 250.0
      GABA_B:
        weight: 0.181
        velocity: 250.0
    MOPP:
      GABA_A:
        weight: 0.2
        velocity: 250.0
  NGFC:
    HC:
      GABA_A:
        weight: 0.473
        velocity: 250.0
    NGFC:
      GABA_A:
        weight: 0.113
        velocity: 250.0
      GABA_B:
        weight: 0.169
        velocity: 250.0
    MOPP:
      GABA_A:
        weight: 0.113
        velocity: 250.0
    GC:
      AMPA:
        weight: 4.7
        velocity: 250.0
    LPP:
      AMPA:
        weight: 0.33
        velocity: 250.0
    MPP:
      AMPA:
        weight: 0.25
        velocity: 250.0
  MOPP:
    MC:
      AMPA:
        weight: 0.5
        velocity: 250.0
    MOPP:
      GABA_A:
        weight: 0.113
        velocity: 250.0
    HC:
      GABA_A:
        weight: 0.473
        velocity: 250.0
    HCC:
      GABA_A:
        weight: 0.325
        velocity: 250.0
    MPP:
      AMPA:
        weight: 1.0
        velocity: 250.0
  HCC:
    GC:
      AMPA:
        weight: 4.7
        velocity: 250.0
    MC:
      AMPA:
        weight: 2.3
        velocity: 250.0
    BC:
      GABA_A:
        weight: 3.82
        velocity: 250.0
    HCC:
      GABA_A:
        weight: 0.325
        velocity: 250.0
    NGFC:
      GABA_A:
        weight: 0.168
        velocity: 250.0
      GABA_B:
        weight: 0.215
        velocity: 250.0
    MOPP:
      GABA_A:
        weight: 0.168
        velocity: 250.0
    IS:
      GABA_A:
        weight: 0.5
        velocity: 250.0
  IS:
    GC:
      AMPA:
        weight: 0.5
        velocity: 250.0
    IS:
      GABA_A:
        weight: 1.0
        velocity: 250.0
Gap Junctions:
  Locations:
    BC:
      AAC: [apical, basal]
      BC: [apical, basal]
    AAC:
      AAC: [apical, basal]
    HCC:
      HCC: [apical, basal]
    HC: 
      HC: [apical, basal]
    IS: 
      HC: [apical, basal]
      IS: [apical, basal]
    NGFC:
      NGFC: [apical]
    MOPP:
      MOPP: [apical, basal]
  Connection Probabilities:
    AAC, BC, HC, IS, HCC, NGFC, MOPP:
      - [0.286, 0.0,   0.0,  0.0,  0.0,   0.0,   0.0]
      - [0.286, 0.286, 0.0,  0.0,  0.0,   0.0,   0.0]
      - [0.0,   0.0,   0.19, 0.0,  0.0,   0.0,   0.0]
      - [0.0,   0.0,   0.19, 0.19, 0.0,   0.0,   0.0]
      - [0.0,   0.0,   0.0,  0.0,  0.085, 0.0,   0.0]
      - [0.786, 0.786, 0.0,  0.0,  0.786, 0.786, 0.0]
      - [0.786, 0.786, 0.0,  0.0,  0.786, 0.786, 0.786]
  ## Distance-dependent connection weights,
  ## based on Fig. 1C from Otsuka 2013
  Connection Weights: { 0: 1.0, 25: 0.429, 75: 0.405, 125: 0.345, 175: 0.08 }
  Connection Parameters: [0.4201,-0.0019,150.7465,0.0255]
  Coupling Coefficients:
    AAC:
      AAC: 0.017
    BC:
      BC: 0.017
    HC:
      HC: 0.13
    HCC:
      HCC: 0.04
    NGFC:
      NGFC: 0.0385
    MOPP:
      MOPP: 0.0385
  ## Distance-dependent coupling coefficient weights,
  ## Based on Fig. 6B from Amitai 2002
  Coupling Weights: { 0: 1.0, 25: 0.5, 75: 0.375, 125: 0.1875, 175: 0.1875 }
  Coupling Parameters: [0.0002,-0.0658,7.3211]
  
