# full width in um [S-T, M-L]
Axon Width:
    GC:   [900., 900.]
    MPP:  [1500., 3000.]
    LPP:  [1500., 3000.]
    MC:   [4000., 4000.]
    NGFC: [2000., 2000.]
    AAC:  [1100., 1100.]
    BC:   [1700., 1000.]
    HCC:  [2600., 2600.]
    HC:   [3000., 3000.]
    IS:   [3000., 3000.]
    MOPP: [2000., 2000.]
Axon Offset:
    MC:   [1000., 0.]
    GC:   [0., 0.]
    MPP:  [0., 0.]
    LPP:  [0., 0.]
    NGFC: [0., 0.]
    AAC:  [0., 0.]
    BC:   [0., 0.]
    HCC:  [0., 0.]
    HC:   [0., 0.]
    IS:   [0., 0.]
    MOPP: [0., 0.]
Synapse Types:
    GC:
      MPP:  [excitatory]
      LPP:  [excitatory]
      MC:   [excitatory]
      NGFC: [inhibitory]
      AAC:  [inhibitory]
      BC:   [inhibitory]
      HCC:  [inhibitory]
      HC:   [inhibitory]
      MOPP: [inhibitory]
    MC:
      GC:   [excitatory]
      MC:   [excitatory]
      HC:   [inhibitory]
      BC:   [inhibitory]
      AAC:  [inhibitory]
      HCC:  [inhibitory]
    HC:
      GC:  [excitatory]
      MC:  [excitatory]
      HC:  [inhibitory]
      BC:  [inhibitory]
      IS:  [inhibitory]
    BC:
      GC:   [excitatory]
      MC:   [excitatory]
      HC:   [inhibitory]
      BC:   [inhibitory]
      HCC:  [inhibitory]
      NGFC: [inhibitory]
      MOPP: [inhibitory]
      IS:   [inhibitory]
      MPP:  [excitatory]
      LPP:  [excitatory]
    AAC:
      GC:   [excitatory]
      MC:   [excitatory]
      HC:   [inhibitory]
      NGFC: [inhibitory]
      MOPP: [inhibitory]
    HCC:
      GC:   [excitatory]
      MC:   [excitatory]
      BC:   [inhibitory]
      HCC:  [inhibitory]
      NGFC: [inhibitory]
      MOPP: [inhibitory]
      IS:   [inhibitory]
    NGFC:
      HC:   [inhibitory]
      NGFC: [inhibitory]
      MPP:  [excitatory]
      LPP:  [excitatory]
    MOPP:
      MC:   [excitatory]
      MOPP: [inhibitory]
      HC:   [inhibitory]
      HCC:  [inhibitory]
      MPP:  [excitatory]
    IS:
      GC:   [excitatory]
      IS:   [inhibitory]
Synapse Locations:
    GC:
      MPP:  [apical]
      LPP:  [apical]
      MC:   [apical]
      NGFC: [apical]
      AAC:  [axon]
      BC:   [soma, apical]
      MOPP: [apical]
      HCC:  [apical]
      HC:   [apical]
    MC:
      GC:   [apical]
      MC:   [apical]
      HC:   [apical]
      BC:   [soma]
      AAC:  [soma]
      HCC:  [apical]
    HC:
      GC:   [apical, basal]
      MC:   [apical, basal]
      HC:   [apical, basal]
      BC:   [apical, basal]
      IS:   [basal]
    BC:
      GC:   [apical, basal]
      MC:   [basal]
      HC:   [basal]
      BC:   [basal]
      HCC:  [basal]
      NGFC: [apical, basal]
      MOPP: [apical, basal]
      IS:   [basal]
      MPP:  [apical]
      LPP:  [apical]
    AAC:
      GC: [apical, basal]
      MC: [basal]
      HC: [basal]
      NGFC: [apical, basal]
      MOPP: [apical, basal]
      IS:   [basal]
    HCC:
      GC: [apical, basal]
      MC: [basal]
      BC: [basal]
      HCC: [basal]
      NGFC: [apical, basal]
      MOPP: [apical, basal]
      IS:   [basal]
    NGFC:
      HC: [apical]
      NGFC: [apical]
      MOPP: [apical]
      MPP:  [apical]
      LPP:  [apical]
    MOPP:
      MC:   [apical]
      MPP:  [apical]
      HC:   [apical]
      HCC:  [apical]
      MOPP: [apical]
      NGFC: [apical]
    IS:
      GC:   [apical]
      IS:   [apical]
Synapse Layers:
    GC:
      MPP:  [MML]
      LPP:  [OML]
      MC:   [IML]
      NGFC: [MML, OML]
      AAC:  [GCL]
      BC:   [GCL, IML]
      MOPP: [IML, MML]
      HCC:  [IML]
      HC:   [MML, OML]
    MC:
      GC:  [Hilus]
      MC:  [Hilus]
      HC:  [IML]
      BC:  [Hilus]
      AAC: [Hilus]
      HCC: [IML]
    HC:
      GC:  [Hilus]
      MC:  [GCL]
      HC:  [Hilus]
      BC:  [GCL]
      IS:  [Hilus]
    BC:
      GC:   [Hilus, GCL]
      MC:   [GCL]
      HC:   [MML]
      BC:   [GCL]
      HCC:  [GCL]
      NGFC: [MML, OML]
      MOPP: [IML, MML]
      IS:   [Hilus]
      MPP:  [MML]
      LPP:  [OML]
    AAC:
      GC:   [Hilus, GCL]
      MC:   [GCL]
      HC:   [MML]
      NGFC: [MML, OML]
      MOPP: [IML, MML]
    HCC:
      GC:   [Hilus]
      MC:   [GCL]
      BC:   [GCL]
      HCC:  [GCL]
      NGFC: [OML]
      MOPP: [MML]
      IS:   [Hilus]
    NGFC:
      HC:   [MML, OML]
      NGFC: [OML]
      MPP:  [MML]
      LPP:  [OML]
    MOPP:
      MC:   [IML]
      MOPP: [MML]
      HC:   [IML]
      HCC:  [IML]
      MPP:  [MML]
    IS:
      GC:   [Hilus]
      IS:   [Hilus]
Synapse Proportions:      
  GC:
    MPP:  [1.]
    LPP:  [1.]
    MC:   [1.]
    NGFC: [0.15, 0.15]
    AAC:  [1.]
    BC:   [1., 0.4]
    MOPP: [0.3, 0.3]
    HCC:  [0.6]
    HC:   [0.55, 0.55]
  MC:
    GC:  [0.05]
    MC:  [0.95]
    BC:  [0.33]
    AAC: [0.77]
    HC:  [0.5]
    HCC: [0.5]
  HC:
    MC:  [1.0]
    BC:  [1.0]
    GC:  [1.0]
    HC:  [0.75]
    IS:  [0.25]
  BC:
    GC:   [0.5, 0.5]
    MC:   [1.0]
    MPP:  [1.0]
    LPP:  [1.0]
    BC:   [0.18]
    HCC:  [0.82]
    HC:   [0.90]
    NGFC: [0.05, 1.0]
    MOPP: [1.0, 0.05]
    IS:   [1.0]
  AAC:
    GC:   [0.5, 0.5]
    MC:   [1.0]
    HC:   [0.9]
    NGFC: [0.05, 1.0]
    MOPP: [1.0, 0.05]
  HCC:
    GC:   [1.0]
    MC:   [1.0]
    BC:   [0.2]
    HCC:  [0.8]
    NGFC: [1.0]
    MOPP: [1.0]
    IS:   [1.0]
  NGFC:
    HC:   [1.0, 0.66]
    NGFC: [0.33]
    MPP:  [1.0]
    LPP:  [1.0]
  MOPP:
    MC:   [1.0]
    MOPP: [1.0]
    HC:   [0.5]
    HCC:  [0.5]
    MPP:  [1.0]
  IS:
    GC:   [1.0]
    IS:   [1.0]
Synapse Kinetics:
  GC:
      GC:
        AMPA:
          t_rise: 1.5
          t_decay: 5.5
          e_rev: 0
      MC:
        AMPA:
          t_rise: 1.5
          t_decay: 5.5
          e_rev: 0
      MPP:
        AMPA:
          t_rise: 0.5
          t_decay: 3.0
          e_rev: 0
      LPP:
        AMPA:
          t_rise: 0.5
          t_decay: 3.0
          e_rev: 0
      HC:
        GABA_A:
          t_rise: 0.005
          t_decay: 0.001
          e_rev: -75
      BC:
        GABA_A:
          t_rise: 0.25
          t_decay: 2.5
          e_rev: -75
      AAC:
        GABA_A:
          t_rise: 0.3
          t_decay: 2.9
          e_rev: -75
      HCC:
        GABA_A:
          t_rise: 0.04
          t_decay: 1.1
          e_rev: -75
      NGFC:
        GABA_A:
          t_rise:  0.1
          t_decay: 10.0
          e_rev:   -75
        GABA_B:
          t_rise:  86.8
          t_decay: 428.1
          e_rev:   -75
      MOPP:
        GABA_A:
          t_rise:  0.1
          t_decay: 10.0
          e_rev:   -75
        GABA_B:
          t_rise:  86.8
          t_decay: 428.1
          e_rev:   -75
  MC:
      GC:
        AMPA:
          t_rise: 0.5
          t_decay: 6.2
          e_rev: 0
      MC:
        AMPA:
          t_rise: 0.45
          t_decay: 2.2
          e_rev: 0
      HC:
        GABA_A:
          t_rise: 0.5
          t_decay: 6.0
          e_rev: -75
      BC:
        GABA_A:
          t_rise: 0.3
          t_decay: 3.3
          e_rev: -75
      AAC:
        GABA_A:
          t_rise: 0.3
          t_decay: 3.3
          e_rev: -75
      HCC:
        GABA_A:
          t_rise: 0.6
          t_decay: 4.7
          e_rev: -75
  HC:
      GC:
        AMPA:
          t_rise: 0.3
          t_decay: 6.2
          e_rev: 0
      MC:
        AMPA:
          t_rise: 0.9
          t_decay: 3.6
          e_rev: 0
      HC:
        GABA_A:
          t_rise: 0.37
          t_decay: 10.48
          e_rev: -75
      BC:
        GABA_A:
          t_rise: 0.265
          t_decay: 2.88
          e_rev: -75
      IS:
        GABA_A:
          t_rise: 0.37
          t_decay: 10.48
          e_rev: -75
  BC:
      GC:
        AMPA:
          t_rise: 0.3
          t_decay: 6.2
          e_rev: 0
      MC:
        AMPA:
          t_rise: 0.9
          t_decay: 3.6
          e_rev: 0
      MPP:
        AMPA:
          t_rise:  0.5
          t_decay: 3.0
          e_rev:     0
      LPP:
        AMPA:
          t_rise:  0.5
          t_decay: 3.0
          e_rev:     0
      HC:
        GABA_A:
          t_rise: 0.46
          t_decay: 4.43
          e_rev: -75
      BC:
        GABA_A:
          t_rise: 0.22
          t_decay: 3.35
          e_rev: -75
      HCC:
        GABA_A:
          t_rise: 0.6
          t_decay: 4.78
          e_rev: -75
      NGFC:
        GABA_A:
          t_rise:   4.2
          t_decay: 14.0
          e_rev:    -75
        GABA_B:
          t_rise:  86.8
          t_decay: 428.1
          e_rev:   -75
      MOPP:
        GABA_A:
          t_rise:   4.2
          t_decay: 14.0
          e_rev:    -75
        GABA_B:
          t_rise:  86.8
          t_decay: 428.1
          e_rev:   -75
      IS:
        GABA_A:
          t_rise: 0.46
          t_decay: 4.43
          e_rev: -75
  AAC:
      GC:
        AMPA:
          t_rise: 0.3
          t_decay: 6.2
          e_rev: 0
      MC:
        AMPA:
          t_rise: 0.9
          t_decay: 3.6
          e_rev: 0
      HC:
        GABA_A:
          t_rise: 0.46
          t_decay: 4.43
          e_rev: -75
      NGFC:
        GABA_A:
          t_rise:  4.2
          t_decay: 14.0
          e_rev: -75
        GABA_B:
          t_rise:  86.8
          t_decay: 428.1
          e_rev: -75
      MOPP:
        GABA_A:
          t_rise:  4.2
          t_decay: 14.0
          e_rev: -75
        GABA_B:
          t_rise:  86.8
          t_decay: 428.1
          e_rev: -75
      IS:
        GABA_A:
          t_rise: 0.46
          t_decay: 4.43
          e_rev: -75
  HCC:
      GC:
        AMPA:
          t_rise: 0.3
          t_decay: 6.2
          e_rev: 0
      MC:
        AMPA:
          t_rise: 0.9
          t_decay: 3.6
          e_rev: 0
      BC:
        GABA_A:
          t_rise: 0.28
          t_decay: 3.45
          e_rev: -75
      HCC:
        GABA_A:
          t_rise: 0.72
          t_decay: 4.7
          e_rev: -75
      IS:
        GABA_A:
          t_rise: 0.46
          t_decay: 4.43
          e_rev: -75
      MOPP:
        GABA_A:
          t_rise:  4.2
          t_decay: 16.2
          e_rev: -75
        GABA_B:
          t_rise: 86.8
          t_decay: 428.1
          e_rev: -75
      NGFC:
        GABA_A:
          t_rise:  4.2
          t_decay: 16.2
          e_rev: -75
        GABA_B:
          t_rise: 86.8
          t_decay: 428.1
          e_rev: -75
  NGFC:
      MPP:
        AMPA:
          t_rise: 0.5
          t_decay: 3.0
          e_rev: 0
      LPP:
        AMPA:
          t_rise: 0.5
          t_decay: 3.0
          e_rev: 0
      BC:
        GABA_A:
          t_rise: 0.72
          t_decay: 10.0
          e_rev: -75
      HC:
        GABA_A:
          t_rise: 0.72
          t_decay: 4.7
          e_rev: -75
      IS:
        GABA_A:
          t_rise: 0.46
          t_decay: 4.43
          e_rev: -75
      NGFC:
        GABA_A:
          t_rise:  4.2
          t_decay: 14.0
          e_rev: -75
        GABA_B:
          t_rise:  86.8
          t_decay: 428.1
          e_rev: -75
  MOPP:
      MPP:
        AMPA:
          t_rise: 0.5
          t_decay: 3.0
          e_rev: 0
      MC:
        AMPA:
          t_rise: 0.9
          t_decay: 3.6
          e_rev: 0
      BC:
        GABA_A:
          t_rise: 0.72
          t_decay: 10.0
          e_rev: -75
      HC:
        GABA_A:
          t_rise: 0.72
          t_decay: 4.7
          e_rev: -75
      HCC:
        GABA_A:
          t_rise: 0.72
          t_decay: 4.7
          e_rev: -75
      IS:
        GABA_A:
          t_rise: 0.46
          t_decay: 4.43
          e_rev: -75
      NGFC:
        GABA_A:
          t_rise:  4.5
          t_decay: 13.8
          e_rev: -75
        GABA_B:
          t_rise:  86.8
          t_decay: 428.1
          e_rev: -75
      MOPP:
        GABA_A:
          t_rise:  4.5
          t_decay: 13.8
          e_rev: -75
        GABA_B:
          t_rise:  86.8
          t_decay: 428.1
          e_rev: -75
  IS:
      GC:
        AMPA:
          t_rise: 0.3
          t_decay: 6.2
          e_rev: 0
      IS:
        GABA_A:
          t_rise: 0.37
          t_decay: 10.48
          e_rev: -75
Connection Properties:
  GC:
    AAC:
      GABA_A: 
        weight: 1.0
        velocity: 250.0
    BC:
      GABA_A: 
        weight: 0.65
        velocity: 250.0
    HC:
      GABA_A:
        weight: 6.0
        velocity: 250.0
    HCC:
      GABA_A:
        weight: 0.2
        velocity: 250.0
    MC:
      AMPA:
        weight: 0.3
        velocity: 250.0
    NGFC:
      GABA_A:
        weight: 0.2
        velocity: 250.0
      GABA_B:
        weight: 0.1
        velocity: 250.0
    MOPP:
      GABA_A:
        weight: 0.2
        velocity: 250.0
      GABA_B:
        weight: 0.1
        velocity: 250.0
    MPP:
      AMPA:
        weight:
          from file: ./dat/MPPsynweights.dat
        velocity: 250.0
    LPP:
      AMPA:
        weight:
          from file: ./dat/LPPsynweights.dat
        velocity: 250.0
  MC:
    AAC:
      GABA_A:
        weight: 3.0
        velocity: 250.0
    BC:
      GABA_A:
        weight: 1.5
        velocity: 250.0
    GC:
      AMPA:
        weight: 0.7
        velocity: 250.0
    HC:
      GABA_A:
        weight: 1.0
        velocity: 250.0
    HCC:
      GABA_A:
      weight: 0.6
      velocity: 250.0
    MC:
      AMPA:
        weight: 0.5
        velocity: 250.0
  HC:
    GC:
      AMPA:
        weight: 0.5
        velocity: 250.0
    HC:
      GABA_A:
        weight: 0.623
        velocity: 250.0
    MC:
      AMPA:
        weight: 0.2
        velocity: 250.0
    BC:
      GABA_A:
        weight: 5.2
        velocity: 250.0
    IS:
      GABA_A:
        weight: 1.0
        velocity: 250.0
  BC:
    GC:
      AMPA:
        weight: 4.7
        velocity: 250.0
    MC:
      AMPA:
        weight: 0.3
        velocity: 250.0
    HC:
      GABA_A:
        weight: 2.14
        velocity: 250.0
    IS:
      GABA_A:
        weight: 2.14
        velocity: 250.0
    BC:
      GABA_A:
        weight: 4.27
        velocity: 250.0
    HCC:
      GABA_A:
        weight: 0.664
        velocity: 250.0
    NGFC:
      GABA_A:
        weight: 0.183
        velocity: 250.0
      GABA_B:
        weight: 0.181
        velocity: 250.0
    MOPP:
      GABA_A:
        weight: 0.2
        velocity: 250.0
      GABA_B:
        weight: 0.1
        velocity: 250.0
    LPP:
      AMPA:
        weight: 2.5
        velocity: 250.0
    MPP:
      AMPA:
        weight: 2.5
        velocity: 250.0
  AAC:
    GC:
      AMPA:
        weight: 4.7
        velocity: 250.0
    MC:
      AMPA:
        weight: 0.3
        velocity: 250.0
    HC:
      GABA_A:
        weight: 2.14
        velocity: 250.0
    IS:
      GABA_A:
        weight: 2.14
        velocity: 250.0
    NGFC:
      GABA_A:
        weight: 0.183
        velocity: 250.0
      GABA_B:
        weight: 0.181
        velocity: 250.0
    MOPP:
      GABA_A:
        weight: 0.2
        velocity: 250.0
      GABA_B:
        weight: 0.1
        velocity: 250.0
  NGFC:
    HC:
      GABA_A:
        weight: 0.473
        velocity: 250.0
    NGFC:
      GABA_A:
        weight: 0.113
        velocity: 250.0
      GABA_B:
        weight: 0.169
        velocity: 250.0
    MOPP:
      GABA_A:
        weight: 0.113
        velocity: 250.0
      GABA_B:
        weight: 0.169
        velocity: 250.0
    GC:
      AMPA:
        weight: 4.7
        velocity: 250.0
    LPP:
      AMPA:
        weight: 2.0
        velocity: 250.0
    MPP:
      AMPA:
        weight: 2.0
        velocity: 250.0
  MOPP:
    MC:
      AMPA:
        weight: 0.5
        velocity: 250.0
    MOPP:
      GABA_A:
        weight: 0.113
        velocity: 250.0
      GABA_B:
        weight: 0.169
        velocity: 250.0
    HC:
      GABA_A:
        weight: 0.473
        velocity: 250.0
    HCC:
      GABA_A:
        weight: 0.325
        velocity: 250.0
    MPP:
      AMPA:
        weight: 2.0
        velocity: 250.0
  HCC:
    GC:
      AMPA:
        weight: 4.7
        velocity: 250.0
    MC:
      AMPA:
        weight: 0.3
        velocity: 250.0
    BC:
      GABA_A:
        weight: 3.82
        velocity: 250.0
    HCC:
      GABA_A:
        weight: 0.325
        velocity: 250.0
    NGFC:
      GABA_A:
        weight: 0.168
        velocity: 250.0
      GABA_B:
        weight: 0.215
        velocity: 250.0
    MOPP:
      GABA_A:
        weight: 0.168
        velocity: 250.0
      GABA_B:
        weight: 0.215
        velocity: 250.0
    IS:
      GABA_A:
        weight: 2.14
        velocity: 250.0
  IS:
    GC:
      AMPA:
        weight: 0.3
        velocity: 250.0
    IS:
      GABA_A:
        weight: 1.0
        velocity: 250.0
