- namespace: ['LTP Structured Weights A', 'LTD Structured Weights A', 'Log-Normal Weights']
  expr: ltp + ltd + lnw
  parameter: [ltp, ltd, lnw]
- namespace: ['NS Structured Weights A', 'Normal Weights']
  expr: nsw + nw
  parameter: [nsw, nw]
