## GC synapse density configuration
apical:
  excitatory: # Excitatory https://www.ncbi.nlm.nih.gov/pubmed/2760687
    IML: # layer
      mean: 3.36
      variance: 0.35
    MML: # layer
      mean: 2.28
      variance: 0.33
    OML: # layer
      mean: 2.02
      variance: 0.28
  inhibitory: # Inhibitory https://www.ncbi.nlm.nih.gov/pubmed/20034063
    IML: # layer
      mean: 0.7
      variance: 0.01
    OML: # layer
      mean: 0.7
      variance: 0.01
    MML: # layer
      mean: 0.7
      variance: 0.01
soma:
  inhibitory: # Inhibitory https://www.ncbi.nlm.nih.gov/pubmed/20034063
    default: # layer
      mean: 10.22
      variance: 0.32
ais:
  inhibitory: # Inhibitory https://www.ncbi.nlm.nih.gov/pubmed/20034063
    default: # layer
      mean: 1.0
      variance: 0.01
