- namespace: ['LTP Structured Weights A', 'LTD Structured Weights A', 'Log-Normal Weights']
  expr: a*ltp + b*(ltd + lnw)
  parameter: [ltp, ltd, lnw]
  const:
    a: 6.0
    b: 1.0
- namespace: ['Normal Weights']
  expr: c*nw
  parameter: [nw]
  const:
    c: 1.0

    
