## Parametric surface extents and other properties

Parametric Surface:
  Origin:
    U: median
    V: median
    L: max
  Minimum Extent:
    Hilus: [0.03142, -0.7225, -3.95]
    GCL:   [0.03142, -0.7225, -1.95]
    IML:   [-0.0502, -0.7225, 0.]
    MML:   [-0.0502, -0.7225, 1.]
    OML:   [-0.0502, -0.7225, 2.]
  Maximum Extent:
    Hilus: [3.0787, 4.4767, -1.95]
    GCL:   [3.0787, 4.4767, 0.]
    IML:   [3.1730, 4.4767, 1.]
    MML:   [3.1730, 4.4767, 2.]
    OML:   [3.1730, 4.4767, 3.1]
  Rotation: [-35.0, 0., 0.]
Cell Layers:
  Minimum Extent:
    GC:  [0.03142, -0.7225, -1.95]
    MPP: [-0.0502, -0.7225, 1.]
    LPP: [-0.0502, -0.7225, 2.]
    MC:  [0.03142, -0.7225, -3.95]
    NGFC: [-0.0502, -0.7225, 2.]
    AAC: [0.03142, -0.7225, -2.95]
    BC:  [0.03142, -0.7225, -1.95]
    MOPP: [-0.0502, -0.7225, 1.]
    HCC: [0.03142, -0.7225, -1.5]
    HC: [0.03142, -0.7225, -3.95]
    IS: [0.03142, -0.7225, -3.95]
  Maximum Extent:
    GC: [3.0787, 4.4767, 0.]
    MPP: [3.1730, 4.4767, 2.]
    LPP: [3.1730, 4.4767, 3.1]
    MC: [3.0787, 4.4767, -1.95]
    NGFC: [3.1730, 4.4767, 3.0]
    AAC: [3.0787, 4.4767, 0.0]
    BC: [3.0787, 4.4767, 1.0]
    MOPP: [3.1730, 4.4767, 2.1]
    HCC: [3.0787, 4.4767, 1.0]
    HC: [3.0787, 4.4767, -1.95]
    IS: [3.0787, 4.4767, -1.95]
Cell Layer Counts:
  GC:
    Hilus: 0
    GCL: 1000000
    IML: 0
    MML: 0
    OML: 0
  MC:
    Hilus: 30000
    GCL: 0
    IML: 0
    MML: 0
    OML: 0
  HC:
    Hilus: 9000
    GCL: 0
    IML: 0
    MML: 0
    OML: 0
  BC:
    Hilus: 3800
    GCL: 0
    IML: 0
    MML: 0
    OML: 0
  AAC:
    Hilus: 450
    GCL: 0
    IML: 0
    MML: 0
    OML: 0
  HCC:
    Hilus: 1400
    GCL: 0
    IML: 0
    MML: 0
    OML: 0
  NGFC:
    Hilus: 0
    GCL: 0
    IML: 0
    MML: 2500
    OML: 2500
  MOPP:
    Hilus: 0
    GCL: 0
    IML: 2000
    MML: 1000
    OML: 1000
  IS:
    Hilus: 3000
    GCL: 0
    IML: 0
    MML: 0
    OML: 0
  MPP:
    Hilus: 0
    GCL: 0
    IML: 0
    MML: 38000
    OML: 0
  LPP:
    Hilus: 0
    GCL: 0
    IML: 0
    MML: 0
    OML: 34000
