## Parametric surface extents and other properties

Parametric Surface:
  Minimum Extent:
    Hilus: [0.03142, -0.7225, -3.95]
    GCL:   [0.03142, -0.7225, -1.95]
    IML:   [-0.0502, -0.7225, 0.]
    MML:   [-0.0502, -0.7225, 1.]
    OML:   [-0.0502, -0.7225, 2.]
  Maximum Extent:
    Hilus: [3.0787, 4.4767, -1.95]
    GCL:   [3.0787, 4.4767, 0.]
    IML:   [3.1730, 4.4767, 1.]
    MML:   [3.1730, 4.4767, 2.]
    OML:   [3.1730, 4.4767, 3.1]
  Rotation: [-35.0, 0., -0.]
Cell Layers:
  Minimum Extent:
    GC: [0.03142, -0.7225, -1.95]
    MPP: [-0.0502, -0.7225, 1.]
    LPP: [-0.0502, -0.7225, 2.]
    MC: [0.03142, -0.7225, -3.95]
    NGFC: [-0.0502, -0.7225, 1.]
    AAC: [-0.0502, -0.7225, -3.95]
    BC: [-0.0502, -0.7225, -3.95]
    MOPP: [-0.0502, -0.7225, 0.]
    HCC: [0.03142, -0.7225, -3.95]
    HC: [0.03142, -0.7225, -3.95]
    IS: [0.03142, -0.7225, -3.95]
  Maximum Extent:
    GC: [3.0787, 4.4767, 0.]
    MPP: [3.1730, 4.4767, 2.]
    LPP: [3.1730, 4.4767, 3.1]
    MC: [3.0787, 4.4767, -1.95]
    NGFC: [3.1730, 4.4767, 3.1]
    AAC: [3.1730, 4.4767, 1.]
    BC: [3.1730, 4.4767, 1.]
    MOPP: [3.1730, 4.4767, 3.1]
    HCC: [3.0787, 4.4767, 0.]
    HC: [3.0787, 4.4767, -1.95]
    IS: [3.0787, 4.4767, -1.95]
Cell Layer Counts:
  GC:
    Hilus: 0
    GCL: 1000000
    IML: 0
    MML: 0
    OML: 0
  MC:
    Hilus: 30000
    GCL: 0
    IML: 0
    MML: 0
    OML: 0
  HC:
    Hilus: 9000
    GCL: 0
    IML: 0
    MML: 0
    OML: 0
  BC:
    Hilus: 1700
    GCL: 1700
    IML: 400
    MML: 0
    OML: 0
  AAC:
    Hilus: 200
    GCL: 200
    IML: 50
    MML: 0
    OML: 0
  HCC:
    Hilus: 1150
    GCL: 250
    IML: 0
    MML: 0
    OML: 0
  NGFC:
    Hilus: 0
    GCL: 0
    IML: 0
    MML: 2500
    OML: 2500
  MOPP:
    Hilus: 0
    GCL: 0
    IML: 2000
    MML: 1000
    OML: 1000
  IS:
    Hilus: 3000
    GCL: 0
    IML: 0
    MML: 0
    OML: 0
  MPP:
    Hilus: 0
    GCL: 0
    IML: 0
    MML: 38000
    OML: 0
  LPP:
    Hilus: 0
    GCL: 0
    IML: 0
    MML: 0
    OML: 34000
Cell Grid Spacing:
  GC:
    H: 20.
    V: 10.
  MC:
    H: 20.
    V: 20.
  HC:
    H: 50.
    V: 50.
  BC:
    H: 100.
    V: 100.
  AAC:
    H: 100.
    V: 100.
  HCC:
    H: 100.
    V: 100.
  NGFC:
    H: 50.
    V: 50.
  IS:
    H: 50.
    V: 50.
  MOPP:
    H: 80.
    V: 80.
  MPP:
    H: 20.
    V: 20.
  LPP:
    H: 20.
    V: 20.
