## HC synapse density configuration
## This configuration uses scaled up density values to account for short dendritic length in the model.
apical:
  excitatory:
    default:
      mean: 2.83
      variance: 0.1
  inhibitory:
    default:
      mean: 0.43
      variance: 0.1
soma:
  inhibitory:
    default:
      mean: 0.1
      variance: 0.1
  excitatory:
    default:
      mean: 0.8
      variance: 0.1
