## About 27% of mEC cells were reported to be grid or border cells; 68% non-grid spatial; 4% non-spatial;
## Reference:
## https://www.ncbi.nlm.nih.gov/pubmed/28343867
## Diehl GW, Hon OJ, Leutgeb S, Leutgeb JK.
## Grid and Nongrid Cells in Medial Entorhinal Cortex Represent
## Spatial Location and Environmental Features with Complementary
## Coding Schemes. 
## Neuron Volume 94, Issue 1, 5 April 2017, pp 83-92.
Feature Distribution:
  MPP:
    grid: 0.3
    place: 0.7
  LPP:
    place: 1.0
  PYR:
    place: 1.0

Peak Rate:
  MPP:
    grid: 20.0
    place: 20.0
  LPP:
    place: 20.0
  PYR:
    place: 20.0
    
Field Probabilities:
  PYR:
    0: 0.38
    1: 0.21
    2: 0.17
    3: 0.13
    4: 0.08
    5: 0.02
    6: 0.01

Field Width:
  x1: 35.0
  x2: 0.32
  min: 40.0

Spatial Resolution: 5.0
Number Modules: 10
  
Arena:
  A: 
    Perforant Path:
      probability inactive:
        - 0.006
        - 0.051
        - 0.040
        - 0.001
        - 0.311
        - 0.514
        - 0.636
        - 0.717
        - 0.768
        - 0.804
        
      probability remaining:
        - 0.94
        - 0.938
        - 0.582
        - 0.026
        - 0.0007
        - 0.005
        - 0.0001
        - 0.0026
        - 0.0058
        - 0.012

    Domain:
      vertices: [[-100, -100], [-100, 100], [100, 100], [100, -100]]
      simplices: [[0,1], [1,2], [2,3], [3,0]]
    
    Trajectory:
      name: Diag
      path: [[[-100, -100], [100, 100]]]
      run velocity: 30. # cm/s
        
    Trajectory:
      name: DiagU5 ## upper diagonal offset by 5 cm on Y axis
      path: [[[-100, -95], [95, 100]]]
      run velocity: 30. # cm/s
        
    Trajectory:
      name: DiagL5 ## lower diagonal offset by 5 cm on X axis
      path: [[[-95, -100], [100, 95]]]
      run velocity: 30. # cm/s
