Number Modules: 10
Spatial Resolution: 5.0  # cm
Temporal Resolution: 1.0  # ms
Equilibration Duration: 250. # ms

# Variances expressed as floor widths of a normal distribution
Grid Orientation Variance: 15.  # degrees
Grid Spacing Variance: 0.  # proportion of module width
Modular Place Field Width Variance: 0.  # proportion of module width
Non-modular Place Field Width Variance: 0.1  # proportion of expected width

## About 27% of mEC cells were reported to be grid or border cells; 68% non-grid spatial; 4% non-spatial;
## Reference:
## https://www.ncbi.nlm.nih.gov/pubmed/28343867
## Diehl GW, Hon OJ, Leutgeb S, Leutgeb JK.
## Grid and Nongrid Cells in Medial Entorhinal Cortex Represent
## Spatial Location and Environmental Features with Complementary
## Coding Schemes.
## Neuron Volume 94, Issue 1, 5 April 2017, pp 83-92.
Selectivity Type Probabilities:
  MPP:
    grid: 0.3
    place: 0.7
  LPP:
    place: 1.0
  GC:
    place: 1.0
  MC:
    place: 1.0
  ConMC:
    place: 1.0
  CA3c:
    place: 1.0

Non-modular Place Selectivity Populations:
  - GC
  - MC
  - ConMC
  - CA3c

Peak Rate:
  MPP:
    grid: 20.0
    place: 20.0
  LPP:
    place: 20.0
  GC:
    place: 20.0
  MC:
    place: 20.0
  ConMC:
    place: 20.0
  CA3c:
    place: 20.0

Place Fraction Active:
  MPP: 0.1668
  LPP: 0.1668
  GC: 0.0338
  MC: 0.1668
  ConMC: 0.1668
  CA3c: 0.1171

Num Place Field Probabilities:
  MPP:
    0: 2.129630E-01
    1: 2.092593E-01
    2: 2.833333E-01
    3: 1.777778E-01
    4: 7.962963E-02
    5: 3.148148E-02
    6: 5.555556E-03
  LPP:
    0: 2.129630E-01
    1: 2.092593E-01
    2: 2.833333E-01
    3: 1.777778E-01
    4: 7.962963E-02
    5: 3.148148E-02
    6: 5.555556E-03
  GC:
    0: 7.677725E-01
    1: 1.469194E-01
    2: 5.687204E-02
    3: 2.369668E-02
    4: 4.739336E-03
  MC:
    0: 2.129630E-01
    1: 2.092593E-01
    2: 2.833333E-01
    3: 1.777778E-01
    4: 7.962963E-02
    5: 3.148148E-02
    6: 5.555556E-03
  ConMC:
    0: 2.129630E-01
    1: 2.092593E-01
    2: 2.833333E-01
    3: 1.777778E-01
    4: 7.962963E-02
    5: 3.148148E-02
    6: 5.555556E-03
  CA3c:
    0: 3.887734E-01
    1: 2.453222E-01
    2: 1.683992E-01
    3: 1.205821E-01
    4: 6.237006E-02
    5: 1.455301E-02

Grid Spacing Parameters:
  slope: 35.0
  tau: 0.32
  offset: 40.0

Selectivity Module Parameters:
  width: 0.75
  displacement: 0.

Field Width Concentration Factor:
  grid: 0.7
  place: 0.871

Arena:
  A:
    Domain:
      vertices: [[-100, -100], [-100, 100], [100, 100], [100, -100]]
      simplices: [[0,1], [1,2], [2,3], [3,0]]

    Trajectory:
      Diag:
        path: [[-100, -100], [100, 100]]
        run velocity: 30.  # cm/s

      HDiag:
        path: [[30, 30], [100, 100]]
        run velocity: 30. # cm/s

      ## upper diagonal offset by 5 cm on Y axis
      DiagU5:
        path: [[-100, -95], [95, 100]]
        run velocity: 30.  # cm/s

      ## lower diagonal offset by 5 cm on X axis
      DiagL5:
        path: [[-95, -100], [100, 95]]
        run velocity: 30.  # cm/s
