- namespace: ['LTP Structured Weights A', 'LTD Structured Weights A', 'Log-Normal Weights']
  expr: a*ltp + (b*ltd + lnw)*c
  parameter: [ltp, ltd, lnw]
  const:
   a: 12.825
   b: 1.0
   c: 0.6
- namespace: ['Normal Weights']
  expr: a*nw
  parameter: [nw]
  const:
   a: 1.0
