- namespace: ['LTP Structured Weights A', 'LTD Structured Weights A', 'Log-Normal Weights']
  expr: 4*(ltp + ltd + lnw)
  parameter: [ltp, ltd, lnw]
- namespace: ['Non-Structured Weights A', 'Normal Weights']
  expr: nsw + nw
  parameter: [nsw, nw]
