- namespace: ['LTP Structured Weights A', 'LTD Structured Weights A', 'Log-Normal Weights']
  expr: a*ltp + (ltd + lnw)
  parameter: [ltp, ltd, lnw]
  const:
   a: 9.36
- namespace: ['Normal Weights']
  expr: c*nw
  parameter: [nw]
  const:
    c: 0.15
