- namespace: ['LTP Structured Weights A', 'LTD Structured Weights A', 'Log-Normal Weights']
  expr: a*ltp + (ltd + lnw)
  parameter: [ltp, ltd, lnw]
  const:
   a: 2.84
- namespace: ['Normal Weights']
  expr: a*nw
  parameter: [nw]
  const:
   a: 8.0
