Network Clamp:  !include Network_Clamp.yaml
Model Name: Single_GC_Aradi_Sat_SLN_IN_PR_proximal_pf
Dataset Name: Slice
Definitions: !include Definitions.yaml
Global Parameters: !include Global.yaml
Geometry: !include Geometry.yaml
Random Seeds: !include Random.yaml
Cell Data: dentatenet_Full_Scale_GC_Aradi_Sat_SLN_proximal_pf_20210916.h5
Connection Data: dentatenet_Full_Scale_GC_Aradi_Sat_SLN_proximal_pf_20210916.h5
#Gap Junction Data: DG_gapjunctions_20191112.h5
Connection Generator: !include Full_Scale_Connections_GC_Aradi_IN_PR.yaml
Recording: !include Recording.yaml
Stimulus: !include Input_Configuration.yaml
Analysis: !include Analysis_Configuration.yaml
## Cell types for dentate gyrus model
Cell Types:
  GC:
    template: DGC
    template file: DGC_Template_Aradi.hoc
    mechanism file: 20210420_DG_GC_null_mech.yaml
    synapses:
      correct_for_spines: True
      weights: !include GC_SLN_weights.yaml
      density: !include GC_synapse_density.yaml
  MC:
    template: PR_nrn
    mechanism file: DG_MC_PR_config.yaml
    synapses:
      weights: !include MC_SLN_weights.yaml
      density: !include MC_synapse_density.yaml
  HC:
    template: PR_nrn
    mechanism file: DG_HIPP_PR_config.yaml
    synapses:
      density: !include HC_synapse_density.yaml
  BC:
    template: PR_nrn
    mechanism file: DG_BC_PR_config.yaml
    synapses:
      density: !include BC_synapse_density.yaml
  AAC:
    template: PR_nrn
    mechanism file: DG_AAC_PR_config.yaml
    synapses:
      density: !include AAC_synapse_density.yaml
  HCC:
    template: PR_nrn
    mechanism file: DG_HICAP_PR_config.yaml
    synapses:
      density: !include HCC_synapse_density.yaml
  NGFC:
    template: PR_nrn
    mechanism file: DG_NGFC_PR_config.yaml
    synapses:
      density: !include NGFC_synapse_density.yaml
  MOPP:
    template: PR_nrn
    mechanism file: DG_MOPP_PR_config.yaml
    synapses:
      density: !include NGFC_synapse_density.yaml
  IS:
    template: PR_nrn
    mechanism file: DG_IS_PR_config.yaml
    synapses:
      density: !include IS_synapse_density.yaml
  MPP:
    template: VecStim
    spike train:
      namespace: Input Spikes
      attribute: Spike Train
  LPP:
    template: VecStim
    spike train:
      namespace: Input Spikes
      attribute: Spike Train
  CA3c:
    template: VecStim
    spike train:
      namespace: Input Spikes
      attribute: Spike Train
  ConMC:
    template: VecStim
    spike train:
      namespace: Input Spikes
      attribute: Spike Train
