Template Parameter Rules:
  StimCell:
    - rate
Weight Generator:
  MC:
    GC:
      class: Log-Normal
      name: AMPA
      params:
        mu: 0.
        sigma: 1.0
        clip: [0.0, 3.0]
    MC:
      class: Sparse
      name: AMPA
      params:
        fraction: 0.5
  GC:
    MPP:
      class: Log-Normal
      name: AMPA
      params:
        mu: 0.
        sigma: 1.0
        clip: [0.0, 3.0]
    LPP:
      class: Log-Normal
      name: AMPA
      params:
        mu: 0.
        sigma: 1.0
        clip: [0.0, 3.0]
Synaptic Optimization:
  GC:
    Parameter ranges:
      Weight all grp ext 1:
        !!python/tuple [MPP, LPP]:
          apical:
            AMPA:
              weight:
                a: [0.1, 10.0]
                b: [0.1, 2.0]
        MC:
          apical:
            AMPA:
              weight: [0.1, 5.0]
        BC:
          apical:
            GABA_A:
              weight: [0.01, 2.0]
          soma:
            GABA_A:
              weight: [0.01, 2.0]
        AAC:
          ais:
            GABA_A:
              weight: [0.01, 2.0]
        HC:
          apical:
            GABA_A:
              weight: [0.01, 2.0]
        HCC:
          apical:
            GABA_A:
              weight: [0.01, 2.0]
        NGFC:
          apical:
            GABA_A:
              weight: [0.01, 2.0]
            GABA_B:
              weight: [0.01, 2.0]
        MOPP:
          apical:
            GABA_A:
              weight: [0.01, 2.0]
      Weight all grp ext 2:
        !!python/tuple [MPP, LPP]:
          apical:
            AMPA:
              weight:
                a: [0.1, 10.0]
                b: [0.1, 2.0]
        MC:
          apical:
            AMPA:
              weight: [0.1, 5.0]
        BC:
          apical:
            GABA_A:
              weight: [0.01, 2.0]
          soma:
            GABA_A:
              weight: [0.01, 2.0]
        AAC:
          ais:
            GABA_A:
              weight: [0.01, 2.0]
        !!python/tuple [HC, HCC]:
          apical:
            GABA_A:
              weight: [0.01, 2.0]
        !!python/tuple [NGFC, MOPP]:
          apical:
            GABA_A:
              weight: [0.01, 2.0]
            GABA_B:
              weight: [0.01, 2.0]
      Weight all grp:
        !!python/tuple [MPP, LPP]:
          apical:
            AMPA:
              weight:
                a: [1.0, 5.0]
        MC:
          apical:
            AMPA:
              weight: [1.0, 2.0]
        BC:
          apical:
            GABA_A:
              weight: [0.01, 1.0]
          soma:
            GABA_A:
              weight: [0.01, 1.0]
        AAC:
          ais:
            GABA_A:
              weight: [0.01, 1.0]
        !!python/tuple [HC, HCC]:
          apical:
            GABA_A:
              weight: [0.01, 1.0]
        !!python/tuple [NGFC, MOPP]:
          apical:
            GABA_A:
              weight: [0.01, 1.0]
            GABA_B:
              weight: [0.01, 1.0]
      Weight no MC grp:
        !!python/tuple [MPP, LPP]:
          apical:
            AMPA:
              weight:
                a: [1.0, 10.0]
        BC:
          apical:
            GABA_A:
              weight: [0.001, 1.0]
          soma:
            GABA_A:
              weight: [0.001, 1.0]
        AAC:
          ais:
            GABA_A:
              weight: [0.001, 1.0]
        !!python/tuple [HC, HCC]:
          apical:
            GABA_A:
              weight: [0.001, 1.0]
        !!python/tuple [NGFC, MOPP]:
          apical:
            GABA_A:
              weight: [0.001, 1.0]
            GABA_B:
              weight: [0.001, 1.0]
      Weight no MC:
        !!python/tuple [MPP, LPP]:
          apical:
            AMPA:
              weight:
                a: [1.0, 10.0]
        BC:
          apical:
            GABA_A:
              weight: [0.001, 1.0]
          soma:
            GABA_A:
              weight: [0.001, 1.0]
        AAC:
          ais:
            GABA_A:
              weight: [0.001, 1.0]
        HC:
          apical:
            GABA_A:
              weight: [0.001, 1.0]
        HCC:
          apical:
            GABA_A:
              weight: [0.001, 1.0]
        NGFC:
          apical:
            GABA_A:
              weight: [0.001, 1.0]
            GABA_B:
              weight: [0.001, 1.0]
        MOPP:  
          apical:
            GABA_A:
              weight: [0.001, 1.0]
      Weight all inh soma dend:
        !!python/tuple [MPP, LPP]:
          apical:
            AMPA:
              weight:
                a: [1.0, 10.0]
        MC:
          apical:
            AMPA:
              weight: [0.1, 3.0]
        !!python/tuple [AAC, BC]:
          soma:
            GABA_A:
              weight: [0.001, 1.0]
          ais:
            GABA_A:
              weight: [0.001, 1.0]
        !!python/tuple [BC, HC, HCC, NGFC, MOPP]:
          apical:
            GABA_A:
              weight: [0.001, 1.0]
            GABA_B:
              weight: [0.001, 1.0]
      Weight all no MC inh soma dend:
        !!python/tuple [MPP, LPP]:
          apical:
            AMPA:
              weight:
                a: [1.0, 10.0]
        !!python/tuple [AAC, BC]:
          soma:
            GABA_A:
              weight: [0.001, 1.0]
          ais:
            GABA_A:
              weight: [0.001, 1.0]
        !!python/tuple [BC, HC, HCC, NGFC, MOPP]:
          apical:
            GABA_A:
              weight: [0.001, 1.0]
            GABA_B:
              weight: [0.001, 1.0]
      Weight inhibitory grp:
        BC:
          apical:
            GABA_A:
              weight: [0.01, 1.0]
          soma:
            GABA_A:
              weight: [0.01, 1.0]
        AAC:
          ais:
            GABA_A:
              weight: [0.01, 1.0]
        !!python/tuple [HC, HCC]:
          apical:
            GABA_A:
              weight: [0.01, 1.0]
        !!python/tuple [NGFC, MOPP]:
          apical:
            GABA_A:
              weight: [0.01, 1.0]
            GABA_B:
              weight: [0.001, 1.0]
      Weight excitatory:
        MPP:
          apical:
            AMPA:
              weight:
                a: [1.0, 5.0]
                b: [0.1, 2.0]
        LPP:
          apical:
            AMPA:
              weight:
                a: [0.1, 5.0]
                b: [0.1, 2.0]
        MC:
          apical:
            AMPA:
              weight: [0.1, 2.0]
      Weight excitatory grp:
        !!python/tuple [MPP, LPP]:
          apical:
            AMPA:
              weight:
                a: [1.0, 5.0]
                b: [0.1, 2.0]
        MC:
          apical:
            AMPA:
              weight: [0.1, 2.0]
      Weight all:
        !!python/tuple [MPP, LPP]:
          apical:
            AMPA:
              weight:
                a: [1.0, 5.0]
                b: [0.1, 2.0]
        MC:
          apical:
            AMPA:
              weight: [0.1, 2.0]
        BC:
          apical:
            GABA_A:
              weight: [0.01, 1.0]
          soma:
            GABA_A:
              weight: [0.01, 1.0]
        AAC:
          ais:
            GABA_A:
              weight: [0.01, 1.0]
        HCC:
          apical:
            GABA_A:
              weight: [0.01, 1.0]
        HC:
          apical:
            GABA_A:
              weight: [0.01, 1.0]
        NGFC:
          apical:
            GABA_A:
              weight: [0.01, 1.0]
            GABA_B:
              weight: [0.01, 1.0]
        MOPP:
          apical:
            GABA_A:
              weight: [0.01, 1.0]
    Targets:
      state:
        v:
          mean: -68.0
          peak: -50.0
      firing rate: 1.0
      baseline firing rate: 0.1
      fraction active: 0.01
  MC:
    Parameter ranges:
      Weight no GC MC:
        CA3c:
          apical:
            AMPA:
              weight:
                a: [0.1, 10.0]
        BC:
          apical:
            GABA_A:
              weight: [0.001, 1.0]
          soma:
            GABA_A:
              weight: [0.001, 1.0]
        AAC:
          ais:
            GABA_A:
              weight: [0.001, 1.0]
        HC:
          apical:
            GABA_A:
              weight: [0.001, 1.0]
        HCC:
          apical:
            GABA_A:
              weight: [0.001, 1.0]
    Targets:
      state:
        v:
          mean: -68.0
          peak: -50.0
      firing rate: 1.5
      baseline firing rate: 1.0
      fraction active: 0.3
  BC:
    Targets:
      firing rate: 21.0
  HCC:
    Targets:
      firing rate: 10.0
