Network Clamp:  !include Network_Clamp.yaml
Model Name: Single_GC_Exc_Sat_SLN_IN_Izh_extent
Dataset Name: Slice
Definitions: !include Definitions.yaml
Global Parameters: !include Global.yaml
Geometry: !include Geometry.yaml
Random Seeds: !include Random.yaml
Cell Data: dentatenet_Full_Scale_GC_Exc_Sat_SLN_extent_arena_margin_20201001_compressed.h5
Connection Data: dentatenet_Full_Scale_GC_Exc_Sat_SLN_extent_arena_margin_20201001_compressed.h5
#Gap Junction Data: DG_gapjunctions_20191112.h5
Connection Generator: !include Full_Scale_Connections_GC_Exc_Sat_IN_Izh.yaml
Recording: !include Recording.yaml
Stimulus: !include Input_Configuration.yaml
Analysis: !include Analysis_Configuration.yaml
## Cell types for dentate gyrus model
Cell Types:
  GC:
    template: DGC
    template file: DGC_Template_minimal.hoc
    mechanism file: 20200219_DG_GC_excitability_synint_combined_gid_0_mech.yaml
    synapses:
      correct_for_spines: True
      weights: !include GC_SLN_weights.yaml
      density: !include GC_synapse_density.yaml
  MC:
    template: Izhikevich
    mechanism file: 20201022_DG_MC_Izhi_cell_attrs.yaml
    synapses:
      weights: !include MC_SLN_weights.yaml
      density: !include MC_synapse_density.yaml
  HC:
    template: HIPPCell
    synapses:
      density: !include HC_synapse_density.yaml
  BC:
    template: BasketCell
    synapses:
      density: !include BC_synapse_density.yaml
  AAC:
    template: AxoAxonicCell
    synapses:
      density: !include AAC_synapse_density.yaml
  HCC:
    template: HICAPCell
    synapses:
      density: !include HCC_synapse_density.yaml
  NGFC:
    template: NGFCell
    synapses:
      density: !include NGFC_synapse_density.yaml
  MOPP:
    template: MOPPCell
    synapses:
      density: !include NGFC_synapse_density.yaml
  IS:
    template: ISCell
    synapses:
      density: !include IS_synapse_density.yaml
  MPP:
    template: MPPCell
    spike train:
      namespace: Input Spikes
      attribute: Spike Train
  LPP:
    template: LPPCell
    spike train:
      namespace: Input Spikes
      attribute: Spike Train
  CA3c:
    template: CA3Cell
    spike train:
      namespace: Input Spikes
      attribute: Spike Train

