Template Parameter Rules:
  StimCell:
    - rate
Input Generator:
  BC:
    template: StimCell
    params:
      rate: 1
Weight Generator:
  MC:
    GC:
      class: Log-Normal
      name: AMPA
      params:
        mu: 0.
        sigma: 1.0
  GC:
    MPP:
      class: Log-Normal
      name: AMPA
      params:
        mu: 0.
        sigma: 1.0
    LPP:
      class: Log-Normal
      name: AMPA
      params:
        mu: 0.
        sigma: 1.0
    MC:
      class: Log-Normal
      name: AMPA
      params:
        mu: 0.
        sigma: 1.0


