Template Parameter Rules:
  StimCell:
    - rate
Input Generator:
  MPP:
    template: StimCell
    params:
      rate: 10.
  LPP:
    template: StimCell
    params:
      rate: 10.
  BC:
    template: StimCell
    params:
      rate: 25.
  AAC:
    template: StimCell
    params:
      rate: 25.
  HC:
    template: StimCell
    params:
      rate: 20.
  HCC:
    template: StimCell
    params:
      rate: 5.
  IS:
    template: StimCell
    params:
      rate: 2.
  NGFC:
    template: StimCell
    params:
      rate: 2.
  MOPP:
    template: StimCell
    params:
      rate: 2.
  MC:
    template: StimCell
    params:
      rate: 2.
  CA3c:
    template: StimCell
    params:
      rate: 2.
  GC:
    template: StimCell
    params:
      rate: 1.0
Weight Generator:
  MC:
    GC:
      class: Log-Normal
      name: AMPA
      params:
        mu: 0.
        sigma: 1.0
        clip: [0.0, 3.0]
    MC:
      class: Sparse
      name: AMPA
      params:
        fraction: 0.5
  GC:
    MPP:
      class: Log-Normal
      name: AMPA
      params:
        mu: 0.
        sigma: 1.0
        clip: [0.0, 3.0]
    LPP:
      class: Log-Normal
      name: AMPA
      params:
        mu: 0.
        sigma: 1.0
        clip: [0.0, 3.0]
Synaptic Optimization:
  GC:
    Parameter ranges:
      AAC:
        ais:
          GABA_A:
            g_unit: 
             a: [0.0005, 0.004]
      BC:
        soma:
          GABA_A:
            g_unit: 
             a: [0.0005, 0.004]
        apical:
          GABA_A:
            g_unit: 
             a: [0.0005, 0.004]
      HC:
        apical:
          GABA_A:
            g_unit: [0.0005, 0.004]
      HCC:
        apical:
          GABA_A:
            g_unit: [0.0005, 0.004]
      MOPP:
        apical:
          GABA_A:
            g_unit: [0.0005, 0.004]
      NGFC:
        apical:
          GABA_A:
            g_unit: [0.0005, 0.004]
          GABA_B:
            g_unit: [0.0005, 0.004]
    Targets:
      firing rate: 0.2
      fraction active: 0.01
  MC:
    Parameter ranges:
      HC:
        apical:
          GABA_A:
            g_unit: 
              a: [0.0005, 0.004]
      HCC:
        apical:
          GABA_A:
            g_unit: 
              a: [0.0005, 0.004]
      BC:
        apical:
          GABA_A:
            g_unit: 
              a: [0.0005, 0.004]
        soma:
          GABA_A:
            g_unit: 
              a: [0.0005, 0.004]
      AAC:
        soma:
          GABA_A:
            g_unit: 
              a: [0.0001, 0.004]
#        ais:
#          GABA_A:
#            g_unit: 
#               a: [0.0001, 0.003]
    Targets:
      firing rate: 1.0
      fraction active: 0.7
  BC:
    Parameter ranges:
      MC:
        apical:
          AMPA:
            g_unit: [0.0001, 0.003]
      BC:
        basal:
          GABA_A:
            g_unit: [0.0001, 0.003]
        soma:
          GABA_A:
            g_unit: [0.0001, 0.003]
      HC:
        apical:
          GABA_A:
            g_unit: [0.0001, 0.003]
      HCC:
        apical:
          GABA_A:
            g_unit: [0.0001, 0.003]
      NGFC:
        apical:
          GABA_A:
            g_unit: [0.0001, 0.003]
      MOPP:
        apical:
          GABA_A:
            g_unit: [0.0001, 0.003]
      IS:
        basal:
          GABA_A:
            g_unit: [0.0001, 0.003]
        apical:
          GABA_A:
            g_unit: [0.0001, 0.003]
    Targets:
      firing rate: 21.0
  HCC:
    Parameter ranges:
      GC:
        apical:
          AMPA:
            g_unit: [0.0001, 0.003]
        basal:
          AMPA:
            g_unit: [0.0001, 0.003]
        soma:
          AMPA:
            g_unit: [0.0001, 0.003]
      MC:
        apical:
          AMPA:
            g_unit: [0.0001, 0.003]
        basal:
          AMPA:
            g_unit: [0.0001, 0.003]
        soma:
          AMPA:
            g_unit: [0.0001, 0.003]
      HCC:
        apical:
          GABA_A:
            g_unit: [0.0001, 0.002]
        basal:
          GABA_A:
            g_unit: [0.0001, 0.004]
      NGFC:
        apical:
          GABA_A:
            g_unit: [0.0001, 0.002]
      MOPP:
        apical:
          GABA_A:
            g_unit: [0.0001, 0.002]
      IS:
        basal:
          GABA_A:
            g_unit: [0.0001, 0.002]
        apical:
          GABA_A:
            g_unit: [0.0001, 0.002]
        soma:
          GABA_A:
            g_unit: [0.0001, 0.002]
    Targets:
      firing rate: 10.0
