Template Parameter Rules:
  StimCell:
    - rate
Weight Generator:
  MC:
    GC:
      class: Log-Normal
      name: AMPA
      params:
        mu: 0.
        sigma: 1.0
        clip: [0.0, 3.0]
    MC:
      class: Sparse
      name: AMPA
      params:
        fraction: 0.5
  GC:
    MPP:
      class: Log-Normal
      name: AMPA
      params:
        mu: 0.
        sigma: 1.0
        clip: [0.0, 3.0]
    LPP:
      class: Log-Normal
      name: AMPA
      params:
        mu: 0.
        sigma: 1.0
        clip: [0.0, 3.0]
Synaptic Optimization:
  GC:
    Parameter ranges:
      Weight all grp ext 2:
        !!python/tuple [MPP, LPP]:
          apical:
            AMPA:
              weight:
                a: [0.01, 10.0]
                b: [0.01, 2.0]
        MC:
          apical:
            AMPA:
              weight: [0.01, 5.0]
        BC:
          apical:
            GABA_A:
              weight: [0.001, 4.0]
          soma:
            GABA_A:
              weight: [0.0005, 4.0]
        AAC:
          ais:
            GABA_A:
              weight: [0.001, 4.0]
        !!python/tuple [HC, HCC]:
          apical:
            GABA_A:
              weight: [0.001, 4.0]
        !!python/tuple [NGFC, MOPP]:
          apical:
            GABA_A:
              weight: [0.001, 4.0]
            GABA_B:
              weight: [0.001, 4.0]
      Weight all grp:
        !!python/tuple [MPP, LPP]:
          apical:
            AMPA:
              weight:
                a: [0.01, 5.0]
                b: [0.01, 1.0]
        MC:
          apical:
            AMPA:
              weight: [0.01, 4.0]
        BC:
          apical:
            GABA_A:
              weight: [0.001, 2.0]
          soma:
            GABA_A:
              weight: [0.0005, 2.0]
        AAC:
          ais:
            GABA_A:
              weight: [0.001, 2.0]
        !!python/tuple [HC, HCC]:
          apical:
            GABA_A:
              weight: [0.001, 1.0]
        !!python/tuple [NGFC, MOPP]:
          apical:
            GABA_A:
              weight: [0.01, 1.0]
            GABA_B:
              weight: [0.001, 1.0]
      Weight all inh soma dend:
        !!python/tuple [MPP, LPP]:
          apical:
            AMPA:
              weight:
                a: [0.01, 5.0]
                b: [0.01, 1.0]
        MC:
          apical:
            AMPA:
              weight: [0.01, 4.0]
        !!python/tuple [AAC, BC]:
          soma:
            GABA_A:
              weight: [0.0005, 2.0]
          ais:
            GABA_A:
              weight: [0.001, 4.0]
        !!python/tuple [BC, HC, HCC, NGFC, MOPP]:
          apical:
            GABA_A:
              weight: [0.0005, 2.0]
            GABA_B:
              weight: [0.001, 1.0]
      Weight inhibitory grp:
        BC:
          apical:
            GABA_A:
              weight: [0.001, 4.0]
          soma:
            GABA_A:
              weight: [0.001, 4.0]
        AAC:
          ais:
            GABA_A:
              weight: [0.001, 4.0]
        !!python/tuple [HC, HCC]:
          apical:
            GABA_A:
              weight: [0.001, 4.0]
        !!python/tuple [NGFC, MOPP]:
          apical:
            GABA_A:
              weight: [0.01, 4.0]
            GABA_B:
              weight: [0.001, 1.0]
      Weight all:
        !!python/tuple [MPP, LPP]:
          apical:
            AMPA:
              weight:
                a: [0.01, 5.0]
                b: [0.01, 1.0]
        MC:
          apical:
            AMPA:
              weight: [0.01, 4.0]
        BC:
          apical:
            GABA_A:
              weight: [0.001, 4.0]
          soma:
            GABA_A:
              weight: [0.0005, 4.0]
        AAC:
          ais:
            GABA_A:
              weight: [0.001, 4.0]
        HCC:
          apical:
            GABA_A:
              weight: [0.001, 2.0]
        HC:
          apical:
            GABA_A:
              weight: [0.001, 2.0]
        NGFC:
          apical:
            GABA_A:
              weight: [0.001, 2.0]
            GABA_B:
              weight: [0.001, 2.0]
        MOPP:
          apical:
            GABA_A:
              weight: [0.001, 2.0]
    Targets:
      state:
        v: -60.0
      firing rate: 0.75
      fraction active: 0.01
  MC:
    Targets:
      firing rate: 1.5
      fraction active: 0.3
  BC:
    Targets:
      firing rate: 21.0
  HCC:
    Targets:
      firing rate: 10.0
