Template Parameter Rules:
  StimCell:
    - rate
Input Generator:
  MPP:
    template: StimCell
    params:
      rate: 10.
  LPP:
    template: StimCell
    params:
      rate: 10.
  BC:
    template: StimCell
    params:
      rate: 24.
  AAC:
    template: StimCell
    params:
      rate: 25.
  HC:
    template: StimCell
    params:
      rate: 20.
  HCC:
    template: StimCell
    params:
      rate: 5.
  IS:
    template: StimCell
    params:
      rate: 2.
  NGFC:
    template: StimCell
    params:
      rate: 2.
  MOPP:
    template: StimCell
    params:
      rate: 2.
  MC:
    template: StimCell
    params:
      rate: 2.
  CA3c:
    template: StimCell
    params:
      rate: 2.
  GC:
    template: StimCell
    params:
      rate: 1.0
Weight Generator:
  MC:
    GC:
      class: Log-Normal
      name: AMPA
      params:
        mu: 0.
        sigma: 1.0
        clip: [0.0, 3.0]
    MC:
      class: Sparse
      name: AMPA
      params:
        fraction: 0.5
  GC:
    MPP:
      class: Log-Normal
      name: AMPA
      params:
        mu: 0.
        sigma: 1.0
        clip: [0.0, 3.0]
    LPP:
      class: Log-Normal
      name: AMPA
      params:
        mu: 0.
        sigma: 1.0
        clip: [0.0, 3.0]
Synaptic Optimization:
  Parameter ranges:
    Weight all grp:
      GC:
        !!python/tuple [MPP, LPP]:
          apical:
            AMPA:
              weight:
                a: [0.01, 5.0]
                b: [0.01, 1.0]
        MC:
          apical:
            AMPA:
              weight: [0.01, 4.0]
        BC:
          apical:
            GABA_A:
              weight: [0.001, 2.0]
          soma:
            GABA_A:
              weight: [0.0005, 2.0]
        AAC:
          ais:
            GABA_A:
              weight: [0.001, 2.0]
        !!python/tuple [HC, HCC]:
          apical:
            GABA_A:
              weight: [0.001, 1.0]
        !!python/tuple [NGFC, MOPP]:
          apical:
            GABA_A:
              weight: [0.01, 1.0]
            GABA_B:
              weight: [0.001, 1.0]
    Weight inhibitory grp:
      GC:
        BC:
          apical:
            GABA_A:
              weight: [0.001, 1.0]
          soma:
            GABA_A:
              weight: [0.0005, 1.0]
        AAC:
          ais:
            GABA_A:
              weight: [0.001, 1.0]
        !!python/tuple [HC, HCC]:
          apical:
            GABA_A:
              weight: [0.001, 1.0]
        !!python/tuple [NGFC, MOPP]:
          apical:
            GABA_A:
              weight: [0.01, 1.0]
            GABA_B:
              weight: [0.001, 1.0]
  Targets:
    GC:
      state:
        v: -65.0
      firing rate: 0.75
      fraction active: 0.01
    MC:
      firing rate: 1.5
      fraction active: 0.3
  BC:
      firing rate: 21.0
  HCC:
      firing rate: 10.0
