Network Clamp:  !include Network_Clamp.yaml
Model Name: Single_GC_Exc_Sat_SynExp3NMDA2fd_SLN_CLS_IN_PR_GC_phenotypes
Dataset Name: Slice
Definitions: !include Definitions.yaml
Global Parameters: !include Global.yaml
Geometry: !include Geometry.yaml
Random Seeds: !include Random.yaml
Cell Data: dentatenet_Slice_GC_phenotypes_20230523.h5
Connection Data: dentatenet_Slice_GC_phenotypes_20230523.h5
#Gap Junction Data: DG_gapjunctions_20191112.h5
Connection Generator: !include Full_Scale_Connections_GC_Exc_Sat_SynExp3NMDA2fd_IN_PR.yaml
Recording: !include Recording.yaml
Stimulus: !include Input_Configuration.yaml
Analysis: !include Analysis_Configuration.yaml
## Cell types for dentate gyrus model
Cell Types:
  GC:
    template: DGC
    template file: DGC_Template_minimal.hoc
    mechanism file: 20220513_DG_GC_excitability_synint_SynExp3NMDA2_gid_118936_mech.yaml
    phenotypes: !include GC_phenotype_configs.yaml
    synapses:
      correct_for_spines: True
      weights: !include GC_SLN_weights.yaml
      clusters: !include GC_SLN_clusters.yaml
      density: !include GC_synapse_density.yaml
  MC:
    template: PRS_nrn
    template file: PRS_nrn.hoc
    mechanism file: DG_MC_PR_SynExp3NMDA2_config.yaml
    synapses:
      weights: !include MC_SLN_weights.yaml
      density: !include MC_synapse_density.yaml
  HC:
    template: HIPPCell
    synapses:
      density: !include HC_synapse_density.yaml
  BC:
    template: BasketCell
    synapses:
      density: !include BC_synapse_density.yaml
  AAC:
    template: AxoAxonicCell
    synapses:
      density: !include AAC_synapse_density.yaml
  HCC:
    template: HICAPCell
    synapses:
      density: !include HCC_synapse_density.yaml
  NGFC:
    template: NGFCell
    synapses:
      density: !include NGFC_synapse_density.yaml
  MOPP:
    template: MOPPCell
    synapses:
      density: !include NGFC_synapse_density.yaml
  IS:
    template: ISCell
    synapses:
      density: !include IS_synapse_density.yaml
  MPP:
    template: VecStim
    spike train:
      namespace: Input Spikes
      attribute: Spike Train
  LPP:
    template: VecStim
    spike train:
      namespace: Input Spikes
      attribute: Spike Train
  CA3c:
    template: VecStim
    spike train:
      namespace: Input Spikes
      attribute: Spike Train
  ConMC:
    template: VecStim
    spike train:
      namespace: Input Spikes
      attribute: Spike Train

