## Recording configuration for field potentials and intracellular quantities
Intracellular:
  Network default:
    dt: 0.1
    section quantity:
      v:
        swc types:
          - soma
  Network clamp default:
    dt: 0.025
    section quantity:
      v:
        swc types:
          - soma
          - ais
          - apical
          - basal
  Network clamp axial current:
    dt: 0.025
    section quantity:
      start.v:
        variable: v
        loc:
          - 1e-3
          - 1e-3
        swc types:
          - apical
          - basal
      mid.v:
        variable: v
        loc:
          - 0.5
          - 0.5
          - 0.5
        swc types:
          - soma
          - apical
          - basal
  Network clamp inh synaptic:
    dt: 0.1
    reduce: True
    section quantity:
      v:
        swc types:
          - soma
          - hillock
          - apical
          - basal
    synaptic quantity:
      i:
        syn types:
          - inhibitory
  Network clamp exc synaptic:
    dt: 0.1
    reduce: True
    section quantity:
      i:
        swc types:
          - soma
      v:
        swc types:
          - soma
          - hillock
          - ais
          - axon
          - apical
          - basal
    synaptic quantity:
      i:
        syn types:
          - excitatory
  Network clamp all synaptic:
    dt: 0.5
    reduce: True
    section quantity:
      v:
        swc types:
          - soma
          - ais
          - axon
          - hillock
          - apical
          - basal
    synaptic quantity:
      i: {}
  Network clamp apical g synaptic:
    dt: 0.1
    reduce: True
    section quantity:
      v:
        swc types:
          - soma
          - hillock
          - ais
          - axon
          - apical
          - basal
      g_Nav11a:
        swc types:
          - apical
      gk_Kir21:
        swc types:
          - apical
      gk_Kv11:
        swc types:
          - apical
      gk_Kv42:
        swc types:
          - apical
    synaptic quantity:
      i:
        syn types:
          - excitatory
  Network clamp apical i synaptic:
    dt: 0.1
    reduce: True
    section quantity:
      v:
        swc types:
          - soma
          - hillock
          - ais
          - axon
          - apical
          - basal
      ina:
        swc types:
          - apical
      ik:
        swc types:
          - apical
      ica:
        swc types:
          - apical
    synaptic quantity:
      i:
        syn types:
          - excitatory
          - inhibitory
  Network clamp all i synaptic:
    dt: 0.1
    reduce: True
    section quantity:
      v:
        swc types:
          - soma
          - hillock
          - ais
          - axon
          - apical
          - basal
      ina:
        swc types:
          - apical
          - soma
          - hillock
          - ais
          - axon
      ik:
        swc types:
          - apical
          - soma
          - hillock
          - ais
          - axon
      ica:
        swc types:
          - apical
          - soma
          - hillock
          - ais
          - axon
    synaptic quantity:
      i:
        syn types:
          - excitatory
          - inhibitory
  Network clamp soma g exc synaptic:
    dt: 0.1
    reduce: True
    section quantity:
      v:
        swc types:
          - soma
          - hillock
          - ais
          - axon
          - apical
          - basal
      g_Nav11a:
        swc types:
          - soma
      g_Kv21:
        swc types:
          - soma
      gak_BK:
        swc types:
          - soma
      gabk_BK:
        swc types:
          - soma
    synaptic quantity:
      i:
        syn types:
          - excitatory
  Network clamp soma i synaptic:
    dt: 0.1
    reduce: True
    section quantity:
      v:
        swc types:
          - soma
          - hillock
          - ais
          - axon
          - apical
          - basal
      ina_Nav11a:
        swc types:
          - soma
      ik_Kv21:
        swc types:
          - soma
      ik_BK:
        swc types:
          - soma
      ik_sAHP:
        swc types:
          - soma
      ica_Ca_Aradi:
        swc types:
          - soma
    synaptic quantity:
      i:
        syn types:
          - excitatory
LFP:
  # Configuration for virtual local field potential recordings
  Electrode 0:
    rho: 333.0
    position: [-1205.5, 2700.3, -211.7]
    maxEDist: 100.
    fraction: .1
    dt: 0.1
  Electrode 1:
    rho: 333.0
    position: [-1205.5, 2700.3, -411.7]
    maxEDist: 100.
    fraction: .1
    dt: 0.1


  
