## Recording configuration for field potentials and intracellular quantities
Intracellular:
  Network default:
    fraction: 0.001
    section quantity:
      v:
        swc types:
          - soma
  Network clamp default:
    fraction: 1.0
    section quantity:
      v:
        swc types:
          - soma
          - hillock
          - apical
          - basal
  Network clamp synaptic:
    fraction: 1.0
    section quantity:
      v:
        swc types:
          - soma
          - hillock
          - apical
          - basal
    synaptic quantity:
      i: {}
LFP:
  # Configuration for virtual local field potential recordings
  Electrode 0:
    rho: 333.0
    position: [-1205.5, 2700.3, -211.7]
    maxEDist: 100.
    fraction: .1
    dt: 0.1
  Electrode 1:
    rho: 333.0
    position: [-1205.5, 2700.3, -411.7]
    maxEDist: 100.
    fraction: .1
    dt: 0.1


  
