## Model configuration of dentate gyrus network
modelname: dentatenet
datasetName: Reduced_Scale_Control
# Synapse indexing used for cells in dentate gyrus model
synapses:
  order:
    GC: 0
    MC: 1
    HC: 2
    BC: 3
    AAC:  4
    HCC:  5
    NGFC_A: 6
    NGFC_B: 7
    MPP:  8
    LPP:  9
## Cell types for dentate gyrus model
celltypes: 
  GC:
    templateName: DGC
    templateType: forest
    forestFile: DGC_forest_syns_reduced.h5
    synapses:
      0:
        t_rise: 1.5
        t_decay: 5.5
        e_rev: 0
  MC:
    indexfile: MC.dat
    templateName: MossyCell
    templateType: single
    synapses:
      GC:
        location:
          dendrite: [0, 1, 2, 3]
          compartment: 0
        t_rise: 0.5
        t_decay: 6.2
        e_rev: 0
      MC:
        location:
          dendrite: [0, 1, 2, 3]
          compartment: 0
        t_rise: 0.45
        t_decay: 2.2
        e_rev: 0
      HC:
        location:
          dendrite: [0, 1, 2, 3]
          compartment: 2
        t_rise: 0.5
        t_decay: 6.0
        e_rev: -70
      BC:
        location: soma
        t_rise: 0.3
        t_decay: 3.3
        e_rev: -70
      AAC:
        location: soma
        t_rise: 0.3
        t_decay: 3.3
        e_rev: -70
      HCC:
        location:
          dendrite: [0, 1, 2, 3]
          compartment: 2
        t_rise: 0.6
        t_decay: 4.7
        e_rev: -70
  HC:
    indexfile: HC.dat
    templateName: HIPPCell
    templateType: single
    synapses:
      GC:
        location:
          dendrite: [0, 1, 2, 3]
          compartment: 0
        t_rise: 0.3
        t_decay: 0.6
        e_rev: 0
      MC:
        location:
          dendrite: [0, 1, 2, 3]
          compartment: 1
        t_rise: 0.9
        t_decay: 3.6
        e_rev: 0
      HC:
        location:
          dendrite: [0, 1, 2, 3]
          compartment: 0
        t_rise: 0.37
        t_decay: 10.48
        e_rev: -70
      BC:
        location:
          dendrite: [0, 1, 2, 3]
          compartment: 1
        t_rise: 0.265
        t_decay: 2.88
        e_rev: -70
  BC:
    indexfile: BC.dat
    templateName: BasketCell
    templateType: single
    synapses:
      GC:
        location:
          dendrite: [0, 1, 2, 3]
          compartment: 0
        t_rise: 0.3
        t_decay: 0.6
        e_rev: 0
      MC:
        location:
          dendrite: [0, 1]
          compartment: 1
        t_rise: 0.9
        t_decay: 3.6
        e_rev: 0
      HC:
        location:
          dendrite: [0, 1]
          compartment: 3
        t_rise: 0.46
        t_decay: 4.43
        e_rev: -70
      BC:
        location:
          dendrite: [0, 1]
          compartment: 1
        t_rise: 0.22
        t_decay: 3.35
        e_rev: -70
      HCC:
        location:
          dendrite: [0, 1]
          compartment: 1
        t_rise: 0.6
        t_decay: 4.78
        e_rev: -70
      NGFC_A:
        location:
          dendrite: [0, 1]
          compartment: 3
        t_rise: 4.2
        t_decay: 14
        e_rev: -70
      NGFC_B:
        location:
          dendrite: [0, 1]
          compartment: 3
        t_rise: 86.8
        t_decay: 428.1
        e_rev: -70
  AAC:
    indexfile: AAC.dat
    templateName: AxoAxonicCell
    templateType: single
    synapses:
      GC:
        location:
          dendrite: [0, 1, 2, 3]
          compartment: 0
        t_rise: 0.3
        t_decay: 0.6
        e_rev: 0
      MC:
        location:
          dendrite: [0, 1]
          compartment: 1
        t_rise: 0.9
        t_decay: 3.6
        e_rev: 0
      HC:
        location:
          dendrite: [0, 1]
          compartment: 3
        t_rise: 0.46
        t_decay: 4.43
        e_rev: -70
      NGFC_A:
        location:
          dendrite: [0, 1]
          compartment: 3
        t_rise: 4.2
        t_decay: 14
        e_rev: -70
      NGFC_B:
        location:
          dendrite: [0, 1]
          compartment: 3
        t_rise: 86.8
        t_decay: 428.1
        e_rev: -70
#  HCC:
#    indexfile: HCC.dat
#    templateName: HICAPCell
#    templateType: single
    # synapses:
    #   GC:
    #     location:
    #       dendrite: [0, 1, 2, 3]
    #       compartment: 0
    #     t_rise: 0.3
    #     t_decay: 0.6
    #     e_rev: 0
    #   MC:
    #     location:
    #       dendrite: [0, 1]
    #       compartment: 1
    #     t_rise: 0.9
    #     t_decay: 3.6
    #     e_rev: 0
    #   BC:
    #     location:
    #       dendrite: [0, 1]
    #       compartment: 1
    #     t_rise: 0.28
    #     t_decay: 3.45
    #     e_rev: -70
    #   HCC:
    #     location:
    #       dendrite: [0, 1]
    #       compartment: 1
    #     t_rise: 0.72
    #     t_decay: 4.7
    #     e_rev: -70
    #   NGFC_A:
    #     location:
    #       dendrite: [0, 1]
    #       compartment: 3
    #     t_rise: 4.2
    #     t_decay: 14
    #     e_rev: -70
    #   NGFC_B:
    #     location:
    #       dendrite: [0, 1]
    #       compartment: 3
    #     t_rise: 86.8
    #     t_decay: 428.1
    #     e_rev: -70
  NGFC:
    indexfile: NGFC.dat
    templateName: NGFCell
    templateType: single
    synapses:
      HC:
        location:
          dendrite: [0, 1, 2, 3]
          compartment: 0
        t_rise: 0.72
        t_decay: 10
        e_rev: -70
      NGFC_A:
        location:
          dendrite: [0, 1, 2, 3]
          compartment: 0
        t_rise: 4.5
        t_decay: 13.8
        e_rev: -70
      NGFC_B:
        location:
          dendrite: [0, 1, 2, 3]
          compartment: 0
        t_rise: 86.8
        t_decay: 428.1
        e_rev: -70
  MPP:
    indexfile: MPP.dat
    templateName: MPPCell
    templateType: single
#  LPP:
#    indexfile: LPP.dat
#    templateName: LPPCell
#    templateTemplateType: single
## Connectivity configuration for dentate gyrus model
connectivity:
  connectivityFile: dentate_Reduced_Scale_Control_dbs.h5
  ## Projection definitions
  projections: 
    AACtoGC:
      source: AAC
      destination: GC
      index: absolute
      type: long.+trans.dist
      synIndex: 4
      weight: 1.0
      velocity: 250.0
    BCtoGC:
      source: BC
      destination: GC
      index: absolute
      type: long.+trans.dist
      synIndex: 3
      weight: 0.65
      velocity: 250.0
    HCtoGC:
      source: HC
      destination: GC
      index: absolute
      type: long.+trans.dist
      synIndex: 2
      weight: 6.0
      velocity: 250.0
    MCtoGC:
      source: MC
      destination: GC
      index: absolute
      type: long.+trans.dist
      synIndex: 1
      weight: 0.3
      velocity: 250.0
    NGFCtoGC:
      source: NGFC
      destination: GC
      index: absolute
      type: long.+trans.dist
      synIndex: [6, 7]
      weight: [0.2, 0.1]
      velocity: 250.0
    AACtoMC:
      source: AAC
      destination: MC
      index: absolute
      type: long.+trans.dist
      synIndex: 4
      weight: 3.0
      velocity: 250.0
    BCtoMC:
      source: BC
      destination: MC
      index: absolute
      type: long.+trans.dist
      synIndex: 3
      weight: 1.5
      velocity: 250.0
    GCtoMC:
      source: GC
      destination: MC
      index: absolute
      type: long.+trans.dist
      synIndex: 0
      weight: 0.7
      velocity: 250.0
    HCtoMC:
      source: HC
      destination: MC
      index: absolute
      type: long.+trans.dist
      synIndex: 2
      weight: 1.0
      velocity: 250.0
    MCtoMC:
      source: MC
      destination: MC
      index: absolute
      type: long.+trans.dist
      synIndex: 1
      weight: 0.5
      velocity: 250.0
    HCtoHC:
      source: HC
      destination: HC
      index: absolute
      type: long.+trans.dist
      synIndex: 2
      weight: 0.623
      velocity: 250.0
    MCtoHC:
      source: MC
      destination: HC
      index: absolute
      type: long.+trans.dist
      synIndex: 1
      weight: 0.2
      velocity: 250.0
    BCtoBC:
      source: BC
      destination: BC
      index: absolute
      type: long.+trans.dist
      synIndex: 3
      weight: 4.27
      velocity: 250.0
    GCtoBC:
      source: GC
      destination: BC
      index: absolute
      type: long.+trans.dist
      synIndex: 0
      weight: 4.7
      velocity: 250.0
    MCtoBC:
      source: MC
      destination: BC
      index: absolute
      type: long.+trans.dist
      synIndex: 1
      weight: 0.3
      velocity: 250.0
    NGFCtoBC:
      source: NGFC
      destination: BC
      index: absolute
      type: long.+trans.dist
      synIndex: [6, 7]
      weight: [0.183, 0.181]
      velocity: 250.0
    GCtoAAC:
      source: GC
      destination: AAC
      index: absolute
      type: long.+trans.dist
      synIndex: 0
      weight: 4.7
      velocity: 250.0
    MCtoAAC:
      source: MC
      destination: AAC
      index: absolute
      type: long.+trans.dist
      synIndex: 1
      weight: 0.3
      velocity: 250.0
    NGFCtoAAC:
      source: NGFC
      destination: AAC
      index: absolute
      type: long.+trans.dist
      synIndex: [6, 7]
      weight: [0.183, 0.181]
      velocity: 250.0
    HCtoNGFC:
      source: HC
      destination: NGFC
      index: absolute
      type: long.+trans.dist
      synIndex: 2
      weight: 0.473
      velocity: 250.0
    NGFCtoNGFC:
      source: NGFC
      destination: NGFC
      index: absolute
      type: long.+trans.dist
      synIndex: [6, 7]
      weight: [0.113, 0.169]
      velocity: 250.0
##    MPPtoGC:
##      source: MPP
##      destination: GC
##      index: absolute
##      type: syn
##      synType: 0
##      weightsFile:  ./dat/MPPsynweights.dat
##      velocity: 250.0
  ## Gap junction projection definitions for dentate gyrus model
  gapjunctions: 
    HCtoHC:
      source: HC
      destination: HC
    BCtoBC:
      source: BC
      destination: BC
    NGFCtoNGFC:
      source: NGFC
      destination: NGFC
