Synapse Mechanisms:
  SatAMPA: SatExp2Syn
  NMDA: FacilNMDA
  SatGABA_A: SatExp2Syn
  SatGABA_B: SatExp2Syn
Synapse Parameter Rules:
  EPSC:
    mech_file: exp2EPSC.mod
    mech_params:
      - tau_rise
      - tau_decay
      - i_unit
    netcon_params:
      weight: 0
  LinExp2Syn:
    mech_file: lin_exp2syn.mod
    mech_params:
      - tau_rise
      - tau_decay
      - e
    netcon_params:
      weight: 0
      g_unit: 1
  SatExp2Syn:
    mech_file: sat_exp2syn.mod
    mech_params:
      - sat
      - dur_onset
      - tau_offset
      - e
    netcon_params:
      weight: 0
      g_unit: 1
  FacilExp2Syn:
    mech_file: facil_exp2syn.mod
    mech_params:
      - sat
      - dur_onset
      - tau_offset
      - e
      - f_inc
      - f_max
      - f_tau
    netcon_params:
      weight: 0
      g_unit: 1
  FacilNMDA:
    mech_file: facil_NMDA.mod
    mech_params:
      - sat
      - dur_onset
      - tau_offset
      - e
      - f_inc
      - f_max
      - f_tau
      - mg
      - Kd
      - gamma
    netcon_params:
      weight: 0
      g_unit: 1
  Exp2Syn:
    mech_file: exp2syn.mod
    mech_params:
      - tau1
      - tau2
      - e
    netcon_params:
      weight: 0
  AMPA_KIN:
    mech_file: ampa_kin.mod
    mech_params:
      - gmax
    netcon_params:
      weight: 0
  NMDA_KIN5:
    mech_file: nmda_kin5.mod
    mech_params:
      - gmax
    netcon_params:
      weight: 0
# full width in um [S-T, M-L]
Axon Width:
  GC:   [900., 900.]
  MPP:  [1500., 3000.]
  LPP:  [1500., 3000.]
  PYR:  [3000., 5000.]
  MC:   [4000., 4000.]
  NGFC: [2000., 2000.]
  AAC:  [1700., 1100.]
  BC:   [1700., 1000.]
  HCC:  [2600., 2600.]
  HC:   [3000., 3000.]
  IS:   [3000., 3000.]
  MOPP: [2000., 2000.]
Axon Offset:
    MC:   [1000., 1000.]
    GC:   [0., 0.]
    MPP:  [0., 0.]
    LPP:  [0., 0.]
    PYR:  [0., 0.]
    NGFC: [0., 0.]
    AAC:  [0., 0.]
    BC:   [0., 0.]
    HCC:  [0., 0.]
    HC:   [0., 0.]
    IS:   [0., 0.]
    MOPP: [0., 0.]
Synapses:
  GC:
    MPP:
      type: excitatory
      sections: [apical]
      layers: [MML]
      proportions: [1.0]
      mechanisms:
        SatAMPA:
          dur_onset: 0.5
          tau_offset: 5.5
          sat: 0.9
          e: 0
          g_unit: 0.0016
    LPP:
      type: excitatory
      sections: [apical]
      layers: [OML]
      proportions: [1.0]
      mechanisms:
        SatAMPA:
          dur_onset: 0.5
          tau_offset: 5.5
          sat: 0.9
          e: 0
          g_unit: 0.0018
    MC:
      type: excitatory
      sections: [apical]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        SatAMPA:
          dur_onset: 0.5
          tau_offset: 5.5
          sat: 0.9
          e: 0
          g_unit: 0.00019
    AAC:
      type: inhibitory
      sections: [ais]
      layers: [GCL]
      proportions: [1.0]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.3
          tau_offset: 2.9
          sat: 0.9
          e: -75
          g_unit: 0.001
    BC:   
      type: inhibitory
      sections: [soma, apical]
      layers: [GCL, IML]
      proportions: [1.0, 0.69]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.25
          tau_offset: 5.5
          sat: 0.9
          e: -75
          g_unit: 0.00065
    HCC:  
      type: inhibitory
      sections: [apical]
      layers: [IML]
      proportions: [0.31]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.4
          tau_offset: 1.1
          sat: 0.9
          e: -75
          g_unit: 0.003
    HC:   
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.5, 0.5]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.5
          tau_offset: 6.0
          sat: 0.9
          e: -75
          g_unit: 0.006
    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.28, 0.28]
      mechanisms:
        SatGABA_A:
          dur_onset:  0.1
          tau_offset: 10.0
          sat: 0.9
          e:   -75
          g_unit: 0.00015
        SatGABA_B:
          dur_onset:  50.0
          tau_offset: 200.0
          sat: 0.9
          e:   -90
          g_unit: 0.0001
    MOPP: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.22, 0.22]
      mechanisms:
        SatGABA_A:
          dur_onset:  0.1
          tau_offset: 10.0
          sat: 0.9
          e:   -75
          g_unit: 0.00015
  MC:
    GC:   
      type: excitatory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.23]
      mechanisms:
        SatAMPA:
          dur_onset: 0.5
          tau_offset: 6.2
          sat: 0.9
          e: 0
          g_unit: 0.0015
    MC:   
      type: excitatory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.77]
      mechanisms:
        SatAMPA:
          dur_onset: 0.45
          tau_offset: 2.2
          sat: 0.9
          e: 0
          g_unit: 0.0005
    HC:   
      type: inhibitory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.33]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.5
          tau_offset: 6.0
          sat: 0.9
          e: -75
          g_unit: 0.001
    BC:   
      type: inhibitory
      sections: [soma, apical]
      layers: [Hilus, Hilus]
      proportions: [1.0, 0.17]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.3
          tau_offset: 3.3
          sat: 0.9
          e: -75
          g_unit: 0.0015
    AAC:  
      type: inhibitory
      sections: [ais]
      layers: [GCL]
      proportions: [1.0]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.3
          tau_offset: 3.3
          sat: 0.9
          e: -75
          g_unit: 0.003
    HCC:  
      type: inhibitory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.5]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.6
          tau_offset: 4.7
          sat: 0.9
          e: -75
          g_unit: 0.0006
  HC:
    GC:   
      type: excitatory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.72]
      mechanisms:
        SatAMPA:
          dur_onset: 0.3
          tau_offset: 6.2
          sat: 0.9
          e: 0
          g_unit: 0.0047
    MC:   
      type: excitatory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.28]
      mechanisms:
        SatAMPA:
          dur_onset: 0.9
          tau_offset: 3.6
          sat: 0.9
          e: 0
          g_unit: 0.0022
    HC:  
      type: inhibitory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.99]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.37
          tau_offset: 10.48
          sat: 0.9
          e: -75
          g_unit: 0.000623
    IS:  
      type: inhibitory
      sections: [apical, soma]
      layers: [Hilus, Hilus]
      proportions: [0.01, 1.0]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.37
          tau_offset: 10.48
          sat: 0.9
          e: -75
          g_unit: 0.0005
  BC:
    GC:   
      type: excitatory
      sections: [soma, basal]
      layers: [Hilus, Hilus]
      proportions: [1.0, 1.0, 1.0]
      mechanisms:
        SatAMPA:
          dur_onset: 0.3
          tau_offset: 6.2
          sat: 0.9
          e: 0
          g_unit: 0.0047
    MPP:
      type: excitatory
      sections: [apical]
      layers: [MML]
      proportions: [1.0]
      mechanisms:
        SatAMPA:
          dur_onset:  0.5
          tau_offset: 3.0
          sat: 0.9
          e:     0
          g_unit: 0.0005
    LPP:
      type: excitatory
      sections: [apical]
      layers: [OML]
      proportions: [1.0]
      mechanisms:
        SatAMPA:
          dur_onset:  0.5
          tau_offset: 3.0
          sat: 0.9
          e:     0
          g_unit: 0.0005
    MC:   
      type: excitatory
      sections: [apical, apical]
      layers: [Hilus, IML]
      proportions: [1.0, 1.0]
      mechanisms:
        SatAMPA:
          dur_onset: 0.9
          tau_offset: 3.6
          sat: 0.9
          e: 0
          g_unit: 0.0003
    BC:   
      type: inhibitory
      sections: [basal, soma]
      layers: [Hilus, Hilus]
      proportions: [0.67, 1.0]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.22
          tau_offset: 3.35
          sat: 0.9
          e: -75
          g_unit: 0.00427
    HCC:  
      type: inhibitory
      sections: [apical]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.6
          tau_offset: 4.78
          sat: 0.9
          e: -75
          g_unit: 0.000664
    HC:   
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.96, 0.96]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.46
          tau_offset: 4.43
          sat: 0.9
          e: -75
          g_unit: 0.00214
    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.02, 0.02]
      mechanisms:
        SatGABA_A:
          dur_onset:   4.2
          tau_offset: 14.0
          sat: 0.9
          e:    -75
          g_unit: 0.000183
        SatGABA_B:
          dur_onset:  50.0
          tau_offset: 200.0
          sat: 0.9
          e:   -90
          g_unit: 0.000181
    MOPP: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.02, 0.02]
      mechanisms:
        SatGABA_A:
          dur_onset:   4.2
          tau_offset: 14.0
          sat: 0.9
          e:    -75
          g_unit: 0.0002
    IS:
      type: inhibitory
      sections: [basal, apical]
      layers: [Hilus, Hilus]
      proportions: [0.33, 1.0]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.46
          tau_offset: 4.43
          sat: 0.9
          e: -75
          g_unit: 0.00214
  AAC:
    GC:   
      type: excitatory
      sections: [basal, soma]
      layers: [Hilus, Hilus]
      proportions: [1.0, 1.0]
      mechanisms:
        SatAMPA:
          dur_onset: 0.3
          tau_offset: 6.2
          sat: 0.9
          e: 0
          g_unit: 0.0047
    MPP:
      type: excitatory
      sections: [apical]
      layers: [MML]
      proportions: [1.0]
      mechanisms:
        SatAMPA:
          dur_onset:  0.5
          tau_offset: 3.0
          sat: 0.9
          e:     0
          g_unit: 0.0005
    LPP:
      type: excitatory
      sections: [apical]
      layers: [OML]
      proportions: [1.0]
      mechanisms:
        SatAMPA:
          dur_onset:  0.5
          tau_offset: 3.0
          sat: 0.9
          e:     0
          g_unit: 0.0005
    MC:   
      type: excitatory
      sections: [apical]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        SatAMPA:
          dur_onset: 0.9
          tau_offset: 3.6
          sat: 0.9
          e: 0
          g_unit: 0.0003
    HCC:  
      type: inhibitory
      sections: [apical]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.6
          tau_offset: 4.78
          sat: 0.9
          e: -75
          g_unit: 0.000664
    HC:   
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.96, 0.96]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.46
          tau_offset: 4.43
          sat: 0.9
          e: -75
          g_unit: 0.00214
    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.02, 0.02]
      mechanisms:
        SatGABA_A:
          dur_onset:   4.2
          tau_offset: 14.0
          sat: 0.9
          e:    -75
          g_unit: 0.000183
        SatGABA_B:
          dur_onset:  50.0
          tau_offset: 200.0
          sat: 0.9
          e:   -90
          g_unit: 0.000181
    MOPP: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.02, 0.02]
      mechanisms:
        SatGABA_A:
          dur_onset:   4.2
          tau_offset: 14.0
          sat: 0.9
          e:    -75
          g_unit: 0.0002
    IS:
      type: inhibitory
      sections: [basal, soma]
      layers: [Hilus, Hilus]
      proportions: [1.0, 1.0]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.46
          tau_offset: 4.43
          sat: 0.9
          e: -75
          g_unit: 0.00214
  HCC:
    MPP:
      type: excitatory
      sections: [apical]
      layers: [MML]
      proportions: [1.0]
      mechanisms:
        SatAMPA:
          dur_onset: 0.5
          tau_offset: 5.0
          sat: 0.9
          e: 0
          g_unit: 0.0005
    LPP:
      type: excitatory
      sections: [apical]
      layers: [OML]
      proportions: [1.0]
      mechanisms:
        SatAMPA:
          dur_onset: 0.5
          tau_offset: 5.0
          sat: 0.9
          e: 0
          g_unit: 0.0005
    GC:   
      type: excitatory
      sections: [basal]
      layers: [Hilus]
      proportions: [0.68]
      mechanisms:
        SatAMPA:
          dur_onset: 0.3
          tau_offset: 6.2
          sat: 0.9
          e: 0
          g_unit: 0.0047
    MC:   
      type: excitatory
      sections: [basal, apical]
      layers: [Hilus, IML]
      proportions: [0.32, 1.0]
      mechanisms:
        SatAMPA:
          dur_onset: 0.9
          tau_offset: 3.6
          sat: 0.9
          e: 0
          g_unit: 0.00233
    HCC:  
      type: inhibitory
      sections: [basal, apical]
      layers: [Hilus, IML]
      proportions: [0.3, 1.0]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.72
          tau_offset: 4.7
          sat: 0.9
          e: -75
          g_unit: 0.000325
    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.56, 0.56]
      mechanisms:
        SatGABA_A:
          dur_onset:  4.2
          tau_offset: 16.2
          sat: 0.9
          e: -75
          g_unit: 0.000168
        SatGABA_B:
          dur_onset:  50.0  # https://physoc.onlinelibrary.wiley.com/doi/abs/10.1113/jphysiol.1993.sp019600
          tau_offset: 200.0  # http://www.jneurosci.org/content/33/18/7961
          sat: 0.9
          e: -90
          g_unit: 0.000215
    MOPP: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.44, 0.44]
      mechanisms:
        SatGABA_A:
          dur_onset:  4.2
          tau_offset: 16.2
          sat: 0.9
          e: -75
          g_unit: 0.000168
    IS: 
      type: inhibitory
      sections: [basal, soma]
      layers: [Hilus, Hilus]
      proportions: [0.7, 1.0]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.46
          tau_offset: 4.43
          sat: 0.9
          e: -75
          g_unit: 0.0005
  NGFC:
    MPP:
      type: excitatory
      sections: [basal]
      layers: [MML]
      proportions: [1.0]
      mechanisms:
        SatAMPA:
          dur_onset: 0.5
          tau_offset: 5.0
          sat: 0.9
          e: 0
          g_unit: 0.00025
    LPP:
      type: excitatory
      sections: [apical]
      layers: [OML]
      proportions: [1.0]
      mechanisms:
        SatAMPA:
          dur_onset: 0.5
          tau_offset: 5.0
          sat: 0.9
          e: 0
          g_unit: 0.00033
    HC:  
      type: inhibitory
      sections: [basal, apical]
      layers: [MML, OML]
      proportions: [0.86, 0.86]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.72
          tau_offset: 4.7
          sat: 0.9
          e: -75
          g_unit: 0.000473
    NGFC: 
      type: inhibitory
      sections: [basal, apical]
      layers: [MML, OML]
      proportions: [0.08, 0.08]
      mechanisms:
        SatGABA_A:
          dur_onset:  4.2
          tau_offset: 14.0
          sat: 0.9
          e: -75
          g_unit: 0.000113
        SatGABA_B:
          dur_onset:  50.0
          tau_offset: 200.0
          sat: 0.9
          e: -90
          g_unit: 0.000169
    MOPP: 
      type: inhibitory
      sections: [basal, apical]
      layers: [MML, OML]
      proportions: [0.06, 0.06]
      mechanisms:
        SatGABA_A:
          dur_onset:  4.2
          tau_offset: 14.0
          sat: 0.9
          e: -75
          g_unit: 0.000113
  MOPP:
    MPP:
      type: excitatory
      sections: [basal]
      layers: [MML]
      proportions: [1.0]
      mechanisms:
        SatAMPA:
          dur_onset: 0.5
          tau_offset: 5.0
          sat: 0.9
          e: 0
          g_unit: 0.0010
    LPP:
      type: excitatory
      sections: [apical]
      layers: [OML]
      proportions: [1.0]
      mechanisms:
        SatAMPA:
          dur_onset: 0.5
          tau_offset: 5.0
          sat: 0.9
          e: 0
          g_unit: 0.0010
    MC:   
      type: excitatory
      sections: [basal]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        SatAMPA:
          dur_onset: 0.9
          tau_offset: 3.6
          sat: 0.9
          e: 0
          g_unit: 0.0005
    HC:  
      type: inhibitory
      sections: [basal, apical]
      layers: [MML, OML]
      proportions: [1.0, 0.86]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.72
          tau_offset: 4.7
          sat: 0.9
          e: -75
          g_unit: 0.000473
    HCC:  
      type: inhibitory
      sections: [basal]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.72
          tau_offset: 4.7
          sat: 0.9
          e: -75
          g_unit: 0.000325
    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.56, 0.08]
      mechanisms:
        SatGABA_A:
          dur_onset:  4.2
          tau_offset: 14.0
          sat: 0.9
          e: -75
          g_unit: 0.000113
        SatGABA_B:
          dur_onset:  50.0
          tau_offset: 200.0
          sat: 0.9
          e: -90
          g_unit: 0.000169
    MOPP: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.44, 0.06]
      mechanisms:
        SatGABA_A:
          dur_onset:  4.5
          tau_offset: 13.8
          sat: 0.9
          e: -75
          g_unit: 0.000113
  IS:
    GC:   
      type: excitatory
      sections: [apical]
      layers: [Hilus]
      proportions: [1.0]
      mechanisms:
        SatAMPA:
          dur_onset: 0.3
          tau_offset: 6.2
          sat: 0.9
          e: 0
          g_unit: 0.0005
    IS:   
      type: inhibitory
      sections: [apical, soma]
      layers: [Hilus, Hilus]
      proportions: [1.0, 1.0]
      mechanisms:
        SatGABA_A:
          dur_onset: 0.37
          tau_offset: 10.48
          sat: 0.9
          e: -75
          g_unit: 0.0010
Connection Velocity:
  AAC: 250.0
  BC: 250.0
  HC: 250.0
  HCC: 250.0
  MC: 250.0
  NGFC: 250.0
  MOPP: 250.0
  MPP: 250.0
  LPP: 250.0
  PYR: 250.0
  IS: 250.0
  GC: 250.0
Gap Junctions: !include Gap_Junctions_Control.yaml
