Synapse Mechanisms:
  AMPA: LinExp2Syn
  NMDA: FacilNMDA
  GABA_A: LinExp2Syn
  GABA_B: LinExp2Syn
Synapse Parameter Rules: !include Synapse_Parameter_Rules.yaml
Axon Extent: !include Axon_Extent.yaml      
Synapses:
  GC:
    MPP:
      type: excitatory
      sections: [apical]
      layers: [MML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 5.5
          e: 0
          g_unit: 0.0016
    LPP:
      type: excitatory
      sections: [apical]
      layers: [OML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 5.5
          e: 0
          g_unit: 0.0018
    MC:
      type: excitatory
      sections: [apical]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 5.5
          e: 0
          g_unit: 0.00019
    AAC:
      type: inhibitory
      sections: [ais]
      layers: [GCL]
      proportions: [1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.3
          tau_decay: 2.9
          e: -75
          g_unit: 0.001
    BC:   
      type: inhibitory
      sections: [soma, apical]
      layers: [GCL, IML]
      proportions: [1.0, 0.69]
      mechanisms:
        GABA_A:
          tau_rise: 0.25
          tau_decay: 5.5
          e: -75
          g_unit: 0.00065
    HCC:  
      type: inhibitory
      sections: [apical]
      layers: [IML]
      proportions: [0.31]
      mechanisms:
        GABA_A:
          tau_rise: 0.4
          tau_decay: 1.1
          e: -75
          g_unit: 0.003
    HC:   
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.5, 0.5]
      mechanisms:
        GABA_A:
          tau_rise: 0.5
          tau_decay: 6.0
          e: -75
          g_unit: 0.006
    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.28, 0.28]
      mechanisms:
        GABA_A:
          tau_rise:  0.1
          tau_decay: 10.0
          e:   -75
          g_unit: 0.00015
        GABA_B:
          tau_rise:  50.0
          tau_decay: 200.0
          e:   -90
          g_unit: 0.0001
    MOPP: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.22, 0.22]
      mechanisms:
        GABA_A:
          tau_rise:  0.1
          tau_decay: 10.0
          e:   -75
          g_unit: 0.00015
  MC:
    GC:   
      type: excitatory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.23]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 6.2
          e: 0
          g_unit: 0.0015
    MC:   
      type: excitatory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.77]
      mechanisms:
        AMPA:
          tau_rise: 0.45
          tau_decay: 2.2
          e: 0
          g_unit: 0.0005
    HC:   
      type: inhibitory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.33]
      mechanisms:
        GABA_A:
          tau_rise: 0.5
          tau_decay: 6.0
          e: -75
          g_unit: 0.001
    BC:   
      type: inhibitory
      sections: [soma, apical]
      layers: [Hilus, Hilus]
      proportions: [1.0, 0.17]
      mechanisms:
        GABA_A:
          tau_rise: 0.3
          tau_decay: 3.3
          e: -75
          g_unit: 0.0015
    AAC:  
      type: inhibitory
      sections: [ais]
      layers: [GCL]
      proportions: [1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.3
          tau_decay: 3.3
          e: -75
          g_unit: 0.003
    HCC:  
      type: inhibitory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.5]
      mechanisms:
        GABA_A:
          tau_rise: 0.6
          tau_decay: 4.7
          e: -75
          g_unit: 0.0006
  HC:
    GC:   
      type: excitatory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.72]
      mechanisms:
        AMPA:
          tau_rise: 0.3
          tau_decay: 6.2
          e: 0
          g_unit: 0.0047
    MC:   
      type: excitatory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.28]
      mechanisms:
        AMPA:
          tau_rise: 0.9
          tau_decay: 3.6
          e: 0
          g_unit: 0.0022
    HC:  
      type: inhibitory
      sections: [apical]
      layers: [Hilus]
      proportions: [0.99]
      mechanisms:
        GABA_A:
          tau_rise: 0.37
          tau_decay: 10.48
          e: -75
          g_unit: 0.000623
    IS:  
      type: inhibitory
      sections: [apical, soma]
      layers: [Hilus, Hilus]
      proportions: [0.01, 1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.37
          tau_decay: 10.48
          e: -75
          g_unit: 0.0005
  BC:
    GC:   
      type: excitatory
      sections: [soma, basal]
      layers: [Hilus, Hilus]
      proportions: [1.0, 1.0, 1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.3
          tau_decay: 6.2
          e: 0
          g_unit: 0.0047
    MPP:
      type: excitatory
      sections: [apical]
      layers: [MML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise:  0.5
          tau_decay: 3.0
          e:     0
          g_unit: 0.0005
    LPP:
      type: excitatory
      sections: [apical]
      layers: [OML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise:  0.5
          tau_decay: 3.0
          e:     0
          g_unit: 0.0005
    MC:   
      type: excitatory
      sections: [apical, apical]
      layers: [Hilus, IML]
      proportions: [1.0, 1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.9
          tau_decay: 3.6
          e: 0
          g_unit: 0.0003
    BC:   
      type: inhibitory
      sections: [basal, soma]
      layers: [Hilus, Hilus]
      proportions: [0.67, 1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.22
          tau_decay: 3.35
          e: -75
          g_unit: 0.00427
    HCC:  
      type: inhibitory
      sections: [apical]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.6
          tau_decay: 4.78
          e: -75
          g_unit: 0.000664
    HC:   
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.96, 0.96]
      mechanisms:
        GABA_A:
          tau_rise: 0.46
          tau_decay: 4.43
          e: -75
          g_unit: 0.00214
    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.02, 0.02]
      mechanisms:
        GABA_A:
          tau_rise:   4.2
          tau_decay: 14.0
          e:    -75
          g_unit: 0.000183
        GABA_B:
          tau_rise:  50.0
          tau_decay: 200.0
          e:   -90
          g_unit: 0.000181
    MOPP: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.02, 0.02]
      mechanisms:
        GABA_A:
          tau_rise:   4.2
          tau_decay: 14.0
          e:    -75
          g_unit: 0.0002
    IS:
      type: inhibitory
      sections: [basal, apical]
      layers: [Hilus, Hilus]
      proportions: [0.33, 1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.46
          tau_decay: 4.43
          e: -75
          g_unit: 0.00214
  AAC:
    GC:   
      type: excitatory
      sections: [basal, soma]
      layers: [Hilus, Hilus]
      proportions: [1.0, 1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.3
          tau_decay: 6.2
          e: 0
          g_unit: 0.0047
    MPP:
      type: excitatory
      sections: [apical]
      layers: [MML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise:  0.5
          tau_decay: 3.0
          e:     0
          g_unit: 0.0005
    LPP:
      type: excitatory
      sections: [apical]
      layers: [OML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise:  0.5
          tau_decay: 3.0
          e:     0
          g_unit: 0.0005
    MC:   
      type: excitatory
      sections: [apical]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.9
          tau_decay: 3.6
          e: 0
          g_unit: 0.0003
    HCC:  
      type: inhibitory
      sections: [apical]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.6
          tau_decay: 4.78
          e: -75
          g_unit: 0.000664
    HC:   
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.96, 0.96]
      mechanisms:
        GABA_A:
          tau_rise: 0.46
          tau_decay: 4.43
          e: -75
          g_unit: 0.00214
    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.02, 0.02]
      mechanisms:
        GABA_A:
          tau_rise:   4.2
          tau_decay: 14.0
          e:    -75
          g_unit: 0.000183
        GABA_B:
          tau_rise:  50.0
          tau_decay: 200.0
          e:   -90
          g_unit: 0.000181
    MOPP: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.02, 0.02]
      mechanisms:
        GABA_A:
          tau_rise:   4.2
          tau_decay: 14.0
          e:    -75
          g_unit: 0.0002
    IS:
      type: inhibitory
      sections: [basal, soma]
      layers: [Hilus, Hilus]
      proportions: [1.0, 1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.46
          tau_decay: 4.43
          e: -75
          g_unit: 0.00214
  HCC:
    MPP:
      type: excitatory
      sections: [apical]
      layers: [MML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 5.0
          e: 0
          g_unit: 0.0005
    LPP:
      type: excitatory
      sections: [apical]
      layers: [OML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 5.0
          e: 0
          g_unit: 0.0005
    GC:   
      type: excitatory
      sections: [basal]
      layers: [Hilus]
      proportions: [0.68]
      mechanisms:
        AMPA:
          tau_rise: 0.3
          tau_decay: 6.2
          e: 0
          g_unit: 0.0047
    MC:   
      type: excitatory
      sections: [basal, apical]
      layers: [Hilus, IML]
      proportions: [0.32, 1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.9
          tau_decay: 3.6
          e: 0
          g_unit: 0.00233
    HCC:  
      type: inhibitory
      sections: [basal, apical]
      layers: [Hilus, IML]
      proportions: [0.3, 1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.72
          tau_decay: 4.7
          e: -75
          g_unit: 0.000325
    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.56, 0.56]
      mechanisms:
        GABA_A:
          tau_rise:  4.2
          tau_decay: 16.2
          e: -75
          g_unit: 0.000168
        GABA_B:
          tau_rise:  50.0  # https://physoc.onlinelibrary.wiley.com/doi/abs/10.1113/jphysiol.1993.sp019600
          tau_decay: 200.0  # http://www.jneurosci.org/content/33/18/7961
          e: -90
          g_unit: 0.000215
    MOPP: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.44, 0.44]
      mechanisms:
        GABA_A:
          tau_rise:  4.2
          tau_decay: 16.2
          e: -75
          g_unit: 0.000168
    IS: 
      type: inhibitory
      sections: [basal, soma]
      layers: [Hilus, Hilus]
      proportions: [0.7, 1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.46
          tau_decay: 4.43
          e: -75
          g_unit: 0.0005
  NGFC:
    MPP:
      type: excitatory
      sections: [basal]
      layers: [MML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 5.0
          e: 0
          g_unit: 0.00025
    LPP:
      type: excitatory
      sections: [apical]
      layers: [OML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 5.0
          e: 0
          g_unit: 0.00033
    HC:  
      type: inhibitory
      sections: [basal, apical]
      layers: [MML, OML]
      proportions: [0.86, 0.86]
      mechanisms:
        GABA_A:
          tau_rise: 0.72
          tau_decay: 4.7
          e: -75
          g_unit: 0.000473
    NGFC: 
      type: inhibitory
      sections: [basal, apical]
      layers: [MML, OML]
      proportions: [0.08, 0.08]
      mechanisms:
        GABA_A:
          tau_rise:  4.2
          tau_decay: 14.0
          e: -75
          g_unit: 0.000113
        GABA_B:
          tau_rise:  50.0
          tau_decay: 200.0
          e: -90
          g_unit: 0.000169
    MOPP: 
      type: inhibitory
      sections: [basal, apical]
      layers: [MML, OML]
      proportions: [0.06, 0.06]
      mechanisms:
        GABA_A:
          tau_rise:  4.2
          tau_decay: 14.0
          e: -75
          g_unit: 0.000113
  MOPP:
    MPP:
      type: excitatory
      sections: [basal]
      layers: [MML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 5.0
          e: 0
          g_unit: 0.0010
    LPP:
      type: excitatory
      sections: [apical]
      layers: [OML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 5.0
          e: 0
          g_unit: 0.0010
    MC:   
      type: excitatory
      sections: [basal]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.9
          tau_decay: 3.6
          e: 0
          g_unit: 0.0005
    HC:  
      type: inhibitory
      sections: [basal, apical]
      layers: [MML, OML]
      proportions: [1.0, 0.86]
      mechanisms:
        GABA_A:
          tau_rise: 0.72
          tau_decay: 4.7
          e: -75
          g_unit: 0.000473
    HCC:  
      type: inhibitory
      sections: [basal]
      layers: [IML]
      proportions: [1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.72
          tau_decay: 4.7
          e: -75
          g_unit: 0.000325
    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.56, 0.08]
      mechanisms:
        GABA_A:
          tau_rise:  4.2
          tau_decay: 14.0
          e: -75
          g_unit: 0.000113
        GABA_B:
          tau_rise:  50.0
          tau_decay: 200.0
          e: -90
          g_unit: 0.000169
    MOPP: 
      type: inhibitory
      sections: [apical, apical]
      layers: [MML, OML]
      proportions: [0.44, 0.06]
      mechanisms:
        GABA_A:
          tau_rise:  4.5
          tau_decay: 13.8
          e: -75
          g_unit: 0.000113
  IS:
    GC:   
      type: excitatory
      sections: [apical]
      layers: [Hilus]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.3
          tau_decay: 6.2
          e: 0
          g_unit: 0.0005
    IS:   
      type: inhibitory
      sections: [apical, soma]
      layers: [Hilus, Hilus]
      proportions: [1.0, 1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.37
          tau_decay: 10.48
          e: -75
          g_unit: 0.0010
Connection Velocity: !include Connection_Velocity.yaml
Gap Junctions: !include Gap_Junctions_Control.yaml
