## Model configuration of dentate gyrus network
Model Name: dentatenet
Dataset Name: Small_Scale
Definitions: !include Definitions.yaml
Geometry: !include Geometry.yaml
Random Seeds: !include Random.yaml
Cell Data: dentatenet_Full_Scale_GC_Exc_Sat_SLN_extent_arena_margin_20201001_compressed.h5
Connection Data: dentatenet_Full_Scale_GC_Exc_Sat_SLN_extent_arena_margin_20201001_compressed.h5
Connection Generator: !include Small_Scale_Connections_tune_GC_synapses.yaml
Recording: !include Recording.yaml
## Cell types for dentate gyrus model
Cell Types: 
  GC:
    template: DGC
    template file: DGC_Template_minimal.hoc
    mechanism file: 20190205_DG_GC_tuned_NMDA_mech.yaml
    synapses:
      correct_for_spines: True
      weights: !include GC_SLN_weights.yaml
      density: !include GC_synapse_density.yaml
  MC:
    template: MossyCell
    synapses:
      density: !include MC_synapse_density.yaml
  HC:
    template: HIPPCell
    synapses:
      density: !include HC_synapse_density.yaml
  BC:
    template: BasketCell
    synapses:
      density: !include BC_synapse_density.yaml
  AAC:
    template: AxoAxonicCell
    synapses:
      density: !include AAC_synapse_density.yaml
  HCC:
    template: HICAPCell
    synapses: !include HCC_synapse_density.yaml
  NGFC:
    template: NGFCell
    synapses:
      density: !include NGFC_synapse_density.yaml
  MOPP:
    template: MOPPCell
    synapses:
      density: !include NGFC_synapse_density.yaml
  IS:
    template: ISCell
    synapses:
      density: !include IS_synapse_density.yaml
  MPP:
    template: MPPCell
    Vector Stimulus: Vector Stimulus 0
  LPP:
    template: LPPCell
    Vector Stimulus: Vector Stimulus 0

