Synapse Mechanisms:
  AMPA: SatExp2Syn
  NMDA: FacilNMDA
  GABA_A: SatExp2Syn
  GABA_B: SatExp2Syn
Synapse Parameter Rules:
  LinExp2Syn:
    mech_file: lin_exp2syn.mod
    mech_params:
      - tau_rise
      - tau_decay
      - e
    netcon_params:
      weight: 0
      g_unit: 1
  SatExp2Syn:
    mech_file: sat_exp2syn.mod
    mech_params:
      - sat
      - dur_onset
      - tau_offset
      - e
    netcon_params:
      weight: 0
      g_unit: 1
  FacilExp2Syn:
    mech_file: facil_exp2syn.mod
    mech_params:
      - sat
      - dur_onset
      - tau_offset
      - e
      - f_inc
      - f_max
      - f_tau
    netcon_params:
      weight: 0
      g_unit: 1
  FacilNMDA:
    mech_file: facil_NMDA.mod
    mech_params:
      - sat
      - dur_onset
      - tau_offset
      - e
      - f_inc
      - f_max
      - f_tau
      - mg
      - Kd
      - gamma
    netcon_params:
      weight: 0
      g_unit: 1
  Exp2Syn:
    mech_file: exp2syn.mod
    mech_params:
      - tau1
      - tau2
      - e
    netcon_params:
      weight: 0
# full width in um [S-T, M-L]
Axon Width:
  GC:   [900., 900.]
  MPP:  [1500., 3000.]
  LPP:  [1500., 3000.]
  MC:   [4000., 4000.]
  NGFC: [2000., 2000.]
  AAC:  [1700., 1100.]
  BC:   [1700., 1000.]
  HCC:  [2600., 2600.]
  HC:   [3000., 3000.]
  IS:   [3000., 3000.]
  MOPP: [2000., 2000.]
Axon Offset:
  MC:   [1000., 1000.]
  GC:   [0., 0.]
  MPP:  [0., 0.]
  LPP:  [0., 0.]
  NGFC: [0., 0.]
  AAC:  [0., 0.]
  BC:   [0., 0.]
  HCC:  [0., 0.]
  HC:   [0., 0.]
  IS:   [0., 0.]
  MOPP: [0., 0.]
Axon Standard Deviation:
  GC:   0.4
  MC:   0.515
  NGFC: 0.45
  AAC:  0.45
  BC:   0.45
  HCC:  0.45
  HC:   0.45
  IS:   0.45
  MOPP: 0.45
  MPP:  1.0
  LPP:  1.0
Synapse Types:
  GC:
    MPP:  [excitatory]
    LPP:  [excitatory]
    MC:   [excitatory]
    NGFC: [inhibitory]
    AAC:  [inhibitory]
    BC:   [inhibitory]
    HCC:  [inhibitory]
    HC:   [inhibitory]
    MOPP: [inhibitory]
  MC:
    GC:   [excitatory]
    MC:   [excitatory]
    HC:   [inhibitory]
    BC:   [inhibitory]
    AAC:  [inhibitory]
    HCC:  [inhibitory]
  HC:
    GC:  [excitatory]
    MC:  [excitatory]
    HC:  [inhibitory]
    IS:  [inhibitory]
  BC:
    GC:   [excitatory]
    MC:   [excitatory]
    HC:   [inhibitory]
    BC:   [inhibitory]
    HCC:  [inhibitory]
    NGFC: [inhibitory]
    MOPP: [inhibitory]
    IS:   [inhibitory]
    MPP:  [excitatory]
    LPP:  [excitatory]
  AAC:
    GC:   [excitatory]
    MC:   [excitatory]
    HCC:  [inhibitory]
  HCC:
    GC:   [excitatory]
    MC:   [excitatory]
    HCC:  [inhibitory]
    NGFC: [inhibitory]
    MOPP: [inhibitory]
    IS:   [inhibitory]
    MPP:  [excitatory]
    LPP:  [excitatory]
  NGFC:
    HC:   [inhibitory]
    NGFC: [inhibitory]
    MOPP: [inhibitory]
    MPP:  [excitatory]
    LPP:  [excitatory]
  MOPP:
    MC:   [excitatory]
    MOPP: [inhibitory]
    NGFC: [inhibitory]
    HC:   [inhibitory]
    HCC:  [inhibitory]
    MPP:  [excitatory]
    LPP:  [excitatory]
  IS:
    GC:   [excitatory]
    IS:   [inhibitory]
Synapse Locations:
  GC:
    MPP:  [apical]
    LPP:  [apical]
    MC:   [apical]
    NGFC: [apical, apical]
    AAC:  [ais]
    BC:   [soma, apical]
    MOPP: [apical, apical]
    HCC:  [apical]
    HC:   [apical, apical]
  MC:
    GC:   [apical]
    MC:   [apical]
    HC:   [apical]
    BC:   [soma, apical]
    AAC:  [ais]
    HCC:  [apical]
  HC:
    GC:   [apical, basal]
    MC:   [apical, basal]
    HC:   [apical, basal]
    BC:   [apical, basal]
    IS:   [apical, soma, basal]
  BC:
    GC:   [basal, basal]
    MC:   [apical]
    HC:   [apical, apical]
    BC:   [basal, soma]
    HCC:  [apical]
    NGFC: [apical, apical]
    MOPP: [apical, apical]
    IS:   [basal]
    MPP:  [apical]
    LPP:  [apical]
  AAC:
    GC:   [basal, basal]
    MC:   [apical]
    HCC:  [apical]
  HCC:
    GC:   [basal]
    MC:   [basal]
    HCC:  [basal, apical]
    NGFC: [apical, apical]
    MOPP: [apical, apical]
    IS:   [basal, soma]
    MPP:  [apical]
    LPP:  [apical]
  NGFC:
    HC:   [basal, apical]
    NGFC: [basal, apical]
    MOPP: [basal, apical]
    MPP:  [basal]
    LPP:  [apical]
  MOPP:
    MC:   [basal]
    MPP:  [basal]
    LPP:  [apical]
    HC:   [basal, apical]
    HCC:  [basal]
    MOPP: [basal, apical]
    NGFC: [basal, apical]
  IS:
    GC:   [apical, basal]
    IS:   [apical, soma, basal]
Synapse Layers:
  GC:
    MPP:  [MML]
    LPP:  [OML]
    MC:   [IML]
    AAC:  [GCL]
    BC:   [GCL, IML]
    NGFC: [MML, OML]
    MOPP: [MML, OML]
    HC:   [MML, OML]
    HCC:  [IML]
  MC:
    GC:  [Hilus]
    MC:  [Hilus]
    HC:  [Hilus]
    BC:  [Hilus, Hilus]
    AAC: [Hilus]
    HCC: [Hilus]
  HC:
    GC:  [Hilus, Hilus]
    MC:  [Hilus, Hilus]
    HC:  [Hilus, Hilus]
    IS:  [Hilus, Hilus, Hilus]
  BC:
    GC:   [Hilus, GCL]
    MC:   [IML]
    HC:   [MML, OML]
    BC:   [GCL, GCL]
    HCC:  [IML]
    NGFC: [MML, OML]
    MOPP: [MML, OML]
    IS:   [Hilus]
    MPP:  [MML]
    LPP:  [OML]
  AAC:
    GC:   [Hilus, GCL]
    MC:   [GCL]
    HCC:  [IML]
  HCC:
    GC:   [Hilus]
    MC:   [Hilus]
    HCC:  [Hilus, IML]
    NGFC: [MML, OML]
    MOPP: [MML, OML]
    IS:   [Hilus, Hilus]
    MPP:  [MML]
    LPP:  [OML]
  NGFC:
    HC:   [MML, OML]
    NGFC: [MML, OML]
    MOPP: [MML, OML]
    MPP:  [MML]
    LPP:  [OML]
  MOPP:
    MC:   [IML]
    MOPP: [MML, OML]
    NGFC: [MML, OML]
    HC:   [MML, OML]
    HCC:  [IML]
    MPP:  [MML]
    LPP:  [OML]
  IS:
    GC:   [Hilus, Hilus]
    IS:   [Hilus, Hilus, Hilus]
Synapse Proportions:
  GC:
    MPP:  [1.]
    LPP:  [1.]
    MC:   [1.]
    AAC:  [1.]
    BC:   [1., 0.1]
    NGFC: [0.15, 0.15]
    MOPP: [0.3, 0.3]
    HC:   [0.55, 0.55]
    HCC:  [0.9]
  MC:
    GC:  [0.23]
    MC:  [0.77]
    HC:  [0.33]
    BC:  [1., 0.33]
    AAC: [1.]
    HCC: [0.34]
  HC:
    MC:  [0.5, 0.5]
    GC:  [0.5, 0.5]
    HC:  [0.75, 0.75]
    IS:  [0.25, 1., 0.25]
  BC:
    GC:   [1., 1.]
    MC:   [1.]
    MPP:  [1.0]
    LPP:  [1.0]
    BC:   [1.0, 1.0]
    HCC:  [1.0]
    HC:   [0.34, 0.34]
    NGFC: [0.33, 0.33]
    MOPP: [0.33, 0.33]
    IS:   [1.0]
  AAC:
    GC:   [1.0, 1.0]
    MC:   [1.0]
    HCC:   [1.0]
  HCC:
    GC:   [0.5]
    MC:   [0.5]
    HCC:  [0.5, 1.0]
    NGFC: [0.5, 0.5]
    MOPP: [0.5, 0.5]
    IS:   [0.5, 1.0]
    MPP:  [1.0]
    LPP:  [1.0]
  NGFC:
    HC:   [0.34, 0.34]
    NGFC: [0.33, 0.33]
    MOPP: [0.33, 0.33]
    MPP:  [1.0]
    LPP:  [1.0]
  MOPP:
    MC:   [1.0]
    HC:   [0.34, 0.34]
    NGFC: [0.33, 0.33]
    MOPP: [0.33, 0.33]
    HCC:  [1.0]
    MPP:  [1.0]
    LPP:  [1.0]
  IS:
    GC:   [1.0. 1.0, 1.0]
    IS:   [1.0, 1.0]
Synapse Parameters:
  GC:
    MC:
      AMPA:
        dur_onset: 0.5
        tau_offset: 5.5
        sat: 0.9
        e: 0
        g_unit: 0.00019
    MPP:
      AMPA:
        dur_onset: 0.5
        tau_offset: 5.5
        sat: 0.9
        e: 0
        g_unit: 0.0016
    LPP:
      AMPA:
        dur_onset: 0.5
        tau_offset: 5.5
        sat: 0.9
        e: 0
        g_unit: 0.0018
    HC:
      GABA_A:
        dur_onset: 0.5
        tau_offset: 6.0
        sat: 0.9
        e: -75
        g_unit: 0.006
    BC:
      GABA_A:
        dur_onset: 0.25
        tau_offset: 5.5
        sat: 0.9
        e: -75
        g_unit: 0.00065
    AAC:
      GABA_A:
        dur_onset: 0.3
        tau_offset: 2.9
        sat: 0.9
        e: -75
        g_unit: 0.001
    HCC:
      GABA_A:
        dur_onset: 0.4
        tau_offset: 1.1
        sat: 0.9
        e: -75
        g_unit: 0.003
    NGFC:
      GABA_A:
        dur_onset:  0.1
        tau_offset: 10.0
        sat: 0.9
        e:   -75
        g_unit: 0.00015
      GABA_B:
        dur_onset:  50.0
        tau_offset: 200.0
        sat: 0.9
        e:   -90
        g_unit: 0.0001
    MOPP:
      GABA_A:
        dur_onset:  0.1
        tau_offset: 10.0
        sat: 0.9
        e:   -75
        g_unit: 0.00015
  MC:
    GC:
      AMPA:
        dur_onset: 0.5
        tau_offset: 6.2
        sat: 0.9
        e: 0
        g_unit: 0.0015
    MC:
      AMPA:
        dur_onset: 0.45
        tau_offset: 2.2
        sat: 0.9
        e: 0
        g_unit: 0.0005
    HC:
      GABA_A:
        dur_onset: 0.5
        tau_offset: 6.0
        sat: 0.9
        e: -75
        g_unit: 0.001
    BC:
      GABA_A:
        dur_onset: 0.3
        tau_offset: 3.3
        sat: 0.9
        e: -75
        g_unit: 0.0015
    AAC:
      GABA_A:
        dur_onset: 0.3
        tau_offset: 3.3
        sat: 0.9
        e: -75
        g_unit: 0.003
    HCC:
      GABA_A:
        dur_onset: 0.6
        tau_offset: 4.7
        sat: 0.9
        e: -75
        g_unit: 0.0006
  HC:
    GC:
      AMPA:
        dur_onset: 0.3
        tau_offset: 6.2
        sat: 0.9
        e: 0
        g_unit: 0.0047
    MC:
      AMPA:
        dur_onset: 0.9
        tau_offset: 3.6
        sat: 0.9
        e: 0
        g_unit: 0.0022
    HC:
      GABA_A:
        dur_onset: 0.37
        tau_offset: 10.48
        sat: 0.9
        e: -75
        g_unit: 0.000623
    IS:
      GABA_A:
        dur_onset: 0.37
        tau_offset: 10.48
        sat: 0.9
        e: -75
        g_unit: 0.0005
  BC:
    GC:
      AMPA:
        dur_onset: 0.3
        tau_offset: 6.2
        sat: 0.9
        e: 0
        g_unit: 0.0047
    MC:
      AMPA:
        dur_onset: 0.9
        tau_offset: 3.6
        sat: 0.9
        e: 0
        g_unit: 0.0003
    MPP:
      AMPA:
        dur_onset:  0.5
        tau_offset: 3.0
        sat: 0.9
        e:     0
        g_unit: 0.0005
    LPP:
      AMPA:
        dur_onset:  0.5
        tau_offset: 3.0
        sat: 0.9
        e:     0
        g_unit: 0.0005
    HC:
      GABA_A:
        dur_onset: 0.46
        tau_offset: 4.43
        sat: 0.9
        e: -75
        g_unit: 0.00214
    BC:
      GABA_A:
        dur_onset: 0.22
        tau_offset: 3.35
        sat: 0.9
        e: -75
        g_unit: 0.00427
    HCC:
      GABA_A:
        dur_onset: 0.6
        tau_offset: 4.78
        sat: 0.9
        e: -75
        g_unit: 0.000664
    NGFC:
      GABA_A:
        dur_onset:   4.2
        tau_offset: 14.0
        sat: 0.9
        e:    -75
        g_unit: 0.000183
      GABA_B:
        dur_onset:  50.0
        tau_offset: 200.0
        sat: 0.9
        e:   -90
        g_unit: 0.000181
    MOPP:
      GABA_A:
        dur_onset:   4.2
        tau_offset: 14.0
        sat: 0.9
        e:    -75
        g_unit: 0.0002
    IS:
      GABA_A:
        dur_onset: 0.46
        tau_offset: 4.43
        sat: 0.9
        e: -75
        g_unit: 0.00214
  AAC:
    GC:
      AMPA:
        dur_onset: 0.3
        tau_offset: 6.2
        sat: 0.9
        e: 0
        g_unit: 0.0047
    MC:
      AMPA:
        dur_onset: 0.9
        tau_offset: 3.6
        sat: 0.9
        e: 0
        g_unit: 0.0003
    HCC:
      GABA_A:
        dur_onset: 0.6
        tau_offset: 4.78
        sat: 0.9
        e: -75
        g_unit: 0.000664
  HCC:
    GC:
      AMPA:
        dur_onset: 0.3
        tau_offset: 6.2
        sat: 0.9
        e: 0
        g_unit: 0.0047
    MC:
      AMPA:
        dur_onset: 0.9
        tau_offset: 3.6
        sat: 0.9
        e: 0
        g_unit: 0.0023
    HCC:
      GABA_A:
        dur_onset: 0.72
        tau_offset: 4.7
        sat: 0.9
        e: -75
        g_unit: 0.000325
    IS:
      GABA_A:
        dur_onset: 0.46
        tau_offset: 4.43
        sat: 0.9
        e: -75
        g_unit: 0.0005
    MOPP:
      GABA_A:
        dur_onset:  4.2
        tau_offset: 16.2
        sat: 0.9
        e: -75
        g_unit: 0.000168
    NGFC:
      GABA_A:
        dur_onset:  4.2
        tau_offset: 16.2
        sat: 0.9
        e: -75
        g_unit: 0.000168
      GABA_B:
        dur_onset:  50.0  # https://physoc.onlinelibrary.wiley.com/doi/abs/10.1113/jphysiol.1993.sp019600
        tau_offset: 200.0  # http://www.jneurosci.org/content/33/18/7961
        sat: 0.9
        e: -90
        g_unit: 0.000215
    MPP:
      AMPA:
        dur_onset: 0.5
        tau_offset: 5.0
        sat: 0.9
        e: 0
        g_unit: 0.0005
    LPP:
      AMPA:
        dur_onset: 0.5
        tau_offset: 5.0
        sat: 0.9
        e: 0
        g_unit: 0.0005
  NGFC:
    MPP:
      AMPA:
        dur_onset: 0.5
        tau_offset: 5.0
        sat: 0.9
        e: 0
        g_unit: 0.00025
    LPP:
      AMPA:
        dur_onset: 0.5
        tau_offset: 5.0
        sat: 0.9
        e: 0
        g_unit: 0.00033
    HC:
      GABA_A:
        dur_onset: 0.72
        tau_offset: 4.7
        sat: 0.9
        e: -75
        g_unit: 0.000473
    MOPP:
      GABA_A:
        dur_onset:  4.2
        tau_offset: 14.0
        sat: 0.9
        e: -75
        g_unit: 0.000113
    NGFC:
      GABA_A:
        dur_onset:  4.2
        tau_offset: 14.0
        sat: 0.9
        e: -75
        g_unit: 0.000113
      GABA_B:
        dur_onset:  50.0
        tau_offset: 200.0
        sat: 0.9
        e: -90
        g_unit: 0.000169
  MOPP:
    MPP:
      AMPA:
        dur_onset: 0.5
        tau_offset: 5.0
        sat: 0.9
        e: 0
        g_unit: 0.0010
    LPP:
      AMPA:
        dur_onset: 0.5
        tau_offset: 5.0
        sat: 0.9
        e: 0
        g_unit: 0.0010
    MC:
      AMPA:
        dur_onset: 0.9
        tau_offset: 3.6
        sat: 0.9
        e: 0
        g_unit: 0.0005
    HC:
      GABA_A:
        dur_onset: 0.72
        tau_offset: 4.7
        sat: 0.9
        e: -75
        g_unit: 0.000473
    HCC:
      GABA_A:
        dur_onset: 0.72
        tau_offset: 4.7
        sat: 0.9
        e: -75
        g_unit: 0.000325
    NGFC:
      GABA_A:
        dur_onset:  4.2
        tau_offset: 14.0
        sat: 0.9
        e: -75
        g_unit: 0.000113
      GABA_B:
        dur_onset:  50.0
        tau_offset: 200.0
        sat: 0.9
        e: -90
        g_unit: 0.000169
    MOPP:
      GABA_A:
        dur_onset:  4.5
        tau_offset: 13.8
        sat: 0.9
        e: -75
        g_unit: 0.000113
  IS:
    GC:
      AMPA:
        dur_onset: 0.3
        tau_offset: 6.2
        sat: 0.9
        e: 0
        g_unit: 0.0005
    IS:
      GABA_A:
        dur_onset: 0.37
        tau_offset: 10.48
        sat: 0.9
        e: -75
        g_unit: 0.0010
Connection Velocity:
  AAC: 250.0
  BC: 250.0
  HC: 250.0
  HCC: 250.0
  MC: 250.0
  NGFC: 250.0
  MOPP: 250.0
  MPP: 250.0
  LPP: 250.0
  IS: 250.0
  GC: 250.0
Gap Junctions:
  Locations:
    BC:
      AAC: [apical, basal]
      BC: [apical, basal]
    AAC:
      AAC: [apical, basal]
    HCC:
      HCC: [apical, basal]
    HC: 
      HC: [apical, basal]
    IS: 
      HC: [apical, basal]
      IS: [apical, basal]
    NGFC:
      NGFC: [apical]
    MOPP:
      MOPP: [apical, basal]
  Connection Probabilities:
    AAC, BC, HC, IS, HCC, NGFC, MOPP:
      - [0.286, 0.0,   0.0,  0.0,  0.0,   0.0,   0.0]
      - [0.286, 0.286, 0.0,  0.0,  0.0,   0.0,   0.0]
      - [0.0,   0.0,   0.19, 0.0,  0.0,   0.0,   0.0]
      - [0.0,   0.0,   0.19, 0.19, 0.0,   0.0,   0.0]
      - [0.0,   0.0,   0.0,  0.0,  0.085, 0.0,   0.0]
      - [0.786, 0.786, 0.0,  0.0,  0.786, 0.786, 0.0]
      - [0.786, 0.786, 0.0,  0.0,  0.786, 0.786, 0.786]
  ## Distance-dependent connection weights,
  ## based on Fig. 1C from Otsuka 2013
  Connection Weights: { 0: 1.0, 25: 0.429, 75: 0.405, 125: 0.345, 175: 0.08 }
  Connection Parameters: [0.4201,-0.0019,150.7465,0.0255]
  Coupling Coefficients:
    AAC:
      AAC: 0.017
    BC:
      BC: 0.017
    HC:
      HC: 0.13
    HCC:
      HCC: 0.04
    NGFC:
      NGFC: 0.0385
    MOPP:
      MOPP: 0.0385
  ## Distance-dependent coupling coefficient weights,
  ## Based on Fig. 6B from Amitai 2002
  Coupling Weights: { 0: 1.0, 25: 0.5, 75: 0.375, 125: 0.1875, 175: 0.1875 }
  Coupling Parameters: [0.0002,-0.0658,7.3211]
