## Model configuration of dentate gyrus network
Model Name: dentatenet
Dataset Name: Small_Scale
Definitions: !include Definitions.yaml
Geometry: !include Geometry.yaml
Random Seeds: !include Random.yaml
Cell Data: GC_MC_BC_trees_syns_connections_20181126.h5  # MC_BC_trees_syns_20180817.h5
Connection Data: GC_MC_BC_trees_syns_connections_20181126.h5  # MC_BC_connections_20180905.h5
Connection Generator: !include Small_Scale_Connections_tune_GC_synapses.yaml
LFP: !include LFP.yaml
Input: !include Input.yaml
## Cell types for dentate gyrus model
Cell Types: 
  GC:
    template: DGC
    templateFile: DGC_Template_minimal.hoc
    mech_file: 20181205_DG_GC_excitability_mech.yaml
    synapses:
      correct_for_spines: True
      weights: True
      weights namespace: Log-Normal Weights
      density: !include GC_synapse_density.yaml
  MC:
    template: MossyCell
    templateFile: MossyCell_minimal.hoc
    synapses:
      weights: False
      density: !include MC_synapse_density.yaml
  HC:
    template: HIPPCell
    synapses:
      density: !include HC_synapse_density.yaml
  BC:
    template: BasketCell
    templateFile: BasketCell_minimal.hoc
    mech_file: 20180831_BC_mech.yaml
    synapses:
      density: !include BC_synapse_density.yaml
  AAC:
    template: AxoAxonicCell
    synapses:
      density: !include AAC_synapse_density.yaml
  HCC:
    template: HICAPCell
    synapses: !include HCC_synapse_density.yaml
  NGFC:
    template: NGFCell
    synapses:
      density: !include NGFC_synapse_density.yaml
  MOPP:
    template: MOPPCell
    synapses:
      density: !include NGFC_synapse_density.yaml
  IS:
    template: ISCell
    synapses:
      density: !include IS_synapse_density.yaml
  MPP:
    template: MPPCell
    Vector Stimulus: Vector Stimulus 0
  LPP:
    template: LPPCell
    Vector Stimulus: Vector Stimulus 0

