SatExp2Syn:
    mech_file: sat_exp2syn.mod
    mech_params:
      - sat
      - dur_onset
      - tau_offset
      - e
    netcon_params:
      weight: 0
      g_unit: 1
    netcon_state:
      onset: 2
      count: 3
      g0: 4
      t0: 5
FacilExp2Syn:
    mech_file: facil_exp2syn.mod
    mech_params:
      - sat
      - dur_onset
      - tau_offset
      - e
      - f_inc
      - f_max
      - f_tau
    netcon_params:
      weight: 0
      g_unit: 1
    netcon_state:
      onset: 2
      count: 3
      g0: 4
      f0: 5
      f1: 6
      t0: 7
FacilNMDA:
    mech_file: facil_NMDA.mod
    mech_params:
      - sat
      - dur_onset
      - tau_offset
      - e
      - f_inc
      - f_max
      - f_tau
      - mg
      - Kd
      - gamma
      - vshift
    netcon_params:
      weight: 0
      g_unit: 1
    netcon_state:
      onset: 2
      count: 3
      g0: 4
      f0: 5
      f1: 6
      t0: 7
Exp2Syn:
    mech_file: exp2syn.mod
    mech_params:
      - tau1
      - tau2
      - e
    netcon_params:
      weight: 0
    netcon_state: {}
LinExp2Syn:
    mech_file: lin_exp2syn.mod
    mech_params:
      - tau_rise
      - tau_decay
      - e
    netcon_params:
      weight: 0
      g_unit: 1
    netcon_state: {}
LinExp2SynNMDA:
    mech_file: lin_exp2synNMDA.mod
    mech_params:
      - tau_rise
      - tau_decay
      - e
      - mg
      - Kd
      - gamma
      - vshift
    netcon_params:
      weight: 0
      g_unit: 1
    netcon_state: {}
Exp5NMDA:
    mech_file: SynExp5NMDA.mod
    mech_params:
      - gVI
      - tauV
      - tau1
      - tau2_0
      - tau3_0
      - wtau2
      - tau_D1
      - a2
      - b2
      - a3
      - b3
      - K0
      - delta
    netcon_params:
      weight: 0
    netcon_state: {}
Exp5NMDA:
    mech_file: SynExp5NMDA.mod
    mech_params:
      - gVI
      - tauV
      - tau1
      - tau2_0
      - tau3_0
      - wtau2
      - tau_D1
      - a2
      - b2
      - a3
      - b3
      - K0
      - delta
    netcon_params:
      weight: 0
    netcon_state:
      D1: 1
      tsyn: 2
Exp3NMDA:
    mech_file: SynExp3NMDA.mod
    mech_params:
      - gVI
      - tau1
      - tau2
      - K0
      - delta
    netcon_params:
      weight: 0
    netcon_state: {}
Exp3NMDA2:
    mech_file: SynExp3NMDA2.mod
    mech_params:
      - gVI
      - tau1_0
      - tau2_0
      - a1
      - b1
      - a2
      - b2
      - tauV
      - K0
      - delta
    netcon_params:
      weight: 0
    netcon_state: {}
Exp3NMDA2fd:
    mech_file: SynExp3NMDA2fd.mod
    mech_params:
      - gVI
      - tau1_0
      - tau2_0
      - a1
      - b1
      - a2
      - b2
      - tauV
      - K0
      - delta_D
      - delta_F
      - tau_D1
      - tau_F
    netcon_params:
      weight: 0
      g_unit: 1
    netcon_state:
      wf: 2
      f:  3
      d1: 4
      t0: 5
EPSC:
    mech_file: exp2EPSC.mod
    mech_params:
      - tau_rise
      - tau_decay
      - i_unit
    netcon_params:
      weight: 0
AMPA_KIN:
    mech_file: ampa_kin.mod
    mech_params:
      - gmax
    netcon_params:
      weight: 0
NMDA_KIN5:
    mech_file: nmda_kin5.mod
    mech_params:
      - gmax
    netcon_params:
      weight: 0
