## Model configuration of dentate gyrus network
Model Name: dentatenet
Dataset Name: Test_GC_1000
Definitions: !include Definitions.yaml
Global Parameters: !include Global.yaml
Geometry: !include Geometry.yaml
Random Seeds: !include Random.yaml
Cell Data: DG_Test_GC_1000_cells_20190625_compressed.h5
Connection Data: DG_Test_GC_1000_connections_20190625_compressed.h5
#Gap Junction Data: DG_gapjunctions_20181228.h5
Connection Generator: !include Full_Scale_Connections_GC_Exc_Sat_DD.yaml
Stimulus: !include Input_Configuration.yaml
## Cell types for dentate gyrus model
Cell Types:
  GC:
    template: DGC
    template file: DGC_Template_minimal.hoc
    mechanism file: 20181205_DG_GC_excitability_mech.yaml
    synapses:
      correct_for_spines: True
      density: !include GC_synapse_density.yaml
  MC:
    template: MossyCell
    synapses:
      weights: False
      density: !include MC_synapse_density.yaml
  HC:
    template: HIPPCell
    synapses:
      density: !include HC_synapse_density.yaml
  BC:
    template: BasketCell
    synapses:
      density: !include BC_synapse_density.yaml
  AAC:
    template: AxoAxonicCell
    synapses:
      density: !include AAC_synapse_density.yaml
  HCC:
    template: HICAPCell
    synapses: 
      density: !include HCC_synapse_density.yaml
  NGFC:
    template: NGFCell
    synapses:
      density: !include NGFC_synapse_density.yaml
  MOPP:
    template: MOPPCell
    synapses:
      density: !include NGFC_synapse_density.yaml
  IS:
    template: ISCell
    synapses:
      density: !include IS_synapse_density.yaml
  MPP:
    template: MPPCell
    Vector Stimulus: Vector Stimulus A Diag
  LPP:
    template: LPPCell
    Vector Stimulus: Vector Stimulus A Diag
