optimization_title: DG_optimize_network_subworlds
param_gen: PopulationAnnealing
feature_names:
- GC target rate dist residual
- MC target rate dist residual
- AAC firing rate
- AAC fraction active
- BC firing rate
- BC fraction active
- HC firing rate
- HC fraction active
- HCC firing rate
- HCC fraction active
- IS firing rate
- IS fraction active
- MOPP firing rate
- MOPP fraction active
- NGFC firing rate
- NGFC fraction active
objective_names:
- GC target rate dist residual
- MC target rate dist residual
- BC firing rate
- BC fraction active
- HC firing rate
- HC fraction active
- HCC firing rate
- HCC fraction active
- IS firing rate
- IS fraction active
- MOPP firing rate
- MOPP fraction active
- NGFC firing rate
- NGFC fraction active
update_context:
- - troubleshoot_optimize_network_subworlds
  - update_network
get_features_stages:
- source: troubleshoot_optimize_network_subworlds
  compute_features: compute_network_features
get_objectives:
  troubleshoot_optimize_network_subworlds: get_objectives
kwargs:
  config: Network_Clamp_Slice_neg25_pos25um_IN_Izh.yaml
  tstop: 9500.
  checkpoint_interval: 0.
  v_init: -77.
  vrecord_fraction: 0.05
  dt: 0.025
  cleanup: False
  verbose: True
  cache_queries: True
  output_results: False
  target_populations: ['GC', 'MC', 'AAC', 'BC', 'HC', 'HCC', 'IS', 'MOPP', 'NGFC']

