Locations:
    AAC:
      AAC: [apical, basal]
      BC:  [apical, basal]
    BC:
      BC: [apical, basal]
    HCC:
      HCC: [apical, basal]
    HC:
      HC: [apical, basal]
    IS:
      IS: [apical, basal]
      HC: [basal]
    NGFC:
      NGFC: [apical]
    MOPP:
      MOPP: [apical, basal]
Connection Probabilities:
    AAC:
      AAC: 0.286
      BC:  0.286
    BC:
      BC:   0.286
    HC:
      HC:   0.19
    HCC:
      HCC: 0.085
    IS:
      IS:  0.19
      HC:  0.19
    NGFC:
      NGFC: 0.786
      MOPP: 0.786
    MOPP:
      MOPP: 0.786
## Distance-dependent connection weights,
## based on Fig. 1C from Otsuka 2013
Connection Weights: { 0: 1.0, 25: 0.429, 75: 0.405, 125: 0.345, 175: 0.08 }
Connection Parameters: [0.4201,-0.0019,150.7465,0.0255]
Coupling Coefficients:
    AAC:
      AAC: 0.017
      BC:  0.017
    BC:
      BC:   0.017
    HC:
      HC:   0.13
    IS:
      IS:   0.13
      HC:   0.13
    HCC:
      HCC: 0.04
    NGFC:
      NGFC: 0.0385
      MOPP: 0.0385
    MOPP:
      MOPP: 0.0385
## Distance-dependent coupling coefficient weights,
## Based on Fig. 6B from Amitai 2002
Coupling Weights: { 0: 1.0, 25: 0.5, 75: 0.375, 125: 0.1875, 175: 0.1875 }
Coupling Parameters: [0.0002,-0.0658,7.3211]
    
