- namespace: ['LTP Structured Weights A', 'LTD Structured Weights A', 'Log-Normal Weights']
  expr: a*ltp + b*(d*ltd + lnw)
  parameter: [ltp, ltd, lnw]
  const:
    a: 10.0
    b: 4.0
    d: 1.0
- namespace: ['Normal Weights']
  expr: c*nw
  parameter: [nw]
  const:
    c: 7.3

    
