- namespace: ['LTP Structured Weights A', 'LTD Structured Weights A', 'Log-Normal Weights']
  expr: a*ltp + b*(d*ltd + lnw)
  parameter: [ltp, ltd, lnw]
  const:
    a: 7.778131931151871
    b: 4.459627167714768
    d: 1.0
- namespace: ['Normal Weights']
  expr: c*nw
  parameter: [nw]
  const:
    c: 1.6365018104802096

    
