job_input: ./results/optimize_selectivity
config_prefix: !envsubst $HOME/src/model/dentate/config
dataset_prefix: !envsubst $HOME/src/model/dentate/datasets
input_features: !envsubst $HOME/src/model/dentate/datasets/Full_Scale_Control/DG_input_features_20220216.h5
target_features: !envsubst $HOME/src/model/dentate/datasets/Slice/dentatenet_Slice_SLN_center_pf_20230315.h5
templates: templates
  
