Selectivity Optimization SNR:
  param_config_name: "Weight exc inh netclamp"
  config: Network_Clamp_GC_Exc_Sat_SynExp3NMDA2fd_SLN_CLS_IN_PR_center_pf.yaml
  population: GC
  t_max: 9250
  n_trials: 1
  trial_regime: mean
  use_coreneuron: True
  dt: 0.0125
  input_features_namespaces:
    - 'Place Selectivity'
    - 'Grid Selectivity'
    - 'Constant Selectivity'
  target_features_namespace: 'Place Selectivity'
  arena_id: A
  trajectory_id: Diag
  phase_mod: True
  n_iter: 4000
Inputs:
  job_input: ./results/optimize_selectivity
  dataset_prefix: $HOME/src/model/dentate/datasets
  config_prefix: $HOME/src/model/dentate/config
  input_features: $HOME/src/model/dentate/datasets/Full_Scale_Control/DG_input_features_20220216.h5
  target_features: $HOME/src/model/dentate/datasets/Slice/dentatenet_Slice_SLN_center_pf_20221216.h5
  templates: templates
Outputs:
  job_output: ./results/optimize_selectivity
Parameter Grid:
  - gid: 880730
    

  
