{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.5991942882537842], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.5419792532920837], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.10932695120573044], [AAC, NGFC, apical, GABA_B, weight, 0.594448983669281]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.5359644889831543], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.1106717437505722], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.28722041845321655], [AAC, NGFC, apical, GABA_B, weight, 0.8920698165893555]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.4610506296157837], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.41264787316322327], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.1490127146244049], [AAC, NGFC, apical, GABA_B, weight, 0.16479365527629852]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.5766350030899048], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.1489846557378769], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.270353227853775], [AAC, NGFC, apical, GABA_B, weight, 0.17151615023612976]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.3210687637329102], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.30927711725234985], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.2082548886537552], [AAC, NGFC, apical, GABA_B, weight, 0.2289533019065857]]}}
