{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.656256079673767], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.5208150148391724], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.0130974054336548], [AAC, NGFC, apical, GABA_B, weight, 0.9440891742706299]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.656256079673767], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.5208150148391724], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.0130974054336548], [AAC, NGFC, apical, GABA_B, weight, 0.9440891742706299]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.656256079673767], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.5208150148391724], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.0130974054336548], [AAC, NGFC, apical, GABA_B, weight, 0.9440891742706299]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.656256079673767], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.5208150148391724], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.0130974054336548], [AAC, NGFC, apical, GABA_B, weight, 0.9440891742706299]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.656256079673767], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.5208150148391724], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.0130974054336548], [AAC, NGFC, apical, GABA_B, weight, 0.9440891742706299]]}}
