{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.742792010307312], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.5419792532920837], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9786588549613953], [AAC, NGFC, apical, GABA_B, weight, 1.0610830783843994]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.742792010307312], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.5419792532920837], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9786588549613953], [AAC, NGFC, apical, GABA_B, weight, 1.0610830783843994]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.742792010307312], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.5419792532920837], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9786588549613953], [AAC, NGFC, apical, GABA_B, weight, 1.0610830783843994]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.742792010307312], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.5419792532920837], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9786588549613953], [AAC, NGFC, apical, GABA_B, weight, 1.0610830783843994]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.742792010307312], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.5419792532920837], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9786588549613953], [AAC, NGFC, apical, GABA_B, weight, 1.0610830783843994]]}}
