{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.2920609712600708], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.11736821383237839], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.2050524204969406], [AAC, NGFC, apical, GABA_B, weight, 1.0816283226013184]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.2920609712600708], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.11736821383237839], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.2050524204969406], [AAC, NGFC, apical, GABA_B, weight, 1.0816283226013184]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.2920609712600708], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.11736821383237839], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.2050524204969406], [AAC, NGFC, apical, GABA_B, weight, 1.0816283226013184]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.2920609712600708], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.11736821383237839], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.2050524204969406], [AAC, NGFC, apical, GABA_B, weight, 1.0816283226013184]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.2920609712600708], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.11736821383237839], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.2050524204969406], [AAC, NGFC, apical, GABA_B, weight, 1.0816283226013184]]}}
