{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.6645967960357666], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.3765881359577179], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.0026055574417114], [AAC, NGFC, apical, GABA_B, weight, 0.1869010478258133]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.6645967960357666], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.3765881359577179], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.0026055574417114], [AAC, NGFC, apical, GABA_B, weight, 0.1869010478258133]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.6645967960357666], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.3765881359577179], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.0026055574417114], [AAC, NGFC, apical, GABA_B, weight, 0.1869010478258133]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.6645967960357666], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.3765881359577179], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.0026055574417114], [AAC, NGFC, apical, GABA_B, weight, 0.1869010478258133]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.6645967960357666], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.3765881359577179], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.0026055574417114], [AAC, NGFC, apical, GABA_B, weight, 0.1869010478258133]]}}
