{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.8003263473510742], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.830388069152832], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.8714925050735474], [AAC, NGFC, apical, GABA_B, weight, 0.6354026198387146]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.625559687614441], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.21827544271945953], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.5707210302352905], [AAC, NGFC, apical, GABA_B, weight, 1.0762994289398193]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.4428081512451172], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.3161833584308624], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.175997018814087], [AAC, NGFC, apical, GABA_B, weight, 0.7686589956283569]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.7346625328063965], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.3320876955986023], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.188412070274353], [AAC, NGFC, apical, GABA_B, weight, 1.0296382904052734]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.5930020809173584], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.7741258144378662], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.7565012574195862], [AAC, NGFC, apical, GABA_B, weight, 0.8451048135757446]]}}
