{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.7913451194763184], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.6587781310081482], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.9896520376205444], [AAC, NGFC, apical, GABA_B, weight, 1.949609637260437]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.7913451194763184], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.6587781310081482], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.9896520376205444], [AAC, NGFC, apical, GABA_B, weight, 1.949609637260437]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.7913451194763184], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.6587781310081482], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.9896520376205444], [AAC, NGFC, apical, GABA_B, weight, 1.949609637260437]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.7913451194763184], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.6587781310081482], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.9896520376205444], [AAC, NGFC, apical, GABA_B, weight, 1.949609637260437]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.7913451194763184], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.6587781310081482], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.9896520376205444], [AAC, NGFC, apical, GABA_B, weight, 1.949609637260437]]}}
