{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.2257347106933594], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.1083192527294159], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.10978292673826218], [AAC, NGFC, apical, GABA_B, weight, 0.10084311664104462]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.4073253870010376], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.10075264424085617], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.11143982410430908], [AAC, NGFC, apical, GABA_B, weight, 0.10656654834747314]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.3029166460037231], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.10272039473056793], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.5197754502296448], [AAC, NGFC, apical, GABA_B, weight, 0.10858683288097382]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.4239476919174194], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.1037987768650055], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.10460200160741806], [AAC, NGFC, apical, GABA_B, weight, 0.10479223728179932]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.2520002126693726], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.1752481907606125], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.12769097089767456], [AAC, NGFC, apical, GABA_B, weight, 0.15892666578292847]]}}
