{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.9850510358810425], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.9746267199516296], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9671264886856079], [AAC, NGFC, apical, GABA_B, weight, 1.6108429431915283]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.9850510358810425], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.9746267199516296], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9671264886856079], [AAC, NGFC, apical, GABA_B, weight, 1.6108429431915283]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.9850510358810425], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.9746267199516296], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9671264886856079], [AAC, NGFC, apical, GABA_B, weight, 1.6108429431915283]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.9850510358810425], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.9746267199516296], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9671264886856079], [AAC, NGFC, apical, GABA_B, weight, 1.6108429431915283]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.9850510358810425], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.9746267199516296], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9671264886856079], [AAC, NGFC, apical, GABA_B, weight, 1.6108429431915283]]}}
