{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.6541719436645508], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.41883546113967896], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.0410287380218506], [AAC, NGFC, apical, GABA_B, weight, 0.9202980995178223]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.6541719436645508], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.41883546113967896], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.0410287380218506], [AAC, NGFC, apical, GABA_B, weight, 0.9202980995178223]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.6541719436645508], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.41883546113967896], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.0410287380218506], [AAC, NGFC, apical, GABA_B, weight, 0.9202980995178223]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.6541719436645508], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.41883546113967896], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.0410287380218506], [AAC, NGFC, apical, GABA_B, weight, 0.9202980995178223]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.6541719436645508], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.41883546113967896], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.0410287380218506], [AAC, NGFC, apical, GABA_B, weight, 0.9202980995178223]]}}
