{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.986778736114502], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.563580334186554], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.4473493099212646], [AAC, NGFC, apical, GABA_B, weight, 1.4521691799163818]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.986778736114502], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.563580334186554], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.4473493099212646], [AAC, NGFC, apical, GABA_B, weight, 1.4521691799163818]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.986778736114502], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.563580334186554], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.4473493099212646], [AAC, NGFC, apical, GABA_B, weight, 1.4521691799163818]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.986778736114502], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.563580334186554], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.4473493099212646], [AAC, NGFC, apical, GABA_B, weight, 1.4521691799163818]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.986778736114502], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.563580334186554], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.4473493099212646], [AAC, NGFC, apical, GABA_B, weight, 1.4521691799163818]]}}
