{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.3210687637329102], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.1106717437505722], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.10932695120573044], [AAC, NGFC, apical, GABA_B, weight, 0.16479365527629852]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.3210687637329102], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.1106717437505722], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.10932695120573044], [AAC, NGFC, apical, GABA_B, weight, 0.16479365527629852]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.3210687637329102], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.1106717437505722], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.10932695120573044], [AAC, NGFC, apical, GABA_B, weight, 0.16479365527629852]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.3210687637329102], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.1106717437505722], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.10932695120573044], [AAC, NGFC, apical, GABA_B, weight, 0.16479365527629852]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.3210687637329102], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.1106717437505722], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.10932695120573044], [AAC, NGFC, apical, GABA_B, weight, 0.16479365527629852]]}}
