{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.4716981649398804], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.13957849144935608], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.9537649154663086], [AAC, NGFC, apical, GABA_B, weight, 0.1514483541250229]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.4716981649398804], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.13957849144935608], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.9537649154663086], [AAC, NGFC, apical, GABA_B, weight, 0.1514483541250229]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.4716981649398804], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.13957849144935608], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.9537649154663086], [AAC, NGFC, apical, GABA_B, weight, 0.1514483541250229]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.4716981649398804], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.13957849144935608], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.9537649154663086], [AAC, NGFC, apical, GABA_B, weight, 0.1514483541250229]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.4716981649398804], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.13957849144935608], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.9537649154663086], [AAC, NGFC, apical, GABA_B, weight, 0.1514483541250229]]}}
