{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.408701777458191], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.44475892186164856], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 2.0], [AAC, NGFC, apical, GABA_B, weight, 0.657680094242096]], 1042913: [
      [AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.408701777458191], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A, weight,
        0.44475892186164856], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A, weight,
        2.0], [AAC, NGFC, apical, GABA_B, weight, 0.657680094242096]], 1043025: [
      [AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.408701777458191], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A, weight,
        0.44475892186164856], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A, weight,
        2.0], [AAC, NGFC, apical, GABA_B, weight, 0.657680094242096]], 1043138: [
      [AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.408701777458191], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A, weight,
        0.44475892186164856], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A, weight,
        2.0], [AAC, NGFC, apical, GABA_B, weight, 0.657680094242096]], 1043249: [
      [AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.408701777458191], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A, weight,
        0.44475892186164856], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A, weight,
        2.0], [AAC, NGFC, apical, GABA_B, weight, 0.657680094242096]]}}
