{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.2257347106933594], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.10075264424085617], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.10460200160741806], [AAC, NGFC, apical, GABA_B, weight, 0.10084311664104462]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.2257347106933594], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.10075264424085617], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.10460200160741806], [AAC, NGFC, apical, GABA_B, weight, 0.10084311664104462]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.2257347106933594], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.10075264424085617], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.10460200160741806], [AAC, NGFC, apical, GABA_B, weight, 0.10084311664104462]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.2257347106933594], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.10075264424085617], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.10460200160741806], [AAC, NGFC, apical, GABA_B, weight, 0.10084311664104462]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.2257347106933594], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.10075264424085617], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.10460200160741806], [AAC, NGFC, apical, GABA_B, weight, 0.10084311664104462]]}}
