{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.7913451194763184], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.8132079243659973], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.7989098429679871], [AAC, NGFC, apical, GABA_B, weight, 1.0610830783843994]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.6765401363372803], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.27956268191337585], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9786588549613953], [AAC, NGFC, apical, GABA_B, weight, 1.2541084289550781]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.6099011898040771], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.4717610776424408], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.5499907732009888], [AAC, NGFC, apical, GABA_B, weight, 0.714609682559967]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.8137314319610596], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.4484715163707733], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.4473493099212646], [AAC, NGFC, apical, GABA_B, weight, 1.1529484987258911]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.6131881475448608], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.7737137675285339], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.2221239805221558], [AAC, NGFC, apical, GABA_B, weight, 0.833479106426239]]}}
