{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.7219939231872559], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.6033821105957031], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9624826908111572], [AAC, NGFC, apical, GABA_B, weight, 1.0300430059432983]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.7219939231872559], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.6033821105957031], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9624826908111572], [AAC, NGFC, apical, GABA_B, weight, 1.0300430059432983]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.7219939231872559], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.6033821105957031], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9624826908111572], [AAC, NGFC, apical, GABA_B, weight, 1.0300430059432983]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.7219939231872559], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.6033821105957031], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9624826908111572], [AAC, NGFC, apical, GABA_B, weight, 1.0300430059432983]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.7219939231872559], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.6033821105957031], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9624826908111572], [AAC, NGFC, apical, GABA_B, weight, 1.0300430059432983]]}}
