{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.7021764516830444], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.6993297934532166], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9226008653640747], [AAC, NGFC, apical, GABA_B, weight, 0.7219516038894653]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.6657794713974], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.30002641677856445], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.7396261692047119], [AAC, NGFC, apical, GABA_B, weight, 1.0593949556350708]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.5726490020751953], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.4517381191253662], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.2965924739837646], [AAC, NGFC, apical, GABA_B, weight, 0.8971195220947266]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.7274421453475952], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.34336057305336], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.1757172346115112], [AAC, NGFC, apical, GABA_B, weight, 1.0544931888580322]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.613233208656311], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.809620201587677], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9309505224227905], [AAC, NGFC, apical, GABA_B, weight, 0.9874868392944336]]}}
