{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.4610506296157837], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.41264787316322327], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.15152834355831146], [AAC, NGFC, apical, GABA_B, weight, 0.714609682559967]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.4610506296157837], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.41264787316322327], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.15152834355831146], [AAC, NGFC, apical, GABA_B, weight, 0.714609682559967]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.4610506296157837], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.41264787316322327], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.15152834355831146], [AAC, NGFC, apical, GABA_B, weight, 0.714609682559967]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.4610506296157837], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.41264787316322327], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.15152834355831146], [AAC, NGFC, apical, GABA_B, weight, 0.714609682559967]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.4610506296157837], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.41264787316322327], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.15152834355831146], [AAC, NGFC, apical, GABA_B, weight, 0.714609682559967]]}}
