{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.8447779417037964], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.4655640721321106], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.28722041845321655], [AAC, NGFC, apical, GABA_B, weight, 1.4744523763656616]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.8447779417037964], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.4655640721321106], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.28722041845321655], [AAC, NGFC, apical, GABA_B, weight, 1.4744523763656616]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.8447779417037964], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.4655640721321106], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.28722041845321655], [AAC, NGFC, apical, GABA_B, weight, 1.4744523763656616]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.8447779417037964], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.4655640721321106], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.28722041845321655], [AAC, NGFC, apical, GABA_B, weight, 1.4744523763656616]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.8447779417037964], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.4655640721321106], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.28722041845321655], [AAC, NGFC, apical, GABA_B, weight, 1.4744523763656616]]}}
