{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.9899749755859375], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 1.4732208251953125], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.2082548886537552], [AAC, NGFC, apical, GABA_B, weight, 0.9088124632835388]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.9899749755859375], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 1.4732208251953125], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.2082548886537552], [AAC, NGFC, apical, GABA_B, weight, 0.9088124632835388]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.9899749755859375], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 1.4732208251953125], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.2082548886537552], [AAC, NGFC, apical, GABA_B, weight, 0.9088124632835388]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.9899749755859375], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 1.4732208251953125], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.2082548886537552], [AAC, NGFC, apical, GABA_B, weight, 0.9088124632835388]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.9899749755859375], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 1.4732208251953125], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.2082548886537552], [AAC, NGFC, apical, GABA_B, weight, 0.9088124632835388]]}}
