{AAC: {1042800: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.8082870244979858], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.7929438352584839], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.8704992532730103], [AAC, NGFC, apical, GABA_B, weight, 1.238675832748413]],
    1042913: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.7231823205947876], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.32885655760765076], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.9094298481941223], [AAC, NGFC, apical, GABA_B, weight, 1.277338981628418]],
    1043025: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.6495635509490967], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.6267107725143433], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.7095504999160767], [AAC, NGFC, apical, GABA_B, weight, 0.8029831051826477]],
    1043138: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.7987315654754639], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.4293234348297119], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.1986854076385498], [AAC, NGFC, apical, GABA_B, weight, 0.9460500478744507]],
    1043249: [[AAC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA,
        weight, 1.6302051544189453], [AAC, [HCC, HC, IS], [apical, basal, soma], GABA_A,
        weight, 0.8390758633613586], [AAC, [NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 1.1242483854293823], [AAC, NGFC, apical, GABA_B, weight, 0.8851668238639832]]}}
