{BC: {1039000: [[BC, [BC, HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A,
        weight, 1.1299653053283691], [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma,
          basal, apical], AMPA, weight, 5.025723457336426], [BC, NGFC, apical, GABA_B,
        weight, 1.2676341533660889]], 1039950: [[BC, [BC, HCC, HC, NGFC, MOPP, IS],
        [apical, basal, soma], GABA_A, weight, 1.009150505065918], [BC, [GC, MC, ConMC,
          CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 5.429140090942383],
      [BC, NGFC, apical, GABA_B, weight, 1.0694684982299805]], 1040900: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.0890506505966187],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 4.100180625915527],
      [BC, NGFC, apical, GABA_B, weight, 1.1670489311218262]], 1041850: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.0122942924499512],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 4.7990570068359375],
      [BC, NGFC, apical, GABA_B, weight, 0.9483863115310669]], 1042799: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.0878937244415283],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 7.458769798278809],
      [BC, NGFC, apical, GABA_B, weight, 0.7329354286193848]]}}
