{BC: {1039000: [[BC, [BC, HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A,
        weight, 1.1069790124893188], [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma,
          basal, apical], AMPA, weight, 6.37484884262085], [BC, NGFC, apical, GABA_B,
        weight, 0.41745954751968384]], 1039950: [[BC, [BC, HCC, HC, NGFC, MOPP, IS],
        [apical, basal, soma], GABA_A, weight, 1.1069790124893188], [BC, [GC, MC,
          ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 6.37484884262085],
      [BC, NGFC, apical, GABA_B, weight, 0.41745954751968384]], 1040900: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.1069790124893188],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 6.37484884262085],
      [BC, NGFC, apical, GABA_B, weight, 0.41745954751968384]], 1041850: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.1069790124893188],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 6.37484884262085],
      [BC, NGFC, apical, GABA_B, weight, 0.41745954751968384]], 1042799: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.1069790124893188],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 6.37484884262085],
      [BC, NGFC, apical, GABA_B, weight, 0.41745954751968384]]}}
