{BC: {1039000: [[BC, [BC, HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A,
        weight, 1.7403427362442017], [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma,
          basal, apical], AMPA, weight, 8.520821571350098], [BC, NGFC, apical, GABA_B,
        weight, 0.6234251260757446]], 1039950: [[BC, [BC, HCC, HC, NGFC, MOPP, IS],
        [apical, basal, soma], GABA_A, weight, 1.7403427362442017], [BC, [GC, MC,
          ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 8.520821571350098],
      [BC, NGFC, apical, GABA_B, weight, 0.6234251260757446]], 1040900: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.7403427362442017],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 8.520821571350098],
      [BC, NGFC, apical, GABA_B, weight, 0.6234251260757446]], 1041850: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.7403427362442017],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 8.520821571350098],
      [BC, NGFC, apical, GABA_B, weight, 0.6234251260757446]], 1042799: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.7403427362442017],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 8.520821571350098],
      [BC, NGFC, apical, GABA_B, weight, 0.6234251260757446]]}}
