{BC: {1039000: [[BC, [BC, HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A,
        weight, 0.9984838962554932], [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma,
          basal, apical], AMPA, weight, 3.9445223808288574], [BC, NGFC, apical, GABA_B,
        weight, 0.21698735654354095]], 1039950: [[BC, [BC, HCC, HC, NGFC, MOPP, IS],
        [apical, basal, soma], GABA_A, weight, 1.0100891590118408], [BC, [GC, MC,
          ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 5.146968841552734],
      [BC, NGFC, apical, GABA_B, weight, 0.43097713589668274]], 1040900: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 0.8877623677253723],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 2.079773426055908],
      [BC, NGFC, apical, GABA_B, weight, 0.8107409477233887]], 1041850: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 0.9872382879257202],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 2.8370859622955322],
      [BC, NGFC, apical, GABA_B, weight, 0.1217377781867981]], 1042799: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.0528533458709717],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 4.275435447692871],
      [BC, NGFC, apical, GABA_B, weight, 0.1702263206243515]]}}
