{BC: {1039000: [[BC, [BC, HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A,
        weight, 0.8877623677253723], [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma,
          basal, apical], AMPA, weight, 2.079773426055908], [BC, NGFC, apical, GABA_B,
        weight, 0.1217377781867981]], 1039950: [[BC, [BC, HCC, HC, NGFC, MOPP, IS],
        [apical, basal, soma], GABA_A, weight, 0.8877623677253723], [BC, [GC, MC,
          ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 2.079773426055908],
      [BC, NGFC, apical, GABA_B, weight, 0.1217377781867981]], 1040900: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 0.8877623677253723],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 2.079773426055908],
      [BC, NGFC, apical, GABA_B, weight, 0.1217377781867981]], 1041850: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 0.8877623677253723],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 2.079773426055908],
      [BC, NGFC, apical, GABA_B, weight, 0.1217377781867981]], 1042799: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 0.8877623677253723],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 2.079773426055908],
      [BC, NGFC, apical, GABA_B, weight, 0.1217377781867981]]}}
