{BC: {1039000: [[BC, [BC, HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A,
        weight, 1.146170973777771], [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal,
          apical], AMPA, weight, 5.799760341644287], [BC, NGFC, apical, GABA_B, weight,
        1.1086019277572632]], 1039950: [[BC, [BC, HCC, HC, NGFC, MOPP, IS], [apical,
          basal, soma], GABA_A, weight, 1.146170973777771], [BC, [GC, MC, ConMC, CA3c,
          MPP, LPP], [soma, basal, apical], AMPA, weight, 5.799760341644287], [BC,
        NGFC, apical, GABA_B, weight, 1.1086019277572632]], 1040900: [[BC, [BC, HCC,
          HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.146170973777771],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 5.799760341644287],
      [BC, NGFC, apical, GABA_B, weight, 1.1086019277572632]], 1041850: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.146170973777771],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 5.799760341644287],
      [BC, NGFC, apical, GABA_B, weight, 1.1086019277572632]], 1042799: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.146170973777771],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 5.799760341644287],
      [BC, NGFC, apical, GABA_B, weight, 1.1086019277572632]]}}
