{BC: {1039000: [[BC, [BC, HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A,
        weight, 0.8878757953643799], [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma,
          basal, apical], AMPA, weight, 2.0800392627716064], [BC, NGFC, apical, GABA_B,
        weight, 1.9610224962234497]], 1039950: [[BC, [BC, HCC, HC, NGFC, MOPP, IS],
        [apical, basal, soma], GABA_A, weight, 0.8878757953643799], [BC, [GC, MC,
          ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 2.0800392627716064],
      [BC, NGFC, apical, GABA_B, weight, 1.9610224962234497]], 1040900: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 0.8878757953643799],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 2.0800392627716064],
      [BC, NGFC, apical, GABA_B, weight, 1.9610224962234497]], 1041850: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 0.8878757953643799],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 2.0800392627716064],
      [BC, NGFC, apical, GABA_B, weight, 1.9610224962234497]], 1042799: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 0.8878757953643799],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 2.0800392627716064],
      [BC, NGFC, apical, GABA_B, weight, 1.9610224962234497]]}}
