{BC: {1039000: [[BC, [BC, HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A,
        weight, 1.1158679723739624], [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma,
          basal, apical], AMPA, weight, 7.442686557769775], [BC, NGFC, apical, GABA_B,
        weight, 1.1389487981796265]], 1039950: [[BC, [BC, HCC, HC, NGFC, MOPP, IS],
        [apical, basal, soma], GABA_A, weight, 1.1158679723739624], [BC, [GC, MC,
          ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 7.442686557769775],
      [BC, NGFC, apical, GABA_B, weight, 1.1389487981796265]], 1040900: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.1158679723739624],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 7.442686557769775],
      [BC, NGFC, apical, GABA_B, weight, 1.1389487981796265]], 1041850: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.1158679723739624],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 7.442686557769775],
      [BC, NGFC, apical, GABA_B, weight, 1.1389487981796265]], 1042799: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.1158679723739624],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 7.442686557769775],
      [BC, NGFC, apical, GABA_B, weight, 1.1389487981796265]]}}
