{BC: {1039000: [[BC, [BC, HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A,
        weight, 1.079746961593628], [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal,
          apical], AMPA, weight, 3.472764492034912], [BC, NGFC, apical, GABA_B, weight,
        1.7332035303115845]], 1039950: [[BC, [BC, HCC, HC, NGFC, MOPP, IS], [apical,
          basal, soma], GABA_A, weight, 0.9734660387039185], [BC, [GC, MC, ConMC,
          CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 6.689042091369629],
      [BC, NGFC, apical, GABA_B, weight, 1.6856135129928589]], 1040900: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 0.15153953433036804],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 0.38412463665008545],
      [BC, NGFC, apical, GABA_B, weight, 0.1034378707408905]], 1041850: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 0.7419800162315369],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 1.5569908618927002],
      [BC, NGFC, apical, GABA_B, weight, 0.21248187124729156]], 1042799: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 0.5292323231697083],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 1.1783714294433594],
      [BC, NGFC, apical, GABA_B, weight, 0.2662927210330963]]}}
