{BC: {1039000: [[BC, [BC, HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A,
        weight, 1.1135753393173218], [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma,
          basal, apical], AMPA, weight, 5.146925926208496], [BC, NGFC, apical, GABA_B,
        weight, 1.2092746496200562]], 1039950: [[BC, [BC, HCC, HC, NGFC, MOPP, IS],
        [apical, basal, soma], GABA_A, weight, 0.9614757299423218], [BC, [GC, MC,
          ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 5.1532111167907715],
      [BC, NGFC, apical, GABA_B, weight, 1.1590921878814697]], 1040900: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.0401854515075684],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 4.984309196472168],
      [BC, NGFC, apical, GABA_B, weight, 1.1823867559432983]], 1041850: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 0.9951789975166321],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 5.032109260559082],
      [BC, NGFC, apical, GABA_B, weight, 1.0146129131317139]], 1042799: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.0631916522979736],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 6.729307651519775],
      [BC, NGFC, apical, GABA_B, weight, 0.8070402145385742]]}}
