{BC: {1039000: [[BC, [BC, HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A,
        weight, 1.0375876426696777], [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma,
          basal, apical], AMPA, weight, 6.519272327423096], [BC, NGFC, apical, GABA_B,
        weight, 1.7140942811965942]], 1039950: [[BC, [BC, HCC, HC, NGFC, MOPP, IS],
        [apical, basal, soma], GABA_A, weight, 1.0375876426696777], [BC, [GC, MC,
          ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 6.519272327423096],
      [BC, NGFC, apical, GABA_B, weight, 1.7140942811965942]], 1040900: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.0375876426696777],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 6.519272327423096],
      [BC, NGFC, apical, GABA_B, weight, 1.7140942811965942]], 1041850: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.0375876426696777],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 6.519272327423096],
      [BC, NGFC, apical, GABA_B, weight, 1.7140942811965942]], 1042799: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.0375876426696777],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 6.519272327423096],
      [BC, NGFC, apical, GABA_B, weight, 1.7140942811965942]]}}
