{BC: {1039000: [[BC, [BC, HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A,
        weight, 1.066370964050293], [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal,
          apical], AMPA, weight, 8.276016235351562], [BC, NGFC, apical, GABA_B, weight,
        0.8876650333404541]], 1039950: [[BC, [BC, HCC, HC, NGFC, MOPP, IS], [apical,
          basal, soma], GABA_A, weight, 1.066370964050293], [BC, [GC, MC, ConMC, CA3c,
          MPP, LPP], [soma, basal, apical], AMPA, weight, 8.276016235351562], [BC,
        NGFC, apical, GABA_B, weight, 0.8876650333404541]], 1040900: [[BC, [BC, HCC,
          HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.066370964050293],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 8.276016235351562],
      [BC, NGFC, apical, GABA_B, weight, 0.8876650333404541]], 1041850: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.066370964050293],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 8.276016235351562],
      [BC, NGFC, apical, GABA_B, weight, 0.8876650333404541]], 1042799: [[BC, [BC,
          HCC, HC, NGFC, MOPP, IS], [apical, basal, soma], GABA_A, weight, 1.066370964050293],
      [BC, [GC, MC, ConMC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight, 8.276016235351562],
      [BC, NGFC, apical, GABA_B, weight, 0.8876650333404541]]}}
