{HC: {1030000: [[HC, [GC, MC, CA3c], [soma, apical], AMPA, weight, 5.666354179382324],
      [HC, [HC, IS], [apical, soma], GABA_A, weight, 0.2388438582420349]], 1032250: [
      [HC, [GC, MC, CA3c], [soma, apical], AMPA, weight, 5.666354179382324], [HC,
        [HC, IS], [apical, soma], GABA_A, weight, 0.2388438582420349]], 1034500: [
      [HC, [GC, MC, CA3c], [soma, apical], AMPA, weight, 5.666354179382324], [HC,
        [HC, IS], [apical, soma], GABA_A, weight, 0.2388438582420349]], 1036750: [
      [HC, [GC, MC, CA3c], [soma, apical], AMPA, weight, 5.666354179382324], [HC,
        [HC, IS], [apical, soma], GABA_A, weight, 0.2388438582420349]], 1038999: [
      [HC, [GC, MC, CA3c], [soma, apical], AMPA, weight, 5.666354179382324], [HC,
        [HC, IS], [apical, soma], GABA_A, weight, 0.2388438582420349]]}}
