{HC: {1030000: [[HC, [GC, MC, CA3c], [soma, apical], AMPA, weight, 9.888604164123535],
      [HC, [HC, IS], [apical, soma], GABA_A, weight, 0.422184556722641]], 1032250: [
      [HC, [GC, MC, CA3c], [soma, apical], AMPA, weight, 9.888604164123535], [HC,
        [HC, IS], [apical, soma], GABA_A, weight, 0.422184556722641]], 1034500: [
      [HC, [GC, MC, CA3c], [soma, apical], AMPA, weight, 9.888604164123535], [HC,
        [HC, IS], [apical, soma], GABA_A, weight, 0.422184556722641]], 1036750: [
      [HC, [GC, MC, CA3c], [soma, apical], AMPA, weight, 9.888604164123535], [HC,
        [HC, IS], [apical, soma], GABA_A, weight, 0.422184556722641]], 1038999: [
      [HC, [GC, MC, CA3c], [soma, apical], AMPA, weight, 9.888604164123535], [HC,
        [HC, IS], [apical, soma], GABA_A, weight, 0.422184556722641]]}}
