{HC: {1030000: [[HC, [GC, MC, CA3c], [soma, apical], AMPA, weight, 6.149328231811523],
      [HC, [HC, IS], [apical, soma], GABA_A, weight, 0.2675996422767639]], 1032250: [
      [HC, [GC, MC, CA3c], [soma, apical], AMPA, weight, 6.149328231811523], [HC,
        [HC, IS], [apical, soma], GABA_A, weight, 0.2675996422767639]], 1034500: [
      [HC, [GC, MC, CA3c], [soma, apical], AMPA, weight, 6.149328231811523], [HC,
        [HC, IS], [apical, soma], GABA_A, weight, 0.2675996422767639]], 1036750: [
      [HC, [GC, MC, CA3c], [soma, apical], AMPA, weight, 6.149328231811523], [HC,
        [HC, IS], [apical, soma], GABA_A, weight, 0.2675996422767639]], 1038999: [
      [HC, [GC, MC, CA3c], [soma, apical], AMPA, weight, 6.149328231811523], [HC,
        [HC, IS], [apical, soma], GABA_A, weight, 0.2675996422767639]]}}
