{HCC: {1043250: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.4780248403549194], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.26760029792785645], [HCC, NGFC, apical, GABA_B, weight, 0.08867614716291428]],
    1043600: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.4780248403549194], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.26760029792785645], [HCC, NGFC, apical, GABA_B, weight, 0.08867614716291428]],
    1043950: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.4780248403549194], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.26760029792785645], [HCC, NGFC, apical, GABA_B, weight, 0.08867614716291428]],
    1044300: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.4780248403549194], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.26760029792785645], [HCC, NGFC, apical, GABA_B, weight, 0.08867614716291428]],
    1044649: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.4780248403549194], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.26760029792785645], [HCC, NGFC, apical, GABA_B, weight, 0.08867614716291428]]}}
