{HCC: {1043250: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        0.9848021864891052], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.014503181912004948], [HCC, NGFC, apical, GABA_B, weight, 0.11252227425575256]],
    1043600: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        0.9848021864891052], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.014503181912004948], [HCC, NGFC, apical, GABA_B, weight, 0.11252227425575256]],
    1043950: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        0.9848021864891052], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.014503181912004948], [HCC, NGFC, apical, GABA_B, weight, 0.11252227425575256]],
    1044300: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        0.9848021864891052], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.014503181912004948], [HCC, NGFC, apical, GABA_B, weight, 0.11252227425575256]],
    1044649: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        0.9848021864891052], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.014503181912004948], [HCC, NGFC, apical, GABA_B, weight, 0.11252227425575256]]}}
