{HCC: {1043250: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.5322544574737549], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.2701214551925659], [HCC, NGFC, apical, GABA_B, weight, 0.07975855469703674]],
    1043600: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.5322544574737549], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.2701214551925659], [HCC, NGFC, apical, GABA_B, weight, 0.07975855469703674]],
    1043950: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.5322544574737549], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.2701214551925659], [HCC, NGFC, apical, GABA_B, weight, 0.07975855469703674]],
    1044300: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.5322544574737549], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.2701214551925659], [HCC, NGFC, apical, GABA_B, weight, 0.07975855469703674]],
    1044649: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.5322544574737549], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.2701214551925659], [HCC, NGFC, apical, GABA_B, weight, 0.07975855469703674]]}}
