{HCC: {1043250: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.2404001951217651], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.02988925576210022], [HCC, NGFC, apical, GABA_B, weight, 0.12671366333961487]],
    1043600: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.2404001951217651], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.02988925576210022], [HCC, NGFC, apical, GABA_B, weight, 0.12671366333961487]],
    1043950: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.2404001951217651], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.02988925576210022], [HCC, NGFC, apical, GABA_B, weight, 0.12671366333961487]],
    1044300: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.2404001951217651], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.02988925576210022], [HCC, NGFC, apical, GABA_B, weight, 0.12671366333961487]],
    1044649: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.2404001951217651], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.02988925576210022], [HCC, NGFC, apical, GABA_B, weight, 0.12671366333961487]]}}
