{HCC: {1043250: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.5162937641143799], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.3462922275066376], [HCC, NGFC, apical, GABA_B, weight, 0.05624120682477951]],
    1043600: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.5162937641143799], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.3462922275066376], [HCC, NGFC, apical, GABA_B, weight, 0.05624120682477951]],
    1043950: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.5162937641143799], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.3462922275066376], [HCC, NGFC, apical, GABA_B, weight, 0.05624120682477951]],
    1044300: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.5162937641143799], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.3462922275066376], [HCC, NGFC, apical, GABA_B, weight, 0.05624120682477951]],
    1044649: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.5162937641143799], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.3462922275066376], [HCC, NGFC, apical, GABA_B, weight, 0.05624120682477951]]}}
