{HCC: {1043250: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        0.6482567191123962], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.009999999776482582], [HCC, NGFC, apical, GABA_B, weight, 0.05000000074505806]],
    1043600: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        0.6482567191123962], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.009999999776482582], [HCC, NGFC, apical, GABA_B, weight, 0.05000000074505806]],
    1043950: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        0.6482567191123962], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.009999999776482582], [HCC, NGFC, apical, GABA_B, weight, 0.05000000074505806]],
    1044300: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        0.6482567191123962], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.009999999776482582], [HCC, NGFC, apical, GABA_B, weight, 0.05000000074505806]],
    1044649: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        0.6482567191123962], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.009999999776482582], [HCC, NGFC, apical, GABA_B, weight, 0.05000000074505806]]}}
