{HCC: {1043250: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.154689073562622], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.28481489419937134], [HCC, NGFC, apical, GABA_B, weight, 0.05015739053487778]],
    1043600: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.154689073562622], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.28481489419937134], [HCC, NGFC, apical, GABA_B, weight, 0.05015739053487778]],
    1043950: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.154689073562622], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.28481489419937134], [HCC, NGFC, apical, GABA_B, weight, 0.05015739053487778]],
    1044300: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.154689073562622], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.28481489419937134], [HCC, NGFC, apical, GABA_B, weight, 0.05015739053487778]],
    1044649: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.154689073562622], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.28481489419937134], [HCC, NGFC, apical, GABA_B, weight, 0.05015739053487778]]}}
