{HCC: {1043250: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.2655867338180542], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.018401632085442543], [HCC, NGFC, apical, GABA_B, weight, 0.14174586534500122]],
    1043600: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.2655867338180542], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.018401632085442543], [HCC, NGFC, apical, GABA_B, weight, 0.14174586534500122]],
    1043950: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.2655867338180542], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.018401632085442543], [HCC, NGFC, apical, GABA_B, weight, 0.14174586534500122]],
    1044300: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.2655867338180542], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.018401632085442543], [HCC, NGFC, apical, GABA_B, weight, 0.14174586534500122]],
    1044649: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.2655867338180542], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.018401632085442543], [HCC, NGFC, apical, GABA_B, weight, 0.14174586534500122]]}}
