{HCC: {1043250: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.1883893013000488], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.01083002146333456], [HCC, NGFC, apical, GABA_B, weight, 0.07051055878400803]],
    1043600: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        0.6467579007148743], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.0648890808224678], [HCC, NGFC, apical, GABA_B, weight, 0.05000000074505806]],
    1043950: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.265164852142334], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.011252758093178272], [HCC, NGFC, apical, GABA_B, weight, 0.05000000074505806]],
    1044300: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.6615488529205322], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.3645842969417572], [HCC, NGFC, apical, GABA_B, weight, 0.05476927384734154]],
    1044649: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.307176947593689], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.3013789653778076], [HCC, NGFC, apical, GABA_B, weight, 0.05000000074505806]]}}
