{HCC: {1043250: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.6230486631393433], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.34697622060775757], [HCC, NGFC, apical, GABA_B, weight, 0.059061452746391296]],
    1043600: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.6230486631393433], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.34697622060775757], [HCC, NGFC, apical, GABA_B, weight, 0.059061452746391296]],
    1043950: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.6230486631393433], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.34697622060775757], [HCC, NGFC, apical, GABA_B, weight, 0.059061452746391296]],
    1044300: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.6230486631393433], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.34697622060775757], [HCC, NGFC, apical, GABA_B, weight, 0.059061452746391296]],
    1044649: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.6230486631393433], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.34697622060775757], [HCC, NGFC, apical, GABA_B, weight, 0.059061452746391296]]}}
