{HCC: {1043250: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.548733115196228], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.275443434715271], [HCC, NGFC, apical, GABA_B, weight, 0.08021027594804764]],
    1043600: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.548733115196228], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.275443434715271], [HCC, NGFC, apical, GABA_B, weight, 0.08021027594804764]],
    1043950: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.548733115196228], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.275443434715271], [HCC, NGFC, apical, GABA_B, weight, 0.08021027594804764]],
    1044300: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.548733115196228], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.275443434715271], [HCC, NGFC, apical, GABA_B, weight, 0.08021027594804764]],
    1044649: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.548733115196228], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.275443434715271], [HCC, NGFC, apical, GABA_B, weight, 0.08021027594804764]]}}
