{HCC: {1043250: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        0.9848021864891052], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.009999999776482582], [HCC, NGFC, apical, GABA_B, weight, 0.05624120682477951]],
    1043600: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        0.6482567191123962], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.0644843801856041], [HCC, NGFC, apical, GABA_B, weight, 0.05000000074505806]],
    1043950: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.2085129022598267], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.018401632085442543], [HCC, NGFC, apical, GABA_B, weight, 0.05000000074505806]],
    1044300: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.6615374088287354], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.2668326497077942], [HCC, NGFC, apical, GABA_B, weight, 0.05222471058368683]],
    1044649: [[HCC, [GC, MC, CA3c, MPP, LPP], [soma, basal, apical], AMPA, weight,
        0.9755041003227234], [HCC, [IS, HCC, NGFC, MOPP], [apical, basal, soma], GABA_A,
        weight, 0.02988925576210022], [HCC, NGFC, apical, GABA_B, weight, 0.05000000074505806]]}}
