{IS: {1049650: [[IS, GC, [soma, basal, apical], AMPA, weight, 2.945051670074463],
      [IS, IS, [apical, basal, soma], GABA_A, weight, 0.9600639939308167]], 1050400: [
      [IS, GC, [soma, basal, apical], AMPA, weight, 2.945051670074463], [IS, IS, [
          apical, basal, soma], GABA_A, weight, 0.9600639939308167]], 1051150: [[
        IS, GC, [soma, basal, apical], AMPA, weight, 2.945051670074463], [IS, IS,
        [apical, basal, soma], GABA_A, weight, 0.9600639939308167]], 1051900: [[IS,
        GC, [soma, basal, apical], AMPA, weight, 2.945051670074463], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 0.9600639939308167]], 1052649: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 2.945051670074463], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 0.9600639939308167]]}}
