{IS: {1049650: [[IS, GC, [soma, basal, apical], AMPA, weight, 2.9486615657806396],
      [IS, IS, [apical, basal, soma], GABA_A, weight, 0.8074999451637268]], 1050400: [
      [IS, GC, [soma, basal, apical], AMPA, weight, 2.9486615657806396], [IS, IS,
        [apical, basal, soma], GABA_A, weight, 0.8074999451637268]], 1051150: [[IS,
        GC, [soma, basal, apical], AMPA, weight, 2.9486615657806396], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 0.8074999451637268]], 1051900: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 2.9486615657806396], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 0.8074999451637268]], 1052649: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 2.9486615657806396], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 0.8074999451637268]]}}
