{IS: {1049650: [[IS, GC, [soma, basal, apical], AMPA, weight, 2.250237464904785],
      [IS, IS, [apical, basal, soma], GABA_A, weight, 0.3349410593509674]], 1050400: [
      [IS, GC, [soma, basal, apical], AMPA, weight, 2.949512481689453], [IS, IS, [
          apical, basal, soma], GABA_A, weight, 0.8109498620033264]], 1051150: [[
        IS, GC, [soma, basal, apical], AMPA, weight, 3.265071392059326], [IS, IS,
        [apical, basal, soma], GABA_A, weight, 1.2640464305877686]], 1051900: [[IS,
        GC, [soma, basal, apical], AMPA, weight, 3.4795618057250977], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 0.9930841326713562]], 1052649: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 2.9149587154388428], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.743282437324524]]}}
