{IS: {1049650: [[IS, GC, [soma, basal, apical], AMPA, weight, 3.263845682144165],
      [IS, IS, [apical, basal, soma], GABA_A, weight, 1.26094651222229]], 1050400: [
      [IS, GC, [soma, basal, apical], AMPA, weight, 3.263845682144165], [IS, IS, [
          apical, basal, soma], GABA_A, weight, 1.26094651222229]], 1051150: [[IS,
        GC, [soma, basal, apical], AMPA, weight, 3.263845682144165], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.26094651222229]], 1051900: [[IS, GC, [soma,
          basal, apical], AMPA, weight, 3.263845682144165], [IS, IS, [apical, basal,
          soma], GABA_A, weight, 1.26094651222229]], 1052649: [[IS, GC, [soma, basal,
          apical], AMPA, weight, 3.263845682144165], [IS, IS, [apical, basal, soma],
        GABA_A, weight, 1.26094651222229]]}}
