{IS: {1049650: [[IS, GC, [soma, basal, apical], AMPA, weight, 3.812782049179077],
      [IS, IS, [apical, basal, soma], GABA_A, weight, 1.3337140083312988]], 1050400: [
      [IS, GC, [soma, basal, apical], AMPA, weight, 3.812782049179077], [IS, IS, [
          apical, basal, soma], GABA_A, weight, 1.3337140083312988]], 1051150: [[
        IS, GC, [soma, basal, apical], AMPA, weight, 3.812782049179077], [IS, IS,
        [apical, basal, soma], GABA_A, weight, 1.3337140083312988]], 1051900: [[IS,
        GC, [soma, basal, apical], AMPA, weight, 3.812782049179077], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.3337140083312988]], 1052649: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 3.812782049179077], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.3337140083312988]]}}
