{IS: {1049650: [[IS, GC, [soma, basal, apical], AMPA, weight, 2.250237464904785],
      [IS, IS, [apical, basal, soma], GABA_A, weight, 0.3349410593509674]], 1050400: [
      [IS, GC, [soma, basal, apical], AMPA, weight, 2.250237464904785], [IS, IS, [
          apical, basal, soma], GABA_A, weight, 0.3349410593509674]], 1051150: [[
        IS, GC, [soma, basal, apical], AMPA, weight, 2.250237464904785], [IS, IS,
        [apical, basal, soma], GABA_A, weight, 0.3349410593509674]], 1051900: [[IS,
        GC, [soma, basal, apical], AMPA, weight, 2.250237464904785], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 0.3349410593509674]], 1052649: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 2.250237464904785], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 0.3349410593509674]]}}
