{IS: {1049650: [[IS, GC, [soma, basal, apical], AMPA, weight, 2.936863422393799],
      [IS, IS, [apical, basal, soma], GABA_A, weight, 1.792504072189331]], 1050400: [
      [IS, GC, [soma, basal, apical], AMPA, weight, 2.936863422393799], [IS, IS, [
          apical, basal, soma], GABA_A, weight, 1.792504072189331]], 1051150: [[IS,
        GC, [soma, basal, apical], AMPA, weight, 2.936863422393799], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.792504072189331]], 1051900: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 2.936863422393799], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.792504072189331]], 1052649: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 2.936863422393799], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.792504072189331]]}}
