{IS: {1049650: [[IS, GC, [soma, basal, apical], AMPA, weight, 3.0168721675872803],
      [IS, IS, [apical, basal, soma], GABA_A, weight, 1.0990978479385376]], 1050400: [
      [IS, GC, [soma, basal, apical], AMPA, weight, 3.0168721675872803], [IS, IS,
        [apical, basal, soma], GABA_A, weight, 1.0990978479385376]], 1051150: [[IS,
        GC, [soma, basal, apical], AMPA, weight, 3.0168721675872803], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.0990978479385376]], 1051900: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 3.0168721675872803], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.0990978479385376]], 1052649: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 3.0168721675872803], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.0990978479385376]]}}
