{IS: {1049650: [[IS, GC, [soma, basal, apical], AMPA, weight, 3.2578659057617188],
      [IS, IS, [apical, basal, soma], GABA_A, weight, 1.2533844709396362]], 1050400: [
      [IS, GC, [soma, basal, apical], AMPA, weight, 3.2578659057617188], [IS, IS,
        [apical, basal, soma], GABA_A, weight, 1.2533844709396362]], 1051150: [[IS,
        GC, [soma, basal, apical], AMPA, weight, 3.2578659057617188], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.2533844709396362]], 1051900: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 3.2578659057617188], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.2533844709396362]], 1052649: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 3.2578659057617188], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.2533844709396362]]}}
