{IS: {1049650: [[IS, GC, [soma, basal, apical], AMPA, weight, 2.1871347427368164],
      [IS, IS, [apical, basal, soma], GABA_A, weight, 0.1247621402144432]], 1050400: [
      [IS, GC, [soma, basal, apical], AMPA, weight, 2.1871347427368164], [IS, IS,
        [apical, basal, soma], GABA_A, weight, 0.1247621402144432]], 1051150: [[IS,
        GC, [soma, basal, apical], AMPA, weight, 2.1871347427368164], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 0.1247621402144432]], 1051900: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 2.1871347427368164], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 0.1247621402144432]], 1052649: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 2.1871347427368164], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 0.1247621402144432]]}}
