{IS: {1049650: [[IS, GC, [soma, basal, apical], AMPA, weight, 2.752056360244751],
      [IS, IS, [apical, basal, soma], GABA_A, weight, 1.1725962162017822]], 1050400: [
      [IS, GC, [soma, basal, apical], AMPA, weight, 3.180818557739258], [IS, IS, [
          apical, basal, soma], GABA_A, weight, 1.1369893550872803]], 1051150: [[
        IS, GC, [soma, basal, apical], AMPA, weight, 3.214696168899536], [IS, IS,
        [apical, basal, soma], GABA_A, weight, 1.3288230895996094]], 1051900: [[IS,
        GC, [soma, basal, apical], AMPA, weight, 3.604074478149414], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.0688354969024658]], 1052649: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 2.332714796066284], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 0.7882453799247742]]}}
