{IS: {1049650: [[IS, GC, [soma, basal, apical], AMPA, weight, 3.3411471843719482],
      [IS, IS, [apical, basal, soma], GABA_A, weight, 1.2733036279678345]], 1050400: [
      [IS, GC, [soma, basal, apical], AMPA, weight, 3.3411471843719482], [IS, IS,
        [apical, basal, soma], GABA_A, weight, 1.2733036279678345]], 1051150: [[IS,
        GC, [soma, basal, apical], AMPA, weight, 3.3411471843719482], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.2733036279678345]], 1051900: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 3.3411471843719482], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.2733036279678345]], 1052649: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 3.3411471843719482], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.2733036279678345]]}}
