{IS: {1049650: [[IS, GC, [soma, basal, apical], AMPA, weight, 2.927414655685425],
      [IS, IS, [apical, basal, soma], GABA_A, weight, 1.770465612411499]], 1050400: [
      [IS, GC, [soma, basal, apical], AMPA, weight, 2.927414655685425], [IS, IS, [
          apical, basal, soma], GABA_A, weight, 1.770465612411499]], 1051150: [[IS,
        GC, [soma, basal, apical], AMPA, weight, 2.927414655685425], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.770465612411499]], 1051900: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 2.927414655685425], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.770465612411499]], 1052649: [[IS, GC, [
          soma, basal, apical], AMPA, weight, 2.927414655685425], [IS, IS, [apical,
          basal, soma], GABA_A, weight, 1.770465612411499]]}}
