{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.1262909322977066], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        0.9728596806526184], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.16423463821411133]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.1262909322977066], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        0.9728596806526184], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.16423463821411133]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.1262909322977066], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        0.9728596806526184], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.16423463821411133]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.1262909322977066], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        0.9728596806526184], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.16423463821411133]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.1262909322977066], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        0.9728596806526184], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.16423463821411133]]}}
