{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.009999999776482582], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.6345201730728149], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.05000000074505806]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.01224763598293066], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.6612417101860046], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.05804065987467766]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.013112963177263737], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.7083243727684021], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.051929157227277756]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.013024494983255863], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.927691638469696], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.051974888890981674]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.009999999776482582], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.507955014705658], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.05000000074505806]]}}
