{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.0723588764667511], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        0.6124724745750427], [MOPP, NGFC, apical, GABA_B, weight, 0.18598231673240662]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.0723588764667511], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        0.6124724745750427], [MOPP, NGFC, apical, GABA_B, weight, 0.18598231673240662]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.0723588764667511], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        0.6124724745750427], [MOPP, NGFC, apical, GABA_B, weight, 0.18598231673240662]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.0723588764667511], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        0.6124724745750427], [MOPP, NGFC, apical, GABA_B, weight, 0.18598231673240662]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.0723588764667511], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        0.6124724745750427], [MOPP, NGFC, apical, GABA_B, weight, 0.18598231673240662]]}}
