{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.02875390462577343], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.1311410665512085], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.3799174726009369]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.02875390462577343], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.1311410665512085], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.3799174726009369]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.02875390462577343], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.1311410665512085], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.3799174726009369]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.02875390462577343], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.1311410665512085], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.3799174726009369]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.02875390462577343], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.1311410665512085], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.3799174726009369]]}}
