{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.2616214454174042], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.2068283557891846], [MOPP, NGFC, apical, GABA_B, weight, 0.0794731080532074]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.2616214454174042], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.2068283557891846], [MOPP, NGFC, apical, GABA_B, weight, 0.0794731080532074]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.2616214454174042], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.2068283557891846], [MOPP, NGFC, apical, GABA_B, weight, 0.0794731080532074]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.2616214454174042], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.2068283557891846], [MOPP, NGFC, apical, GABA_B, weight, 0.0794731080532074]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.2616214454174042], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.2068283557891846], [MOPP, NGFC, apical, GABA_B, weight, 0.0794731080532074]]}}
