{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.009999999776482582], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.7423708438873291], [MOPP, NGFC, apical, GABA_B, weight, 0.05000000074505806]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.23288075625896454], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.6612417101860046], [MOPP, NGFC, apical, GABA_B, weight, 0.05567922815680504]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.2750656008720398], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        0.8399661183357239], [MOPP, NGFC, apical, GABA_B, weight, 0.051463596522808075]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.25889313220977783], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.4936927556991577], [MOPP, NGFC, apical, GABA_B, weight, 0.051974888890981674]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.011291644535958767], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.0805375576019287], [MOPP, NGFC, apical, GABA_B, weight, 0.05000000074505806]]}}
