{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.16772077977657318], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.0962580442428589], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.12164634466171265]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.16772077977657318], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.0962580442428589], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.12164634466171265]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.16772077977657318], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.0962580442428589], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.12164634466171265]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.16772077977657318], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.0962580442428589], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.12164634466171265]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.16772077977657318], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.0962580442428589], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.12164634466171265]]}}
