{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.1980113536119461], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.6010020971298218], [MOPP, NGFC, apical, GABA_B, weight, 0.088960200548172]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.1980113536119461], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.6010020971298218], [MOPP, NGFC, apical, GABA_B, weight, 0.088960200548172]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.1980113536119461], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.6010020971298218], [MOPP, NGFC, apical, GABA_B, weight, 0.088960200548172]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.1980113536119461], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.6010020971298218], [MOPP, NGFC, apical, GABA_B, weight, 0.088960200548172]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.1980113536119461], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.6010020971298218], [MOPP, NGFC, apical, GABA_B, weight, 0.088960200548172]]}}
