{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.13007982075214386], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.1115936040878296], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.1599908471107483]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.11357816308736801], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.8279193639755249], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.20304231345653534]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.17255470156669617], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.9627957344055176], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.13245363533496857]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.13636194169521332], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.4061509370803833], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.1617831289768219]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.13354229927062988], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.0335627794265747], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.11980243027210236]]}}
