{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.13854347169399261], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.039811134338379], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.1498774141073227]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.1738009750843048], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.0508664846420288], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.13758334517478943]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.21590332686901093], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.107283592224121], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.09259781241416931]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.16992083191871643], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.1763815879821777], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.10575368255376816]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.14043524861335754], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.1069481372833252], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.12241943180561066]]}}
