{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.13722339272499084], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.0684044361114502], [MOPP, NGFC, apical, GABA_B, weight, 0.15541447699069977]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.13722339272499084], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.0684044361114502], [MOPP, NGFC, apical, GABA_B, weight, 0.15541447699069977]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.13722339272499084], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.0684044361114502], [MOPP, NGFC, apical, GABA_B, weight, 0.15541447699069977]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.13722339272499084], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.0684044361114502], [MOPP, NGFC, apical, GABA_B, weight, 0.15541447699069977]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.13722339272499084], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.0684044361114502], [MOPP, NGFC, apical, GABA_B, weight, 0.15541447699069977]]}}
