{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.26188549399375916], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.206218957901001], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.07930959016084671]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.26188549399375916], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.206218957901001], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.07930959016084671]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.26188549399375916], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.206218957901001], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.07930959016084671]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.26188549399375916], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.206218957901001], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.07930959016084671]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.26188549399375916], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.206218957901001], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.07930959016084671]]}}
