{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.22932851314544678], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.974443793296814], [MOPP, NGFC, apical, GABA_B, weight, 0.07207661867141724]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.22932851314544678], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.974443793296814], [MOPP, NGFC, apical, GABA_B, weight, 0.07207661867141724]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.22932851314544678], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.974443793296814], [MOPP, NGFC, apical, GABA_B, weight, 0.07207661867141724]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.22932851314544678], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.974443793296814], [MOPP, NGFC, apical, GABA_B, weight, 0.07207661867141724]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.22932851314544678], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.974443793296814], [MOPP, NGFC, apical, GABA_B, weight, 0.07207661867141724]]}}
