{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.2330007702112198], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.3839699029922485], [MOPP, NGFC, apical, GABA_B, weight, 0.08703672885894775]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.2330007702112198], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.3839699029922485], [MOPP, NGFC, apical, GABA_B, weight, 0.08703672885894775]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.2330007702112198], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.3839699029922485], [MOPP, NGFC, apical, GABA_B, weight, 0.08703672885894775]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.2330007702112198], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.3839699029922485], [MOPP, NGFC, apical, GABA_B, weight, 0.08703672885894775]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.2330007702112198], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.3839699029922485], [MOPP, NGFC, apical, GABA_B, weight, 0.08703672885894775]]}}
