{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.009999999776482582], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.8399661183357239], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.05000000074505806]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.009999999776482582], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.8399661183357239], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.05000000074505806]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.009999999776482582], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.8399661183357239], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.05000000074505806]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.009999999776482582], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.8399661183357239], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.05000000074505806]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.009999999776482582], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.8399661183357239], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.05000000074505806]]}}
