{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.07801250368356705], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.0529844760894775], [MOPP, NGFC, apical, GABA_B, weight, 0.18879683315753937]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.03666127100586891], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.7585564255714417], [MOPP, NGFC, apical, GABA_B, weight, 0.2427746057510376]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.23667855560779572], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.9745320677757263], [MOPP, NGFC, apical, GABA_B, weight, 0.08171216398477554]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.14883509278297424], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.4936927556991577], [MOPP, NGFC, apical, GABA_B, weight, 0.16423463821411133]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.1262909322977066], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        0.9419984221458435], [MOPP, NGFC, apical, GABA_B, weight, 0.06401541084051132]]}}
