{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.2787185609340668], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.0272685289382935], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.055549055337905884]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.2787185609340668], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.0272685289382935], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.055549055337905884]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.2787185609340668], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.0272685289382935], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.055549055337905884]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.2787185609340668], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.0272685289382935], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.055549055337905884]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.2787185609340668], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.0272685289382935], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.055549055337905884]]}}
