{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.25889313220977783], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.4936927556991577], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.051974888890981674]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.25889313220977783], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.4936927556991577], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.051974888890981674]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.25889313220977783], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.4936927556991577], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.051974888890981674]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.25889313220977783], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.4936927556991577], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.051974888890981674]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.25889313220977783], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.4936927556991577], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.051974888890981674]]}}
