{MOPP: {1052650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.11025100201368332], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 1.0530235767364502], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.14474113285541534]],
    1053650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.23288075625896454], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.8295015096664429], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.0699099451303482]],
    1054650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.2750656008720398], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        0.974443793296814], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.05538163334131241]],
    1055650: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.2119603455066681], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA, weight,
        1.0710532665252686], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.07819390296936035]],
    1056649: [[MOPP, [HC, HCC, MOPP, NGFC], [apical, basal, soma], GABA_A, weight,
        0.12637650966644287], [MOPP, [MPP, LPP, MC], [soma, basal, apical], AMPA,
        weight, 0.9725940227508545], [MOPP, NGFC, 'apical,', GABA_B, weight, 0.06391699612140656]]}}
