{NGFC: {1044650: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight,
        0.037588488310575485], [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight,
        0.9743298888206482], [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.6940471529960632]],
    1045900: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.037588488310575485],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 0.9743298888206482],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.6940471529960632]], 1047150: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.037588488310575485],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 0.9743298888206482],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.6940471529960632]], 1048400: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.037588488310575485],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 0.9743298888206482],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.6940471529960632]], 1049640: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.037588488310575485],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 0.9743298888206482],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.6940471529960632]]}}
