{NGFC: {1044650: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight,
        0.28434687852859497], [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.2368996143341064], [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.3543044924736023]],
    1045900: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.28434687852859497],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.2368996143341064],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.3543044924736023]], 1047150: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.28434687852859497],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.2368996143341064],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.3543044924736023]], 1048400: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.28434687852859497],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.2368996143341064],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.3543044924736023]], 1049640: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.28434687852859497],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.2368996143341064],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.3543044924736023]]}}
