{NGFC: {1044650: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight,
        0.16166818141937256], [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.1840450763702393], [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.44083479046821594]],
    1045900: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.16166818141937256],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.1840450763702393],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.44083479046821594]], 1047150: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.16166818141937256],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.1840450763702393],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.44083479046821594]], 1048400: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.16166818141937256],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.1840450763702393],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.44083479046821594]], 1049640: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.16166818141937256],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.1840450763702393],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.44083479046821594]]}}
