{NGFC: {1044650: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight,
        0.009999999776482582], [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight,
        0.34670141339302063], [NGFC, NGFC, [apical, basal, soma], GABA_B, weight,
        0.05000000074505806]], 1045900: [[NGFC, [HC, NGFC, MOPP], [apical, basal,
          soma], GABA_A, weight, 0.009999999776482582], [NGFC, [MPP, LPP], [soma,
          basal, apical], AMPA, weight, 0.34670141339302063], [NGFC, NGFC, [apical,
          basal, soma], GABA_B, weight, 0.05000000074505806]], 1047150: [[NGFC, [
          HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.009999999776482582],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 0.34670141339302063],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.05000000074505806]], 1048400: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.009999999776482582],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 0.34670141339302063],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.05000000074505806]], 1049640: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.009999999776482582],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 0.34670141339302063],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.05000000074505806]]}}
