{NGFC: {1044650: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight,
        0.23106665909290314], [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.8666101694107056], [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.6033984422683716]],
    1045900: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.23106665909290314],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.8666101694107056],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.6033984422683716]], 1047150: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.23106665909290314],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.8666101694107056],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.6033984422683716]], 1048400: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.23106665909290314],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.8666101694107056],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.6033984422683716]], 1049640: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.23106665909290314],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.8666101694107056],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.6033984422683716]]}}
