{NGFC: {1044650: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight,
        0.16166818141937256], [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.4000722169876099], [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.6606613993644714]],
    1045900: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.2182396799325943],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 0.8443829417228699],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.44083479046821594]], 1047150: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.12909035384655],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.1077492237091064],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.5294590592384338]], 1048400: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.2507350742816925],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.04435133934021], [
        NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.30580803751945496]],
    1049640: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.5594525337219238],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.4822405576705933],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.15414343774318695]]}}
