{NGFC: {1044650: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight,
        0.009999999776482582], [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight,
        0.6599008440971375], [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.060309622436761856]],
    1045900: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.009999999776482582],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 0.6599008440971375],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.060309622436761856]],
    1047150: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.009999999776482582],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 0.6599008440971375],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.060309622436761856]],
    1048400: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.009999999776482582],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 0.6599008440971375],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.060309622436761856]],
    1049640: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.009999999776482582],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 0.6599008440971375],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.060309622436761856]]}}
