{NGFC: {1044650: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight,
        0.16166818141937256], [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight,
        1.5095077753067017], [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.6606613993644714]],
    1045900: [[NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.16166818141937256],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.5095077753067017],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.6606613993644714]], 1047150: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.16166818141937256],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.5095077753067017],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.6606613993644714]], 1048400: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.16166818141937256],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.5095077753067017],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.6606613993644714]], 1049640: [
      [NGFC, [HC, NGFC, MOPP], [apical, basal, soma], GABA_A, weight, 0.16166818141937256],
      [NGFC, [MPP, LPP], [soma, basal, apical], AMPA, weight, 1.5095077753067017],
      [NGFC, NGFC, [apical, basal, soma], GABA_B, weight, 0.6606613993644714]]}}
